// Port-specific qstrs — short attrs that must stay in the global pool.
// Do not Q() dotted module names or package segment names also emitted by frozen.
// *FORMAT-OFF*
Q(if_count)
Q(if_status)
Q(iface)
Q(services_start)
Q(peer_add)
Q(last_handshake)
Q(listen_port)
Q(compress_bound)
Q(compress)
Q(decompress)
Q(format_bytes)
Q(from_string)
Q(pad_len)
Q(user_check)
Q(hash_verify)
Q(verify_mods)
Q(available)
Q(autoload)
Q(client_exec)
Q(banner_send)
Q(banner_sent)
Q(banner_reset)
