# pymergetic.metal.net.ssh — Python face (C impl in __init__.c).
# µPy builtin: glue/pymergetic/metal/net/ssh.c

from typing import TypeAlias

_WriteableBuffer: TypeAlias = bytearray | memoryview

def available() -> bool: ...
def init() -> int: ...
def autoload() -> int: ...
def listen(port: int) -> int: ...
def close(s: int) -> None: ...
def poll() -> int: ...
def served() -> int: ...
def status(buf: _WriteableBuffer) -> int: ...
def listen_port() -> int: ...
def hostkey_label(buf: _WriteableBuffer) -> int: ...
def client_exec(
    host: str,
    port: int,
    user: str,
    cmd: str,
    buf: _WriteableBuffer | None = ...,
) -> int: ...
def banner_send() -> int: ...
def banner_sent() -> int: ...
def banner_reset() -> None: ...
