#ifndef PM_METAL_PY_INTERNAL_H_
#define PM_METAL_PY_INTERNAL_H_

#include <stddef.h>
#include <stdint.h>

#include <pymergetic/metal/runtime/async/async.h>

#include "py/obj.h"

#include "py_ctx.h"

typedef struct pm_metal_py_job {
  uint32_t                step;
  uint32_t                after_zip_step; /* target step once PY_STEP_ZIP resolves */
  char                   *src;
  size_t                  src_len;
  mp_obj_t                py_coro; /* async main / call_async coro, or MP_OBJ_NULL */
  mp_obj_t                call_fn; /* bound callable for PY_STEP_CALL */
  uint32_t                call_arg0;
  pm_metal_async_handle_t pending;
  mp_obj_t                pending_aw; /* awaitable obj waiting for pending */
  int                     exe_exception;
  /*
   * NULL (default): shared/default context, mPyRunLock-serialized, exactly
   * today's behavior. Non-NULL: this job exclusively owns an isolated
   * pm_metal_py_ctx_t (own heap, own VM state) for its whole lifetime — no
   * lock needed, and it can run bytecode in true parallel with every other
   * context on a different CPU. See py_ctx.h + docs/MICROPYTHON.md.
   */
  pm_metal_py_ctx_t *ctx;
} pm_metal_py_job_t;

pm_metal_py_job_t *pm_metal_py_job_current(void);
void pm_metal_py_job_set_pending(pm_metal_py_job_t *job, pm_metal_async_handle_t h, mp_obj_t aw);

void pm_metal_py_c_py_demo_seed(void);
void pm_metal_py_pmcmd_install(void);
void pm_metal_py_mod_install(void);

/*
 * Shared by py_zip.c (trust-check/HTTP-fetch-on-miss) and py_zip_embed.c
 * (writes the build-embedded copy to this same path at py_init time) —
 * one path literal, not two independently-typed #define sites.
 */
#ifndef PM_METAL_PY_STDLIB_ZIP
#define PM_METAL_PY_STDLIB_ZIP "/mods/py/stdlib.zip"
#endif
#define PM_METAL_PY_STDLIB_ZIP_SIG PM_METAL_PY_STDLIB_ZIP ".sig"

void pm_metal_py_zip_init_sys_path(void);
int  pm_metal_py_zip_ensure(void);
/** Coroutine-friendly zip ensure — see py_zip.c for the 0/-1/1 contract. */
int32_t pm_metal_py_zip_step(pm_metal_async_handle_t self_h, pm_metal_async_handle_t *out_pending);

/**
 * Writes the build-embedded stdlib.zip + .sig (py_zip_embed.inc.c,
 * generated by scripts/build.d/port/efi/embed-stdlib.sh from
 * mods/py/stdlib_src/ — see docs/MICROPYTHON.md) to PM_METAL_PY_STDLIB_ZIP
 * / _SIG. Called once from pm_metal_py_init(), before anything reads
 * those paths — so a fresh clone/build always has a locally-signed
 * stdlib.zip on "disk" with no network fetch and nothing to track in
 * git (neither the zip nor the signature, which is never byte-stable
 * across re-signs, is committed).
 */
void pm_metal_py_zip_embed_install(void);

/**
 * Flush mphalport_metal.c's cross-call stdout accumulator (see that file)
 * -- hands any buffered text with no trailing '\n' yet to
 * pm_metal_shell_out() as its own line. Call after a REPL chunk/statement
 * finishes so output like `print('x', end='')` still shows up before the
 * next ">>> " prompt instead of waiting indefinitely for a newline that
 * may never come.
 */
void pm_metal_py_stdout_flush(void);

#endif
