/**
 * @file Build-embedded stdlib.zip + .sig (py_zip_embed.inc.c, generated by
 * scripts/build.d/port/efi/embed-stdlib.sh from mods/py/stdlib/ — see
 * docs/MICROPYTHON.md). Written out to PM_METAL_PY_STDLIB_ZIP / _SIG once
 * at py_init time so py_zip.c's file-based trust-check/import machinery
 * (ZipVerifyLocal, HTTP-fetch-on-miss) runs completely unchanged; neither
 * the zip nor the signature is tracked in git, both are always freshly
 * rebuilt+resigned from source and baked into the binary instead.
 */
#include <pymergetic/metal/fs/fs.h>
#include <pymergetic/metal/log/log.h>

#include "py_internal.h"

#include "py_zip_embed.inc.c"

void pm_metal_py_zip_embed_install(void)
{
  if (pm_metal_fs_write(PM_METAL_PY_STDLIB_ZIP, g_pm_metal_stdlib_zip, g_pm_metal_stdlib_zip_len) !=
      g_pm_metal_stdlib_zip_len) {
    pm_metal_log("py: embedded stdlib.zip write failed");
    return;
  }
  if (pm_metal_fs_write(PM_METAL_PY_STDLIB_ZIP_SIG,
                        g_pm_metal_stdlib_zip_sig,
                        g_pm_metal_stdlib_zip_sig_len) != g_pm_metal_stdlib_zip_sig_len) {
    pm_metal_log("py: embedded stdlib.zip.sig write failed");
  }
}
