# DO NOT EDIT — generated by `pymergetic.util.gen` (live µPy import).
# pymergetic.metal.boot.tree

from typing import Any

def motd(*args: Any, **kwargs: Any) -> Any: ...

def print(*args: Any, **kwargs: Any) -> Any: ...

def shutdown(*args: Any, **kwargs: Any) -> Any: ...

