#!/usr/bin/env bash
# Build EFI-embedded guest mods (no wasi-threads) → embed_mods.inc.c
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
WASI_SDK="${ROOT}/.tools/wasi-sdk"
CLANG="${WASI_SDK}/bin/clang"
SYSROOT="${WASI_SDK}/share/wasi-sysroot"
OUT_DIR="${ROOT}/build/efi/embed"
INC_OUT="${ROOT}/src/pymergetic/metal/guest/wasm/embed_mods.inc.c"
# Classic wasip1 — no thread imports (EFI WAMR has no wasi-threads).
TARGET=wasm32-wasip1

if [[ ! -x "${CLANG}" ]]; then
	echo "embed-mods: wasi-sdk missing (${CLANG})" >&2
	exit 1
fi

mkdir -p "${OUT_DIR}"

build_one() {
	local name src out
	name="$1"
	src="$2"
	shift 2
	out="${OUT_DIR}/${name}.wasm"
	echo "embed-mods: ${name}"
	"${CLANG}" \
		--target="${TARGET}" \
		--sysroot="${SYSROOT}" \
		-O2 -Wall -Wextra \
		-I "${ROOT}/include" \
		-Wl,--export=main \
		-Wl,--export=malloc \
		-Wl,--export=free \
		"$@" \
		-Wl,--allow-undefined \
		-o "${out}" \
		"${src}"
}

build_one hello "${ROOT}/mods/tests/t0_hello/main.c"
build_one ui_hello "${ROOT}/mods/tests/t_ui_hello/main.c"
build_one async_sleep "${ROOT}/mods/tests/t_async_sleep/main.c" \
	-Wl,--export=pm_metal_guest_step
build_one async_fs "${ROOT}/mods/tests/t_async_fs/main.c" \
	-Wl,--export=pm_metal_guest_step
build_one async_fs_fd "${ROOT}/mods/tests/t_async_fs_fd/main.c" \
	-Wl,--export=pm_metal_guest_step
build_one async_time "${ROOT}/mods/tests/t_async_time/main.c" \
	-Wl,--export=pm_metal_guest_step
build_one async_net "${ROOT}/mods/tests/t_async_net/main.c" \
	-Wl,--export=pm_metal_guest_step
build_one async_ping "${ROOT}/mods/tests/t_async_ping/main.c" \
	-Wl,--export=pm_metal_guest_step
build_one async_http "${ROOT}/mods/tests/t_async_http/main.c" \
	-Wl,--export=pm_metal_guest_step
build_one async_tftp "${ROOT}/mods/tests/t_async_tftp/main.c" \
	-Wl,--export=pm_metal_guest_step
build_one async_audio "${ROOT}/mods/tests/t_async_audio/main.c" \
	-Wl,--export=pm_metal_guest_step
build_one async_blk "${ROOT}/mods/tests/t_async_blk/main.c" \
	-Wl,--export=pm_metal_guest_step

# AOT proof embed (same guest as async_sleep) — both host arches, always.
# Lookup: run async_aot → async_aot.{x86_64,i386} by BUILD_TARGET.
# shellcheck disable=SC1091
source "${ROOT}/scripts/lib/aot.sh"
rm -f "${OUT_DIR}/async_aot.aot" "${OUT_DIR}/async_aot.aot.sig"
if ! pm_metal_aot_compile_all "${OUT_DIR}/async_sleep.wasm" "${OUT_DIR}/async_aot"; then
	echo "embed-mods: async_aot skipped (./scripts/setup wamrc)" >&2
fi

python3 - "${OUT_DIR}" "${INC_OUT}" <<'PY'
import pathlib, sys, re

out_dir = pathlib.Path(sys.argv[1])
inc_out = pathlib.Path(sys.argv[2])
mods = [
    ("hello", out_dir / "hello.wasm"),
    ("ui_hello", out_dir / "ui_hello.wasm"),
    ("async_sleep", out_dir / "async_sleep.wasm"),
    ("async_fs", out_dir / "async_fs.wasm"),
    ("async_fs_fd", out_dir / "async_fs_fd.wasm"),
    ("async_time", out_dir / "async_time.wasm"),
    ("async_net", out_dir / "async_net.wasm"),
    ("async_ping", out_dir / "async_ping.wasm"),
    ("async_http", out_dir / "async_http.wasm"),
    ("async_tftp", out_dir / "async_tftp.wasm"),
    ("async_audio", out_dir / "async_audio.wasm"),
    ("async_blk", out_dir / "async_blk.wasm"),
]
# Whatever pm_metal_aot_compile_all produced (x86_64/i386/aarch64/arm/…).
for aot in sorted(out_dir.glob("async_aot.*.aot")):
    if aot.stat().st_size > 0:
        mods.append((aot.stem, aot))  # async_aot.x86_64, …

def c_ident(name: str) -> str:
    return "g_pm_metal_embed_" + re.sub(r"[^A-Za-z0-9_]", "_", name)

# Uefi.h before BaseLib — BaseLib alone does not define CONST/CHAR8/UINT*.
lines = [
    "/* AUTO-GENERATED by scripts/build.d/port/efi/embed-mods.sh — do not edit */",
    "#include <Uefi.h>",
    "#include <Library/BaseLib.h>",
    "",
    "typedef struct {",
    "  CONST CHAR8   *name;",
    "  CONST UINT8   *bytes;",
    "  UINT32         len;",
    "} pm_metal_embed_mod_t;",
    "",
]

for name, path in mods:
    data = path.read_bytes()
    arr = c_ident(name)
    lines.append(f"STATIC CONST UINT8 {arr}[{len(data)}] = {{")
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")

lines.append("STATIC CONST pm_metal_embed_mod_t g_pm_metal_embed_mods[] = {")
for name, path in mods:
    data = path.read_bytes()
    lines.append(
        f'  {{ "{name}", {c_ident(name)}, {len(data)} }},'
    )
lines.append("};")
lines.append("")
lines.append(
    f"STATIC CONST UINT32 g_pm_metal_embed_mod_count = {len(mods)};"
)
lines.append("")

inc_out.write_text("\n".join(lines) + "\n")
nbytes = sum(p.stat().st_size for _, p in mods)
print(f"embed-mods: wrote {inc_out} ({nbytes} guest bytes, {len(mods)} mods)")
PY
