#!/usr/bin/env bash
# Pack iface header (+ optional sources) + meta packs into
# src/pymergetic/metal/util/iface_metal_guest_embed.inc.c — lz4(ustar).
#
# Kconfig (config/metal/util/Kconfig.iface):
#   CONFIG_PM_METAL_IFACE_EMBED_HEADERS — metal.guest + meta/docs + mod.t8
#   CONFIG_PM_METAL_IFACE_EMBED_SOURCES — metal.guest.sources (depends on headers)
#
#   metal.guest          — metal.h's own #include list + wasi.h +
#                          guest/mod/*.h + version.h (curated allowlist)
#   metal.guest.sources  — full rebuild tree for later JIT / in-guest rebuild:
#                          src/pymergetic/metal + src/{efi,bios}/pymergetic/metal
#                          + include/pymergetic/metal  (.c / .S / .s / .h).
#                          Skips *.inc.c (AUTO-GENERATED embeds, fonts, fw, syms).
#   metal.guest.meta     — LICENSE + README.md (kind meta)
#   metal.guest.docs     — docs/*.md (kind meta)
#   mod.t8_multimod_lib  — mods/tests/t8_multimod_lib/include/*.h
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
INCLUDE_METAL="${ROOT}/include/pymergetic/metal"
METAL_H="${INCLUDE_METAL}/metal.h"
DOCS_DIR="${ROOT}/docs"
T8_INCLUDE="${ROOT}/mods/tests/t8_multimod_lib/include"
INC_OUT="${ROOT}/src/pymergetic/metal/util/iface_metal_guest_embed.inc.c"
# Paths relative to ROOT staged into metal.guest.sources.
SOURCES_TREES=(
	"src/pymergetic/metal"
	"src/efi/pymergetic/metal"
	"src/bios/pymergetic/metal"
	"include/pymergetic/metal"
)

# shellcheck disable=SC1091
source "${ROOT}/scripts/lib/kconfig.sh"
pm_metal_kconfig_load

EMBED_HEADERS="${CONFIG_PM_METAL_IFACE_EMBED_HEADERS:-y}"
EMBED_SOURCES="${CONFIG_PM_METAL_IFACE_EMBED_SOURCES:-n}"

write_empty_install() {
	cat >"${INC_OUT}" <<'EOF'
/* AUTO-GENERATED by scripts/build.d/port/efi/embed-iface.sh — do not edit */
#include <stdint.h>
#include <pymergetic/metal/util/iface.h>

void pm_metal_iface_embed_install(void);
void pm_metal_iface_embed_install(void) {}
EOF
	echo "embed-iface: headers disabled — empty install -> ${INC_OUT}" >&2
}

if [[ "${EMBED_HEADERS}" != "y" ]]; then
	write_empty_install
	exit 0
fi

if [[ ! -f "${METAL_H}" ]]; then
	echo "embed-iface: missing ${METAL_H}" >&2
	exit 1
fi

TMP="$(mktemp -d)"
# shellcheck disable=SC1091
source "${ROOT}/scripts/lib/iface-pack.sh"
trap 'pm_metal_iface_pack_cleanup; rm -rf "${TMP}"' EXIT
pm_metal_iface_pack_init

# Args: stage_dir pkg_name c_ident version KIND_MACRO
pack_one() {
	local stage="$1" name="$2" ident="$3" version="$4" kind="$5"
	local blob_path uncompressed_len
	blob_path="${TMP}/${ident}.tar.lz4"

	uncompressed_len="$(pm_metal_iface_pack_dir "${stage}" "${blob_path}")"

	echo "static const uint8_t g_pm_metal_iface_embed_${ident}[] = {"
	od -An -v -tx1 "${blob_path}" | sed 's/ \([0-9a-f][0-9a-f]\)/ 0x\1,/g'
	echo "};"
	echo "static const uint32_t g_pm_metal_iface_embed_${ident}_len = sizeof(g_pm_metal_iface_embed_${ident});"
	echo "static const uint32_t g_pm_metal_iface_embed_${ident}_uncompressed_len = ${uncompressed_len}u;"
	echo ""
	REGISTER_CALLS+=("  (void)pm_metal_iface_pkg_register(\"${name}\", ${kind}, \"${version}\", \"\", g_pm_metal_iface_embed_${ident}, g_pm_metal_iface_embed_${ident}_len, g_pm_metal_iface_embed_${ident}_uncompressed_len);")

	echo "embed-iface: ${name} (${kind}) <- ${stage} (${uncompressed_len} ustar -> $(wc -c <"${blob_path}" | tr -d ' ') lz4)" >&2
}

REGISTER_CALLS=()

STAGE_GUEST="${TMP}/stage_guest"
mkdir -p "${STAGE_GUEST}"

mapfile -t GUEST_HEADERS < <(
	grep -oE '"pymergetic/metal/[A-Za-z0-9_./]+\.h"' "${METAL_H}" | tr -d '"'
	echo "pymergetic/metal/wasi.h"
	echo "pymergetic/metal/version.h"
	find "${INCLUDE_METAL}/guest/mod" -maxdepth 1 -name '*.h' -printf 'pymergetic/metal/guest/mod/%f\n' 2>/dev/null || true
)

for rel in "${GUEST_HEADERS[@]}"; do
	src="${ROOT}/include/${rel}"
	if [[ ! -f "${src}" ]]; then
		echo "embed-iface: missing header ${rel}, skipped" >&2
		continue
	fi
	dst="${STAGE_GUEST}/${rel#pymergetic/metal/}"
	mkdir -p "$(dirname "${dst}")"
	cp -f "${src}" "${dst}"
done

STAGE_SOURCES=""
if [[ "${EMBED_SOURCES}" == "y" ]]; then
	STAGE_SOURCES="${TMP}/stage_sources"
	mkdir -p "${STAGE_SOURCES}"
	src_n=0
	for tree in "${SOURCES_TREES[@]}"; do
		abs="${ROOT}/${tree}"
		if [[ ! -d "${abs}" ]]; then
			echo "embed-iface: sources tree missing, skip ${tree}" >&2
			continue
		fi
		while IFS= read -r -d '' src; do
			rel="${src#"${ROOT}"/}"
			dst="${STAGE_SOURCES}/${rel}"
			mkdir -p "$(dirname "${dst}")"
			cp -f "${src}" "${dst}"
			src_n=$((src_n + 1))
		done < <(
			# No *.inc.c — those are generated embeds / binary-as-C (mods zip,
			# py zip, iface packs, fonts, fw, sym tables), not JIT inputs.
			find "${abs}" -type f \( -name '*.c' -o -name '*.S' -o -name '*.s' -o -name '*.h' \) \
				! -name '*.inc.c' -print0
		)
	done
	echo "embed-iface: sources pack staged ${src_n} files (c/S/s/h, no *.inc.c)" >&2
	if [[ "${src_n}" -eq 0 ]]; then
		echo "embed-iface: warning — no sources staged; skipping sources pack" >&2
		STAGE_SOURCES=""
	fi
fi

STAGE_META="${TMP}/stage_meta"
mkdir -p "${STAGE_META}"
meta_n=0
for f in LICENSE README.md; do
	if [[ -f "${ROOT}/${f}" ]]; then
		cp -f "${ROOT}/${f}" "${STAGE_META}/${f}"
		meta_n=$((meta_n + 1))
	else
		echo "embed-iface: missing ${f}, skipped for metal.guest.meta" >&2
	fi
done
if [[ "${meta_n}" -eq 0 ]]; then
	echo "embed-iface: warning — no meta files staged; skipping metal.guest.meta" >&2
	STAGE_META=""
fi

STAGE_DOCS=""
if [[ -d "${DOCS_DIR}" ]]; then
	STAGE_DOCS="${TMP}/stage_docs"
	mkdir -p "${STAGE_DOCS}"
	docs_n=0
	while IFS= read -r -d '' src; do
		base="$(basename "${src}")"
		cp -f "${src}" "${STAGE_DOCS}/${base}"
		docs_n=$((docs_n + 1))
	done < <(find "${DOCS_DIR}" -maxdepth 1 -type f -name '*.md' -print0 | sort -z)
	echo "embed-iface: docs pack staged ${docs_n} files (docs/*.md)" >&2
	if [[ "${docs_n}" -eq 0 ]]; then
		echo "embed-iface: warning — no docs/*.md staged; skipping metal.guest.docs" >&2
		STAGE_DOCS=""
	fi
else
	echo "embed-iface: ${DOCS_DIR} missing, metal.guest.docs pack skipped" >&2
fi

METAL_VERSION="$(git -C "${ROOT}" describe --tags --dirty --always 2>/dev/null || echo "0.0.0-unknown")"

{
	echo "/* AUTO-GENERATED by scripts/build.d/port/efi/embed-iface.sh — do not edit */"
	echo "#include <stdint.h>"
	echo "#include <pymergetic/metal/util/iface.h>"
	echo ""
	pack_one "${STAGE_GUEST}" "metal.guest" "metal_guest" "${METAL_VERSION}" "PM_METAL_IFACE_PKG_HEADERS"

	if [[ -n "${STAGE_SOURCES}" ]]; then
		pack_one "${STAGE_SOURCES}" "metal.guest.sources" "metal_guest_sources" "${METAL_VERSION}" "PM_METAL_IFACE_PKG_SOURCES"
	fi

	if [[ -n "${STAGE_META}" ]]; then
		pack_one "${STAGE_META}" "metal.guest.meta" "metal_guest_meta" "${METAL_VERSION}" "PM_METAL_IFACE_PKG_META"
	fi

	if [[ -n "${STAGE_DOCS}" ]]; then
		pack_one "${STAGE_DOCS}" "metal.guest.docs" "metal_guest_docs" "${METAL_VERSION}" "PM_METAL_IFACE_PKG_META"
	fi

	if [[ -d "${T8_INCLUDE}" ]]; then
		pack_one "${T8_INCLUDE}" "mod.t8_multimod_lib" "mod_t8_multimod_lib" "" "PM_METAL_IFACE_PKG_HEADERS"
	else
		echo "embed-iface: ${T8_INCLUDE} missing, mod.t8_multimod_lib pack skipped" >&2
	fi

	echo "void pm_metal_iface_embed_install(void);"
	echo "void pm_metal_iface_embed_install(void)"
	echo "{"
	for call in "${REGISTER_CALLS[@]}"; do
		echo "${call}"
	done
	echo "}"
} >"${INC_OUT}"

echo "embed-iface: wrote ${INC_OUT}"
