#!/usr/bin/env bash
# Pack two iface header packs (docs/DOC_IFACE_PLAN.md Part II-C) into
# src/pymergetic/metal/util/iface_metal_guest_embed.inc.c — lz4(ustar),
# same tar+lz4pack recipe as scripts/lib/pack-pkg.sh (adapted: an explicit
# file allowlist instead of "the whole directory", and
# pm_metal_iface_pkg_register() instead of pm_metal_pkg_register()).
#
#   metal.guest          — metal.h's own #include list + wasi.h +
#                          guest/mod/*.h + version.h (see file comment
#                          below for why this is a curated allowlist, not
#                          a full transitive #include closure)
#   mod.t8_multimod_lib  — mods/tests/t8_multimod_lib/include/*.h (v1 seed
#                          proving a *mod* can publish its own pack, not
#                          just the kernel — Part II-E)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
INCLUDE_METAL="${ROOT}/include/pymergetic/metal"
METAL_H="${INCLUDE_METAL}/metal.h"
T8_INCLUDE="${ROOT}/mods/tests/t8_multimod_lib/include"
INC_OUT="${ROOT}/src/pymergetic/metal/util/iface_metal_guest_embed.inc.c"

if [[ ! -f "${METAL_H}" ]]; then
	echo "embed-iface: missing ${METAL_H}" >&2
	exit 1
fi

TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

CC_BIN="${CC:-cc}"
LZ4PACK_C="${TMP}/lz4pack.c"
LZ4PACK_BIN="${TMP}/lz4pack"
cat >"${LZ4PACK_C}" <<'EOF'
#include <stdio.h>
#include <stdlib.h>
#include "lz4.h"
int main(void) {
	long n; unsigned char *in; int bound, out_n; unsigned char *out;
	if (fseek(stdin, 0, SEEK_END) != 0) return 1;
	n = ftell(stdin); if (n < 0 || fseek(stdin, 0, SEEK_SET) != 0) return 1;
	in = malloc((size_t)n); if (!in || fread(in, 1, (size_t)n, stdin) != (size_t)n) return 1;
	bound = LZ4_compressBound((int)n); out = malloc((size_t)bound);
	if (!out) return 1;
	out_n = LZ4_compress_default((const char *)in, (char *)out, (int)n, bound);
	if (out_n <= 0) return 1;
	if (fwrite(out, 1, (size_t)out_n, stdout) != (size_t)out_n) return 1;
	return 0;
}
EOF
"${CC_BIN}" -O2 -I "${ROOT}/external/lz4/lib" -o "${LZ4PACK_BIN}" "${LZ4PACK_C}" \
	"${ROOT}/external/lz4/lib/lz4.c"

# --- pack one directory tree of files into a C byte array + emit its
#     pm_metal_iface_pkg_register() call. Args: stage_dir pkg_name c_ident version ---
pack_one() {
	local stage="$1" name="$2" ident="$3" version="$4"
	local tar_path blob_path uncompressed_len
	tar_path="${TMP}/${ident}.tar"
	blob_path="${TMP}/${ident}.tar.lz4"

	tar --format=ustar -cf "${tar_path}" -C "${stage}" .
	uncompressed_len="$(wc -c <"${tar_path}" | tr -d ' ')"
	"${LZ4PACK_BIN}" <"${tar_path}" >"${blob_path}"

	echo "static const uint8_t g_pm_metal_iface_embed_${ident}[] = {"
	od -An -v -tx1 "${blob_path}" | sed 's/ \([0-9a-f][0-9a-f]\)/ 0x\1,/g'
	echo "};"
	echo "static const uint32_t g_pm_metal_iface_embed_${ident}_len = sizeof(g_pm_metal_iface_embed_${ident});"
	echo "static const uint32_t g_pm_metal_iface_embed_${ident}_uncompressed_len = ${uncompressed_len}u;"
	echo ""
	REGISTER_CALLS+=("  (void)pm_metal_iface_pkg_register(\"${name}\", PM_METAL_IFACE_PKG_HEADERS, \"${version}\", \"\", g_pm_metal_iface_embed_${ident}, g_pm_metal_iface_embed_${ident}_len, g_pm_metal_iface_embed_${ident}_uncompressed_len);")

	echo "embed-iface: ${name} <- ${stage} (${uncompressed_len} ustar bytes -> $(wc -c <"${blob_path}" | tr -d ' ') lz4 bytes)" >&2
}

REGISTER_CALLS=()

# --- metal.guest: metal.h's own direct #include list + a fixed extra set
#     (see file header — a curated allowlist, not every header those
#     headers themselves go on to include; docs/IFACE.md notes this). ---
STAGE_GUEST="${TMP}/stage_guest"
mkdir -p "${STAGE_GUEST}"

mapfile -t GUEST_HEADERS < <(
	grep -oE '"pymergetic/metal/[A-Za-z0-9_./]+\.h"' "${METAL_H}" | tr -d '"'
	echo "pymergetic/metal/wasi.h"
	echo "pymergetic/metal/version.h"
	find "${INCLUDE_METAL}/guest/mod" -maxdepth 1 -name '*.h' -printf 'pymergetic/metal/guest/mod/%f\n'
)

for rel in "${GUEST_HEADERS[@]}"; do
	src="${ROOT}/include/${rel}"
	if [[ ! -f "${src}" ]]; then
		echo "embed-iface: missing header ${rel}, skipped" >&2
		continue
	fi
	dst="${STAGE_GUEST}/${rel#pymergetic/metal/}"
	mkdir -p "$(dirname "${dst}")"
	cp -f "${src}" "${dst}"
done

METAL_VERSION="$(git -C "${ROOT}" describe --tags --dirty --always 2>/dev/null || echo "0.0.0-unknown")"

{
	# iface.h so clangd / one-file -fsyntax-only on this generated .inc.c
	# can resolve pm_metal_iface_pkg_register / PM_METAL_IFACE_PKG_HEADERS
	# (PathMatch treats *.inc.c as a TU). When pulled into
	# iface_embed_install.c the include guard makes the second include a
	# no-op — same fix as gen_iface_syms.py for iface_syms.inc.c.
	echo "/* AUTO-GENERATED by scripts/build.d/port/efi/embed-iface.sh — do not edit */"
	echo "#include <stdint.h>"
	echo "#include <pymergetic/metal/util/iface.h>"
	echo ""
	pack_one "${STAGE_GUEST}" "metal.guest" "metal_guest" "${METAL_VERSION}"

	if [[ -d "${T8_INCLUDE}" ]]; then
		pack_one "${T8_INCLUDE}" "mod.t8_multimod_lib" "mod_t8_multimod_lib" ""
	else
		echo "embed-iface: ${T8_INCLUDE} missing, mod.t8_multimod_lib pack skipped" >&2
	fi

	echo "void pm_metal_iface_embed_install(void);"
	echo "void pm_metal_iface_embed_install(void)"
	echo "{"
	for call in "${REGISTER_CALLS[@]}"; do
		echo "${call}"
	done
	echo "}"
} >"${INC_OUT}"

echo "embed-iface: wrote ${INC_OUT}"
