#!/usr/bin/env bash
# Build+sign mods/py/stdlib.zip (mods/py/build_stdlib_zip.sh), then embed
# both the zip and its .sig as C byte arrays -> py_zip_embed.inc.c, so the
# port build (EFI or BIOS — this script is shared, mirrors embed-mods.sh)
# compiles a self-contained stdlib.zip straight into the firmware image.
#
# Neither mods/py/stdlib.zip nor its .sig is tracked in git (both are
# regenerated from mods/py/stdlib_src/ on every build, and the .sig is
# never byte-stable across re-signs) — see docs/MICROPYTHON.md. This
# script, run unconditionally by both port builds, is what replaces
# "committed to git" with "always freshly baked into the binary".
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
ZIP="${ROOT}/mods/py/stdlib.zip"
SIG="${ZIP}.sig"
INC_OUT="${ROOT}/src/pymergetic/metal/py/py_zip_embed.inc.c"

"${ROOT}/mods/py/build_stdlib_zip.sh"

[[ -f "${ZIP}" ]] || {
	echo "embed-stdlib: missing ${ZIP} after build_stdlib_zip.sh" >&2
	exit 1
}
[[ -f "${SIG}" ]] || {
	echo "embed-stdlib: missing ${SIG} — scripts/pki not set up?" >&2
	exit 1
}

python3 - "${ZIP}" "${SIG}" "${INC_OUT}" <<'PY'
import pathlib
import sys

zip_path, sig_path, inc_out = (pathlib.Path(p) for p in sys.argv[1:4])


def emit(lines, ident, data):
    lines.append(f"static const uint8_t {ident}[{len(data)}] = {{")
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")


zip_data = zip_path.read_bytes()
sig_data = sig_path.read_bytes()

lines = [
    "/* AUTO-GENERATED by scripts/build.d/port/efi/embed-stdlib.sh — do not edit */",
    "#include <stdint.h>",
    "",
]
emit(lines, "g_pm_metal_stdlib_zip", zip_data)
emit(lines, "g_pm_metal_stdlib_zip_sig", sig_data)
lines.append(f"static const uint32_t g_pm_metal_stdlib_zip_len = {len(zip_data)};")
lines.append(f"static const uint32_t g_pm_metal_stdlib_zip_sig_len = {len(sig_data)};")
lines.append("")

inc_out.write_text("\n".join(lines) + "\n")
print(
    f"embed-stdlib: wrote {inc_out} "
    f"({len(zip_data)} zip bytes, {len(sig_data)} sig bytes)"
)
PY
