[package]
name = "pymergetic_metal_wasm"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
path = "../__init__.rs"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "smoke"
path = "smoke.rs"

[dependencies]
pymergetic_metal_rt = { path = "../../rt/.pm" }
pymergetic_metal_mem = { path = "../../mem/.pm" }
pymergetic_metal_reg = { path = "../../reg/.pm" }
pymergetic_metal_log = { path = "../../log/.pm" }
pymergetic_metal_async = { path = "../../async/.pm" }

[build-dependencies]
cc = "1"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
