# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal`` — generated package re-exports (scripts/gen_py_stubs.py).
"""

from typing import Any

from . import aio as aio
from . import audio as audio
from . import authors as authors
from . import doc as doc
from . import externals as externals
from . import fs as fs
from . import iface as iface
from . import mod as mod
from . import net as net
from . import process as process
from . import random as random
from . import tar as tar
from . import time as time

__all__ = ['aio', 'audio', 'authors', 'doc', 'externals', 'fs', 'iface', 'mod', 'net', 'process', 'random', 'tar', 'time']
__path__: list[str]

def __getattr__(name: str) -> Any: ...
