# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.aio`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/runtime/async/async_py_bind.c
"""

from typing import Any

def mono_us(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def sleep_us(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def yield_(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
