"""Typing face (matrix Py count = max(glue,.pyi))."""

def current(*args, **kwargs): ...
def name(*args, **kwargs): ...
def firmware(*args, **kwargs): ...
def py_name(*args, **kwargs): ...
def py_names(*args, **kwargs): ...
