"""pymergetic.metal.async — µPy face over C async engine."""

def status(h: int) -> int: ...
def set_result_u32(h: int, v: int) -> None: ...
def result_u32(h: int) -> int: ...
def completed_u32(h: int) -> int: ...
def coro_close(h: int) -> None: ...
def start(h: int) -> int: ...
def ready() -> int: ...
def n_runners() -> int: ...
def create_task(*args) -> int: ...
def run_poll() -> int: ...
def run_poll_all() -> int: ...
def run_loop() -> None: ...
