# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.audio`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/dev/audio/audio_py_bind.c
"""

from typing import Any

def backend(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def mute(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def muted(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def ready(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def volume_get(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def volume_set(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
