def users_set(users: list[dict[str, str]]) -> None: ...
def user_check(user: str, password: str) -> bool: ...
def hash_verify(encoded: str, password: str) -> bool: ...
def basic_decode(b64: str) -> tuple[str, str] | None: ...
def pubkeys_clear() -> None: ...
def pubkey_add(user: str, algo: str, blob: bytes | bytearray | memoryview) -> bool: ...
def pubkey_add_line(user: str, line: str) -> bool: ...
def pubkey_load_text(user: str, text: str | bytes | bytearray | memoryview) -> int: ...
def pubkey_check(user: str, algo: str | None, blob: bytes | bytearray | memoryview) -> bool: ...
