"""boot face."""

def banner(*args, **kwargs): ...
def emit(*args, **kwargs): ...
def tree_ready_ok(*args, **kwargs): ...
def tree_print(*args, **kwargs): ...
def unboot() -> int: ...
def shutting_down() -> bool: ...
def shutdown() -> int: ...
def reboot() -> int: ...
def is_dead() -> bool: ...
