from collections.abc import Callable

def init(buf: bytearray | memoryview) -> int: ...
def create(id: int, buf: bytearray | memoryview) -> int: ...
def ready() -> int: ...
def ready_id(id: int) -> int: ...
def write(data: bytes | bytearray | memoryview) -> int: ...
def write_id(id: int, data: bytes | bytearray | memoryview) -> int: ...
def viewport_attach(console_id: int, sink: Callable[[bytes], object] | None) -> int: ...
def attach(sink: Callable[[bytes], object] | None) -> int: ...
def viewport_rebind(vp: int, console_id: int) -> int: ...
def viewport_detach(vp: int) -> None: ...
def detach() -> None: ...
def set_sink(sink: Callable[[bytes], object] | None) -> int: ...
def seq() -> int: ...
def len() -> int: ...
def copy_tail(out: bytearray | memoryview) -> int: ...
