# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.doc`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/util/doc_py_bind.c
"""

from typing import Any

def help(*args: Any) -> Any:
    """Joined summary/sig/body text for one bare name, any kind.

help(name: str) -> str | None

Tries the shell face first (name typically a command), else scans the whole catalog for an exact key match. None if nothing matches."""
    ...

def list(*args: Any) -> Any:
    """Enumerate the whole catalog, optionally filtered to one kind.

list(kind: str | None = None) -> list[dict]

kind is positional, not a keyword arg. Each item has the same shape as lookup()'s return value."""
    ...

def lookup(*args: Any) -> Any:
    """Direct (kind, key) catalog lookup.

lookup(kind: str, key: str) -> dict | None

kind is 'shell'/'py'/'mod'; key is a shell command name, a dotted py bind path (e.g. 'pymergetic.metal.fs.open'), or 'modname.funcname'. Returns None if unknown, else {kind, key, summary, sig, body} (sig/body are '' when that face never set them)."""
    ...

def lookup_key(*args: Any) -> Any:
    """Catalog lookup by one packed "<kind>:<key>" doc_key string.

lookup_key(doc_key: str) -> dict | None

Same result shape as lookup(); doc_key is what an iface sym table's own doc_key column points at (see pymergetic.metal.iface.sym())."""
    ...

def __getattr__(name: str) -> Any: ...
