def soft_init(buf: bytearray | memoryview, width: int, height: int, bpp: int) -> dict | None: ...
def fill(surf: dict, argb: int) -> None: ...
def pixel(surf: dict, x: int, y: int, argb: int) -> None: ...
def glyph8(surf: dict, x: int, y: int, ch: str, fg: int, bg: int) -> None: ...
def text8(surf: dict, x: int, y: int, text: str, fg: int, bg: int) -> None: ...
def checksum(surf: dict) -> int: ...
