# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.externals`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/boot/externals_py_bind.c
"""

from typing import Any

def get(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def list(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
