"""pymergetic.metal.externals — third-party stack identity registry."""

from typing import Any

def list() -> list[dict[str, str]]: ...
def get(id: str) -> dict[str, str] | None: ...
def register(id: str, version: str, url: str = "", note: str = "") -> bool: ...
def __getattr__(name: str) -> Any: ...
