"""pymergetic.metal.externals — third-party stack identity registry."""

def init() -> None: ...
def seed_fallback() -> None: ...
def count() -> int: ...
def get(idx: int) -> dict[str, str] | None: ...
def find(id: str) -> dict[str, str] | None: ...
def register(id: str, version: str, url: str = "", note: str = "") -> bool: ...
