# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.fs`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/fs/fs_py_bind.c
"""

from typing import Any

def close(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def listdir(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def lseek(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def mkdir(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def open(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def read(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def rename(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def stat(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def unlink(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def write(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
