# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.iface`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/util/iface_py_bind.c
"""

from typing import Any

def info(*args: Any) -> Any:
    """Every registered header pack, keyed by package name.

info() -> dict[str, dict]

Each value has the same shape as one list(pkg) row's own package context: {name, kind, version, abi_hash, nfiles, blob_len}."""
    ...

def list(*args: Any) -> Any:
    """Package names, or one package's own file paths.

list(pkg: str | None = None) -> list[str]

pkg is positional. Raises ValueError for an unknown package name."""
    ...

def read(*args: Any) -> Any:
    """Whole file contents from a registered header pack.

read(pkg: str, path: str) -> bytes

path is exactly what list(pkg) returned (e.g. 'pymergetic/metal/fs/fs.h'). Raises ValueError if pkg/path is unknown."""
    ...

def sym(*args: Any) -> Any:
    """List or look up scraped NativeSymbol rows.

sym(module: str | None = None, name: str | None = None) -> list[dict] | dict | None

sym() lists every row; sym(module) filters to one wasi module; sym(module, name) returns one {module, name, sig, class_, doc_key} or None. doc_key is '' unless scripts/iface_doc_keys.txt set one - pass a non-empty doc_key to doc.lookup_key() for the readable text."""
    ...

def __getattr__(name: str) -> Any: ...
