"""Typing face (matrix Py count = max(glue,.pyi))."""

def init(*args, **kwargs): ...
def capabilities_json(*args, **kwargs): ...
def handle(*args, **kwargs): ...
def py_handle(*args, **kwargs): ...
def py_create_app(*args, **kwargs): ...
def py_close(*args, **kwargs): ...
