"""pymergetic.metal.pack — µPy face."""

def mount_all() -> int: ...
def names() -> tuple[str, ...]: ...
def inspect() -> bytes: ...
def inspect_len() -> int: ...
def metal() -> bytes: ...
def metal_len() -> int: ...
