# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.process`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/guest/process/process_py_bind.c
"""

from typing import Any

def active(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def current(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def info(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def poll(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
