"""pymergetic.metal.process — intent-root face over async tasks."""

FG: int
BG: int
DAEMON: int

def current() -> int: ...
def quit(pid: int = 0, code: int = 0) -> int: ...
def crown(handle: int, mode: int, tag: str = "") -> int: ...
def list() -> list: ...
def ps() -> list: ...
def shutting_down() -> bool: ...
