# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.random`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/dev/random/random_py_bind.c
"""

from typing import Any

def seed_u32(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
