"""Cold registry ledger + seat table."""

def ledger_seed_pilot() -> int: ...
def ledger_method_count() -> int: ...
def ledger_gap_count() -> int: ...
def ledger_json() -> str: ...
def ledger_module_json(module: str) -> str: ...
def ledger_method_json(module: str, func: str) -> str: ...

def seat_count() -> int: ...
def seat_at(index: int) -> tuple[str, int, bool, bool, bool]: ...
def seats_json() -> str: ...
def run_tests() -> int: ...
