# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.tls`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/dev/net/tls_py_bind.c
"""

from typing import Any

def close(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def connect(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def open(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def read(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def write(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
