def mode() -> int: ...
def mode_str() -> str: ...
def ready() -> bool: ...
def mods_pubkey_set(pk: bytes | bytearray | memoryview | None = None) -> bool: ...
def verify_mods(data: bytes | bytearray | memoryview, sig: bytes | bytearray | memoryview) -> bool: ...
def accept_mods(data: bytes | bytearray | memoryview, sig: bytes | bytearray | memoryview | None = None) -> bool: ...
def proof() -> bool: ...
