def ready() -> int: ...
def init() -> int: ...
def shutdown() -> None: ...
def load(full_module: str, bytes: bytes | bytearray | memoryview) -> int: ...
def image(full_module: str) -> bytes: ...
def register(full_module: str) -> int: ...
def load_register(full_module: str, bytes: bytes | bytearray | memoryview) -> int: ...
def load_verified(
    full_module: str, bytes: bytes | bytearray | memoryview, sig: bytes | bytearray | memoryview
) -> int: ...
def unload(full_module: str) -> int: ...
def call0(full_module: str, func: str) -> int: ...
def guest_coro_create_for(full_module: str, state_bytes: int) -> int: ...
def proof_stress() -> int: ...
def proof() -> int: ...
def fetch_register(
    full_module: str, url: str, sig: bytes | bytearray | memoryview | None
) -> int: ...
def proof_fetch() -> int: ...
