"""
``os`` — Metal's own module (mods/py/stdlib_src/os/__init__.py), not
CPython's. Bytes-only (see that file's own note: MICROPY_CPYTHON_COMPAT is
off, no str.encode()/bytes.decode() to build a text layer on top of), no
VFS/mount tree (flat single-root FS backed directly by pymergetic.metal.fs),
so this shadows typeshed's bundled "os" stub (which pyright otherwise
prefers over any same-named project file, real stdlib name or not) with the
much smaller surface this build actually implements.

Hand-authored, same reason as typings/uio.pyi and typings/deflate.pyi — keep
in sync by hand with mods/py/stdlib_src/os/__init__.py and os/path.py.
"""

from typing import Any

sep: str

def stat(path: str) -> tuple[int, int, int, int, int, int, int, int, int, int]: ...
def mkdir(path: str) -> None: ...
def remove(path: str) -> None: ...
def unlink(path: str) -> None: ...
def rename(old: str, new: str) -> None: ...
def listdir(path: str = ...) -> list[str]: ...
def ilistdir(path: str = ...) -> list[tuple[str, int, int]]: ...
def rmdir(path: str) -> None: ...
def getcwd() -> str: ...

path: Any
