# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pmcmd`` — every registered shell command as a real attribute.

Generated from PM_METAL_SHELL_CMD / PM_METAL_SHELL_CMDS call sites under
src/pymergetic/metal/**. Deliberately the one module that does NOT carry
the ``pymergetic.metal.*`` prefix — see docs/MICROPYTHON.md.

Mod-registered commands (pm_metal_mod_register_cmd, runtime-only — a mod's
on_load must actually run before they exist) are NOT covered by this static
scan; they still work at runtime via __getattr__ below, just without a
named stub.
"""

from typing import Any

def about(*args: Any) -> Any:
    """about [mod]       version, desc, url, authors (metal or a mod)"""
    ...

def audio(*args: Any) -> Any:
    """audio [status|mute|vol N]  backend / mute / volume 0-100"""
    ...

def bg(*args: Any) -> Any:
    """bg                resume job in background"""
    ...

def close(*args: Any) -> Any:
    """close [n]         close tab n, or active/last guest"""
    ...

def cpu(*args: Any) -> Any:
    """cpu               per-runner busy % + session pin"""
    ...

def date(*args: Any) -> Any:
    """date              local wall clock"""
    ...

def echo(*args: Any) -> Any:
    """echo <text>       print text"""
    ...

def exit(*args: Any) -> Any:
    """exit|quit [-r]    power off (or reboot with -r)"""
    ...

def externals(*args: Any) -> Any:
    """externals [id]    third-party stack ids + versions"""
    ...

def fg(*args: Any) -> Any:
    """fg                resume job in foreground"""
    ...

def help(*args: Any) -> Any:
    """this text"""
    ...

def history(*args: Any) -> Any:
    """history           list command history"""
    ...

def hostname(*args: Any) -> Any:
    """hostname [name]   get/set local nodename (not DNS)"""
    ...

def httpd(*args: Any) -> Any:
    """httpd autoload|listen [port]|close <srv>"""
    ...

def hwinfo(*args: Any) -> Any:
    """hwinfo            metal devices + PCI net/virtio"""
    ...

def jobs(*args: Any) -> Any:
    """jobs              list shell async job"""
    ...

def keyb(*args: Any) -> Any:
    """keyb [us|de]      PS/2 layout (default us; de QWERTZ, alias gr; Ctrl+Alt+Home cycles)"""
    ...

def mem(*args: Any) -> Any:
    """mem               system RAM + arena layout"""
    ...

def net(*args: Any) -> Any:
    """net [status [ethN]] | net set [ethN] <ip> <mask> <gw> [dns] | dhcp | dhcp6"""
    ...

def nslookup(*args: Any) -> Any:
    """nslookup <host>   resolve name (DNS / hosts)"""
    ...

def ping(*args: Any) -> Any:
    """ping <host>       ICMP echo (literal or DNS)"""
    ...

def presentoffload(*args: Any) -> Any:
    """presentoffload [on|off]  A/B: cross-runner present offload"""
    ...

def ps(*args: Any) -> Any:
    """ps                list fake processes"""
    ...

def ps2trace(*args: Any) -> Any:
    """ps2trace [on|off] Log raw i8042 keyboard bytes (debug real-HW scancode mismatches)"""
    ...

def py(*args: Any) -> Any:
    """py [-x] <script>|-c <code> | -f <mod.fn> [args] | -i"""
    ...

def quit(*args: Any) -> Any:
    """exit|quit [-r]    power off (or reboot with -r)"""
    ...

def run(*args: Any) -> Any:
    """run <mod>         fullscreen in console (guest HID)"""
    ...

def shutdown(*args: Any) -> Any:
    """exit|quit [-r]    power off (or reboot with -r)"""
    ...

def sshd(*args: Any) -> Any:
    """sshd autoload|listen [port]|close <srv>|status"""
    ...

def tab(*args: Any) -> Any:
    """tab <mod>         windowed in a new tab (guest HID)"""
    ...

def tabs(*args: Any) -> Any:
    """tabs              list tabs"""
    ...

def test(*args: Any) -> Any:
    """test              run bring-up proof suite"""
    ...

def tz(*args: Any) -> Any:
    """tz [+HHMM|name]   get/set timezone"""
    ...

def use(*args: Any) -> Any:
    """use <n>           activate tab index"""
    ...

def vol(*args: Any) -> Any:
    """vol [0-100]         alias for audio vol"""
    ...

def __getattr__(name: str) -> Any: ...
