"""
``uio`` — the forced-built-in-import alias for upstream MicroPython's native
``io`` module (external/micropython/py/modio.c). Every MP_REGISTER_EXTENSIBLE_MODULE
module gets this ``u``-prefixed alias for free (py/objmodule.c): once Metal's
own mods/py/stdlib_src/io.py occupies the bare "io" name, `import io` resolves
to that pure-Python file, and only `import uio` still reaches the native type.

Hand-authored (not scripts/gen_py_stubs.py output) for the same reason as
typings/deflate.pyi: a real upstream MicroPython builtin, not a
pymergetic.metal.* PM_METAL_PY_BIND call site, and CPython/typeshed have no
"uio" module. Members below are gated to match this port's mpconfigport.h
(MICROPY_PY_IO_IOBASE=1, MICROPY_PY_IO_BYTESIO=1, MICROPY_PY_IO_BUFFEREDWRITER=0)
— keep in sync by hand if those flags change.
"""

from typing import Any

def open(name: str, mode: str = ...) -> Any: ...

class IOBase:
    def readinto(self, buf: Any) -> int | None: ...
    def write(self, data: Any) -> int | None: ...
    def ioctl(self, request: int, arg: int) -> int: ...

class StringIO:
    def __init__(self, string: str = ...) -> None: ...
    def read(self, size: int = ...) -> str: ...
    def readline(self, size: int = ...) -> str: ...
    def write(self, data: str) -> int: ...
    def getvalue(self) -> str: ...
    def close(self) -> None: ...
    def __enter__(self) -> "StringIO": ...
    def __exit__(self, *exc_info: Any) -> None: ...

class BytesIO:
    def __init__(self, data: bytes = ...) -> None: ...
    def read(self, size: int = ...) -> bytes: ...
    def readinto(self, buf: Any) -> int: ...
    def readline(self, size: int = ...) -> bytes: ...
    def write(self, data: Any) -> int: ...
    def getvalue(self) -> bytes: ...
    def close(self) -> None: ...
    def __enter__(self) -> "BytesIO": ...
    def __exit__(self, *exc_info: Any) -> None: ...
