"""Typing face (matrix Py count = max(glue,.pyi))."""

def init(*args, **kwargs): ...
def ready(*args, **kwargs): ...
def switch(*args, **kwargs): ...
def active(*args, **kwargs): ...
def get(*args, **kwargs): ...
def bind_surface(*args, **kwargs): ...
def write(*args, **kwargs): ...
def puts(*args, **kwargs): ...
def render(*args, **kwargs): ...
