[package]
name = "pymergetic_metal_fs"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "../../src/pymergetic/metal/fs/__init__.rs"
crate-type = ["rlib"]

[dependencies]
pymergetic_metal_rt = { path = "../pymergetic_metal_rt" }
pymergetic_metal_async = { path = "../pymergetic_metal_async" }
pymergetic_metal_fs_vfs = { path = "../pymergetic_metal_fs_vfs" }
