/* generated by pymergetic.metal.jit.rs.compiler */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>

#line 3 "__impl__.rs"
uint8_t classify(uint8_t c)
;
#line 15 "__impl__.rs"
bool punct(const uint8_t * s)
;
#line 3 "__impl__.rs"
uint8_t classify(uint8_t c)
{
    uint8_t q = 'q';
    uint8_t nl = '\n';
    if ((c == q)) {
        return 1;
    } else         if ((c == nl)) {
            return 2;
        } else {
            return 0;
        }
}

#line 15 "__impl__.rs"
bool punct(const uint8_t * s)
{
    uint8_t c = (*s);
    return (((((c == '(') || (c == ')')) || (c == '[')) || (c == ']')) || (c == '{'));
}

