/* generated by pymergetic.metal.jit.rs.compiler */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>

#define KINDS 2
#line 18 "__impl__.rs"
typedef enum Kind Kind;
enum Kind {
    Kind_P,
    Kind_Q,
};

#line 26 "__impl__.rs"
typedef enum Other Other;
enum Other {
    Other_U,
    Other_V,
};


#line 4 "__impl__.rs"
int32_t chain(bool a, bool b, bool c)
;
#line 31 "__impl__.rs"
uint32_t discriminate(bool a, bool b, bool c)
;
#line 4 "__impl__.rs"
int32_t chain(bool a, bool b, bool c)
{
    if (a) {
        return 1;
    } else         if (b) {
            return 2;
        } else             if (c) {
                return 3;
            } else {
                return 4;
            }
}

#line 31 "__impl__.rs"
uint32_t discriminate(bool a, bool b, bool c)
{
    Kind kind = Kind_P;
    if ((chain(a, b, c) == 2)) {
        {
            kind = Kind_Q;
        }
    }
    if ((kind == Kind_Q)) {
        return KINDS;
    } else {
        return 0;
    }
}

