/* generated by pymergetic.metal.jit.rs.compiler */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>


#line 5 "__impl__.rs"
const uint8_t * pick(bool fixed)
;
#line 16 "__impl__.rs"
uint8_t at(size_t i)
;
#line 5 "__impl__.rs"
const uint8_t * pick(bool fixed)
{
    char * z;
    if (fixed) {
        z = "[;]\0";
    } else {
        z = "[]\0";
    }
    int32_t zl;
    if (fixed) {
        zl = 3;
    } else {
        zl = 2;
    }
zl;    return z;
}

#line 16 "__impl__.rs"
uint8_t at(size_t i)
{
    if ((i < 8)) {
        return 7;
    } else {
        return 0;
    }
}

