/* generated by pymergetic.metal.jit.rs.compiler */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>

#line 5 "__impl__.rs"
typedef struct Tab Tab;
struct Tab {
    bool used[8];
    size_t n;
};
typedef struct Tab Tab;


#line 11 "__impl__.rs"
size_t Tab_reg(Tab * self, size_t slot)
;
#line 20 "__impl__.rs"
size_t register_two(void)
;
#line 11 "__impl__.rs"
size_t Tab_reg(Tab * self, size_t slot)
{
    if ((slot < 8)) {
        {
            (((self)->used)[slot]) = true;
            ((self)->n) += 1;
        }
    }
    return slot;
}

#line 20 "__impl__.rs"
size_t register_two(void)
{
    Tab t = (Tab){ .used = {false,false,false,false,false,false,false,false}, .n = 0 };
Tab_reg(&(t), 1);Tab_reg(&(t), 2);    return ((t).n);
}

