/* generated by pymergetic.metal.jit.rs.compiler */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>

#line 6 "__impl__.rs"
typedef struct Kid Kid;
struct Kid {
    uint8_t * p;
    size_t n;
};
typedef struct Kid Kid;

#line 11 "__impl__.rs"
int32_t pack(Kid * * src, Kid * * dst, size_t count)
;
#line 19 "__impl__.rs"
uint8_t copy_bytes(const uint8_t * src, uint8_t * dst, size_t n)
;
#line 11 "__impl__.rs"
int32_t pack(Kid * * src, Kid * * dst, size_t count)
{
    memcpy(dst, src, (count) * sizeof(*src));
    return (int32_t)(count);
}

#line 19 "__impl__.rs"
uint8_t copy_bytes(const uint8_t * src, uint8_t * dst, size_t n)
{
    memcpy(dst, src, (n) * sizeof(*src));
    return (*dst);
}

