[package]
name = "pymergetic_metal_reg"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "../../src/pymergetic/metal/reg/__init__.rs"
crate-type = ["rlib"]

[dependencies]
pymergetic_metal_rt = { path = "../pymergetic_metal_rt" }
pymergetic_metal_async = { path = "../pymergetic_metal_async" }
