# pymergetic.metal.async — Python face (C N-runner impl in __init__.c)

def start(n_cpus: int) -> int: ...
def ready() -> int: ...
def n_runners() -> int: ...
def create_task(h: int = 0) -> int: ...
def run_poll() -> int: ...
def run_poll_all() -> int: ...
def run_loop() -> int: ...
def sleep_us(us: int) -> int: ...
def yield_() -> int: ...
def await_(self_h: int, child_h: int) -> int: ...
