def banner(version: str, cpu: str) -> None: ...
def emit(line: str) -> None: ...
def tree_ready_ok() -> None: ...
def tree_print() -> int: ...
def unboot() -> int: ...
def shutting_down() -> bool: ...
def shutdown() -> int: ...
def reboot() -> int: ...
def is_dead() -> bool: ...
