from collections.abc import Callable

def set_print(fn: Callable[[str], object] | None) -> None: ...
def emit(line: str) -> None: ...
def banner(version: str, cpu: str) -> None: ...
def reset() -> None: ...
def enter(name: str) -> None: ...
def enter_ex(name: str, st: int, detail: str | None = ...) -> None: ...
def item(name: str, st: int, detail: str | None = ...) -> None: ...
def leave() -> None: ...
def ready_ok() -> None: ...
def rainbow_metalpython(version: str, cpu: str) -> None: ...
def print() -> int: ...
