[package]
name = "pymergetic_metal"
version = "0.1.0"
edition = "2021"

[lib]
path = "../_impl/__init__.rs"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "smoke"
path = "smoke.rs"

[dependencies]
pymergetic_metal_reg = { path = "../reg/.pm" }

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
