//! grammar -- generated rule tables for the Metal parse-tree builder.
//!
//! GENERATED by `gen_grammar.py` from `external/micropython/py/grammar.h`.
//! Regenerate: `python3 src/pymergetic/metal/py/gen_grammar.py`.
//! Flags baked in: ASYNC_AWAIT/ASSIGN_EXPR/BUILTINS_SLICE/BUILTINS_SET on,
//! no f-strings/t-strings (see gen_grammar.py FLAGS + module comment).
//! Do not hand-edit -- edit the generator and rerun it instead.

use crate::upy::py::lexer::TokenKind;

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuleId {
    FileInput,
    FileInput2,
    Decorated,
    Funcdef,
    SimpleStmt2,
    ExprStmt,
    TestlistStarExpr,
    DelStmt,
    PassStmt,
    BreakStmt,
    ContinueStmt,
    ReturnStmt,
    YieldStmt,
    RaiseStmt,
    ImportName,
    ImportFrom,
    GlobalStmt,
    NonlocalStmt,
    AssertStmt,
    AsyncStmt,
    IfStmt,
    WhileStmt,
    ForStmt,
    TryStmt,
    WithStmt,
    SuiteBlockStmts,
    NamedexprTest,
    TestIfExpr,
    Lambdef,
    LambdefNocond,
    OrTest,
    AndTest,
    NotTest2,
    Comparison,
    StarExpr,
    Expr,
    XorExpr,
    AndExpr,
    ShiftExpr,
    ArithExpr,
    Term,
    Factor2,
    Power,
    AtomExprAwait,
    AtomExprNormal,
    AtomParen,
    AtomBracket,
    AtomBrace,
    TrailerParen,
    TrailerBracket,
    TrailerPeriod,
    Subscriptlist,
    Subscript2,
    Subscript3,
    Testlist,
    DictorsetmakerItem,
    Classdef,
    YieldExpr,
    ConstObject,
    GenericColonTest,
    GenericEqualTest,
    SingleInput,
    FileInput3,
    EvalInput,
    EvalInput2,
    Decorator,
    Decorators,
    DecoratedBody,
    AsyncFuncdef,
    Funcdefrettype,
    Typedargslist,
    TypedargslistItem,
    TypedargslistName,
    TypedargslistStar,
    TypedargslistDblStar,
    Tfpdef,
    Varargslist,
    VarargslistItem,
    VarargslistName,
    VarargslistStar,
    VarargslistDblStar,
    Vfpdef,
    Stmt,
    SimpleStmt,
    SmallStmt,
    ExprStmt2,
    ExprStmtAugassign,
    ExprStmtAssignList,
    ExprStmtAssign,
    ExprStmt6,
    TestlistStarExpr2,
    Annassign,
    Augassign,
    FlowStmt,
    RaiseStmtArg,
    RaiseStmtFrom,
    ImportStmt,
    ImportFrom2,
    ImportFrom2b,
    ImportFrom3,
    ImportAsNamesParen,
    OneOrMorePeriodOrEllipsis,
    PeriodOrEllipsis,
    ImportAsName,
    DottedAsName,
    AsName,
    ImportAsNames,
    DottedAsNames,
    DottedName,
    NameList,
    AssertStmtExtra,
    CompoundStmt,
    AsyncStmt2,
    IfStmtElifList,
    IfStmtElif,
    TryStmt2,
    TryStmtExceptAndMore,
    TryStmtExcept,
    TryStmtAsName,
    TryStmtExceptList,
    TryStmtFinally,
    ElseStmt,
    WithStmtList,
    WithItem,
    WithItemAs,
    Suite,
    SuiteBlock,
    NamedexprTest2,
    Test,
    TestIfElse,
    TestNocond,
    NotTest,
    CompOp,
    CompOpNotIn,
    CompOpIs,
    CompOpIsNot,
    ShiftOp,
    ArithOp,
    TermOp,
    Factor,
    FactorOp,
    AtomExpr,
    AtomExprTrailers,
    PowerDblStar,
    Atom,
    Atom2b,
    TestlistComp,
    TestlistComp2,
    TestlistComp3,
    TestlistComp3b,
    TestlistComp3c,
    Trailer,
    Subscript,
    Subscript3b,
    Subscript3c,
    Subscript3d,
    Sliceop,
    Exprlist,
    Exprlist2,
    Dictorsetmaker,
    DictorsetmakerTail,
    DictorsetmakerList,
    DictorsetmakerList2,
    Classdef2,
    Arglist,
    Arglist2,
    ArglistStar,
    ArglistDblStar,
    Argument,
    Argument2,
    Argument3,
    CompIter,
    CompFor,
    CompIf,
    YieldArg,
    YieldArgFrom,
}

pub const RULE_COUNT: usize = 176;

pub const RULE_ACT_ARG_MASK: u8 = 0x0f;
pub const RULE_ACT_KIND_MASK: u8 = 0x30;
pub const RULE_ACT_ALLOW_IDENT: u8 = 0x40;
pub const RULE_ACT_ADD_BLANK: u8 = 0x80;
pub const RULE_ACT_OR: u8 = 0x10;
pub const RULE_ACT_AND: u8 = 0x20;
pub const RULE_ACT_LIST: u8 = 0x30;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuleArg {
    Tok(TokenKind),
    Rule(RuleId),
    OptRule(RuleId),
}

pub static RULE_ACT_TABLE: [u8; RULE_COUNT] = [
    0x61, // file_input
    0x32, // file_input_2
    0x62, // decorated
    0xa8, // funcdef
    0x33, // simple_stmt_2
    0x22, // expr_stmt
    0x33, // testlist_star_expr
    0x22, // del_stmt
    0x21, // pass_stmt
    0x21, // break_stmt
    0x21, // continue_stmt
    0x22, // return_stmt
    0x21, // yield_stmt
    0x22, // raise_stmt
    0x22, // import_name
    0x24, // import_from
    0x22, // global_stmt
    0x22, // nonlocal_stmt
    0x23, // assert_stmt
    0x22, // async_stmt
    0x26, // if_stmt
    0x25, // while_stmt
    0x27, // for_stmt
    0x24, // try_stmt
    0x24, // with_stmt
    0x32, // suite_block_stmts
    0x62, // namedexpr_test
    0x62, // test_if_expr
    0xa4, // lambdef
    0xa4, // lambdef_nocond
    0x31, // or_test
    0x31, // and_test
    0x22, // not_test_2
    0x31, // comparison
    0x22, // star_expr
    0x31, // expr
    0x31, // xor_expr
    0x31, // and_expr
    0x31, // shift_expr
    0x31, // arith_expr
    0x31, // term
    0x62, // factor_2
    0x62, // power
    0x23, // atom_expr_await
    0x62, // atom_expr_normal
    0x23, // atom_paren
    0x23, // atom_bracket
    0x23, // atom_brace
    0x23, // trailer_paren
    0x23, // trailer_bracket
    0x22, // trailer_period
    0x33, // subscriptlist
    0x62, // subscript_2
    0x22, // subscript_3
    0x33, // testlist
    0x62, // dictorsetmaker_item
    0xa5, // classdef
    0x22, // yield_expr
    0, // RuleId::ConstObject (never dispatched directly)
    0x62, // generic_colon_test
    0x62, // generic_equal_test
    0x13, // single_input
    0x12, // file_input_3
    0x62, // eval_input
    0x21, // eval_input_2
    0x24, // decorator
    0x32, // decorators
    0x13, // decorated_body
    0x22, // async_funcdef
    0x62, // funcdefrettype
    0x33, // typedargslist
    0x13, // typedargslist_item
    0x63, // typedargslist_name
    0x22, // typedargslist_star
    0x23, // typedargslist_dbl_star
    0x22, // tfpdef
    0x33, // varargslist
    0x13, // varargslist_item
    0x62, // varargslist_name
    0x22, // varargslist_star
    0x22, // varargslist_dbl_star
    0x61, // vfpdef
    0x12, // stmt
    0x62, // simple_stmt
    0x18, // small_stmt
    0x13, // expr_stmt_2
    0x62, // expr_stmt_augassign
    0x32, // expr_stmt_assign_list
    0x62, // expr_stmt_assign
    0x12, // expr_stmt_6
    0x12, // testlist_star_expr_2
    0x23, // annassign
    0x1d, // augassign
    0x15, // flow_stmt
    0x62, // raise_stmt_arg
    0x62, // raise_stmt_from
    0x12, // import_stmt
    0x12, // import_from_2
    0x62, // import_from_2b
    0x13, // import_from_3
    0x63, // import_as_names_paren
    0x32, // one_or_more_period_or_ellipsis
    0x12, // period_or_ellipsis
    0x22, // import_as_name
    0x62, // dotted_as_name
    0x62, // as_name
    0x33, // import_as_names
    0x31, // dotted_as_names
    0x31, // dotted_name
    0x31, // name_list
    0x62, // assert_stmt_extra
    0x19, // compound_stmt
    0x13, // async_stmt_2
    0x32, // if_stmt_elif_list
    0x24, // if_stmt_elif
    0x12, // try_stmt_2
    0x63, // try_stmt_except_and_more
    0x24, // try_stmt_except
    0x62, // try_stmt_as_name
    0x32, // try_stmt_except_list
    0x23, // try_stmt_finally
    0x63, // else_stmt
    0x31, // with_stmt_list
    0x62, // with_item
    0x62, // with_item_as
    0x12, // suite
    0x64, // suite_block
    0x62, // namedexpr_test_2
    0x12, // test
    0x24, // test_if_else
    0x12, // test_nocond
    0x12, // not_test
    0x19, // comp_op
    0x22, // comp_op_not_in
    0x22, // comp_op_is
    0x21, // comp_op_is_not
    0x12, // shift_op
    0x12, // arith_op
    0x15, // term_op
    0x12, // factor
    0x13, // factor_op
    0x12, // atom_expr
    0x32, // atom_expr_trailers
    0x62, // power_dbl_star
    0x1c, // atom
    0x12, // atom_2b
    0x62, // testlist_comp
    0x12, // testlist_comp_2
    0x12, // testlist_comp_3
    0x62, // testlist_comp_3b
    0x33, // testlist_comp_3c
    0x13, // trailer
    0x12, // subscript
    0x12, // subscript_3b
    0x22, // subscript_3c
    0x62, // subscript_3d
    0x22, // sliceop
    0x33, // exprlist
    0x12, // exprlist_2
    0x62, // dictorsetmaker
    0x12, // dictorsetmaker_tail
    0x22, // dictorsetmaker_list
    0x33, // dictorsetmaker_list2
    0x63, // classdef_2
    0x33, // arglist
    0x13, // arglist_2
    0x22, // arglist_star
    0x22, // arglist_dbl_star
    0x62, // argument
    0x13, // argument_2
    0x22, // argument_3
    0x12, // comp_iter
    0xa5, // comp_for
    0x23, // comp_if
    0x12, // yield_arg
    0x22, // yield_arg_from
];

pub static RULE_ARGS: [&[RuleArg]; RULE_COUNT] = [
    &[RuleArg::OptRule(RuleId::FileInput2)], // file_input
    &[RuleArg::Rule(RuleId::FileInput3)], // file_input_2
    &[RuleArg::Rule(RuleId::Decorators), RuleArg::Rule(RuleId::DecoratedBody)], // decorated
    &[RuleArg::Tok(TokenKind::KwDef), RuleArg::Tok(TokenKind::Name), RuleArg::Tok(TokenKind::DelParenOpen), RuleArg::OptRule(RuleId::Typedargslist), RuleArg::Tok(TokenKind::DelParenClose), RuleArg::OptRule(RuleId::Funcdefrettype), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Suite)], // funcdef
    &[RuleArg::Rule(RuleId::SmallStmt), RuleArg::Tok(TokenKind::DelSemicolon)], // simple_stmt_2
    &[RuleArg::Rule(RuleId::TestlistStarExpr), RuleArg::OptRule(RuleId::ExprStmt2)], // expr_stmt
    &[RuleArg::Rule(RuleId::TestlistStarExpr2), RuleArg::Tok(TokenKind::DelComma)], // testlist_star_expr
    &[RuleArg::Tok(TokenKind::KwDel), RuleArg::Rule(RuleId::Exprlist)], // del_stmt
    &[RuleArg::Tok(TokenKind::KwPass)], // pass_stmt
    &[RuleArg::Tok(TokenKind::KwBreak)], // break_stmt
    &[RuleArg::Tok(TokenKind::KwContinue)], // continue_stmt
    &[RuleArg::Tok(TokenKind::KwReturn), RuleArg::OptRule(RuleId::Testlist)], // return_stmt
    &[RuleArg::Rule(RuleId::YieldExpr)], // yield_stmt
    &[RuleArg::Tok(TokenKind::KwRaise), RuleArg::OptRule(RuleId::RaiseStmtArg)], // raise_stmt
    &[RuleArg::Tok(TokenKind::KwImport), RuleArg::Rule(RuleId::DottedAsNames)], // import_name
    &[RuleArg::Tok(TokenKind::KwFrom), RuleArg::Rule(RuleId::ImportFrom2), RuleArg::Tok(TokenKind::KwImport), RuleArg::Rule(RuleId::ImportFrom3)], // import_from
    &[RuleArg::Tok(TokenKind::KwGlobal), RuleArg::Rule(RuleId::NameList)], // global_stmt
    &[RuleArg::Tok(TokenKind::KwNonlocal), RuleArg::Rule(RuleId::NameList)], // nonlocal_stmt
    &[RuleArg::Tok(TokenKind::KwAssert), RuleArg::Rule(RuleId::Test), RuleArg::OptRule(RuleId::AssertStmtExtra)], // assert_stmt
    &[RuleArg::Tok(TokenKind::KwAsync), RuleArg::Rule(RuleId::AsyncStmt2)], // async_stmt
    &[RuleArg::Tok(TokenKind::KwIf), RuleArg::Rule(RuleId::NamedexprTest), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Suite), RuleArg::OptRule(RuleId::IfStmtElifList), RuleArg::OptRule(RuleId::ElseStmt)], // if_stmt
    &[RuleArg::Tok(TokenKind::KwWhile), RuleArg::Rule(RuleId::NamedexprTest), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Suite), RuleArg::OptRule(RuleId::ElseStmt)], // while_stmt
    &[RuleArg::Tok(TokenKind::KwFor), RuleArg::Rule(RuleId::Exprlist), RuleArg::Tok(TokenKind::KwIn), RuleArg::Rule(RuleId::Testlist), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Suite), RuleArg::OptRule(RuleId::ElseStmt)], // for_stmt
    &[RuleArg::Tok(TokenKind::KwTry), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Suite), RuleArg::Rule(RuleId::TryStmt2)], // try_stmt
    &[RuleArg::Tok(TokenKind::KwWith), RuleArg::Rule(RuleId::WithStmtList), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Suite)], // with_stmt
    &[RuleArg::Rule(RuleId::Stmt)], // suite_block_stmts
    &[RuleArg::Rule(RuleId::Test), RuleArg::OptRule(RuleId::NamedexprTest2)], // namedexpr_test
    &[RuleArg::Rule(RuleId::OrTest), RuleArg::OptRule(RuleId::TestIfElse)], // test_if_expr
    &[RuleArg::Tok(TokenKind::KwLambda), RuleArg::OptRule(RuleId::Varargslist), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Test)], // lambdef
    &[RuleArg::Tok(TokenKind::KwLambda), RuleArg::OptRule(RuleId::Varargslist), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::TestNocond)], // lambdef_nocond
    &[RuleArg::Rule(RuleId::AndTest), RuleArg::Tok(TokenKind::KwOr)], // or_test
    &[RuleArg::Rule(RuleId::NotTest), RuleArg::Tok(TokenKind::KwAnd)], // and_test
    &[RuleArg::Tok(TokenKind::KwNot), RuleArg::Rule(RuleId::NotTest)], // not_test_2
    &[RuleArg::Rule(RuleId::Expr), RuleArg::Rule(RuleId::CompOp)], // comparison
    &[RuleArg::Tok(TokenKind::OpStar), RuleArg::Rule(RuleId::Expr)], // star_expr
    &[RuleArg::Rule(RuleId::XorExpr), RuleArg::Tok(TokenKind::OpPipe)], // expr
    &[RuleArg::Rule(RuleId::AndExpr), RuleArg::Tok(TokenKind::OpCaret)], // xor_expr
    &[RuleArg::Rule(RuleId::ShiftExpr), RuleArg::Tok(TokenKind::OpAmpersand)], // and_expr
    &[RuleArg::Rule(RuleId::ArithExpr), RuleArg::Rule(RuleId::ShiftOp)], // shift_expr
    &[RuleArg::Rule(RuleId::Term), RuleArg::Rule(RuleId::ArithOp)], // arith_expr
    &[RuleArg::Rule(RuleId::Factor), RuleArg::Rule(RuleId::TermOp)], // term
    &[RuleArg::Rule(RuleId::FactorOp), RuleArg::Rule(RuleId::Factor)], // factor_2
    &[RuleArg::Rule(RuleId::AtomExpr), RuleArg::OptRule(RuleId::PowerDblStar)], // power
    &[RuleArg::Tok(TokenKind::KwAwait), RuleArg::Rule(RuleId::Atom), RuleArg::OptRule(RuleId::AtomExprTrailers)], // atom_expr_await
    &[RuleArg::Rule(RuleId::Atom), RuleArg::OptRule(RuleId::AtomExprTrailers)], // atom_expr_normal
    &[RuleArg::Tok(TokenKind::DelParenOpen), RuleArg::OptRule(RuleId::Atom2b), RuleArg::Tok(TokenKind::DelParenClose)], // atom_paren
    &[RuleArg::Tok(TokenKind::DelBracketOpen), RuleArg::OptRule(RuleId::TestlistComp), RuleArg::Tok(TokenKind::DelBracketClose)], // atom_bracket
    &[RuleArg::Tok(TokenKind::DelBraceOpen), RuleArg::OptRule(RuleId::Dictorsetmaker), RuleArg::Tok(TokenKind::DelBraceClose)], // atom_brace
    &[RuleArg::Tok(TokenKind::DelParenOpen), RuleArg::OptRule(RuleId::Arglist), RuleArg::Tok(TokenKind::DelParenClose)], // trailer_paren
    &[RuleArg::Tok(TokenKind::DelBracketOpen), RuleArg::Rule(RuleId::Subscriptlist), RuleArg::Tok(TokenKind::DelBracketClose)], // trailer_bracket
    &[RuleArg::Tok(TokenKind::DelPeriod), RuleArg::Tok(TokenKind::Name)], // trailer_period
    &[RuleArg::Rule(RuleId::Subscript), RuleArg::Tok(TokenKind::DelComma)], // subscriptlist
    &[RuleArg::Rule(RuleId::Test), RuleArg::OptRule(RuleId::Subscript3)], // subscript_2
    &[RuleArg::Tok(TokenKind::DelColon), RuleArg::OptRule(RuleId::Subscript3b)], // subscript_3
    &[RuleArg::Rule(RuleId::Test), RuleArg::Tok(TokenKind::DelComma)], // testlist
    &[RuleArg::Rule(RuleId::Test), RuleArg::OptRule(RuleId::GenericColonTest)], // dictorsetmaker_item
    &[RuleArg::Tok(TokenKind::KwClass), RuleArg::Tok(TokenKind::Name), RuleArg::OptRule(RuleId::Classdef2), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Suite)], // classdef
    &[RuleArg::Tok(TokenKind::KwYield), RuleArg::OptRule(RuleId::YieldArg)], // yield_expr
    &[], // RuleId::ConstObject
    &[RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Test)], // generic_colon_test
    &[RuleArg::Tok(TokenKind::DelEqual), RuleArg::Rule(RuleId::Test)], // generic_equal_test
    &[RuleArg::Tok(TokenKind::Newline), RuleArg::Rule(RuleId::SimpleStmt), RuleArg::Rule(RuleId::CompoundStmt)], // single_input
    &[RuleArg::Tok(TokenKind::Newline), RuleArg::Rule(RuleId::Stmt)], // file_input_3
    &[RuleArg::Rule(RuleId::Testlist), RuleArg::OptRule(RuleId::EvalInput2)], // eval_input
    &[RuleArg::Tok(TokenKind::Newline)], // eval_input_2
    &[RuleArg::Tok(TokenKind::OpAt), RuleArg::Rule(RuleId::DottedName), RuleArg::OptRule(RuleId::TrailerParen), RuleArg::Tok(TokenKind::Newline)], // decorator
    &[RuleArg::Rule(RuleId::Decorator)], // decorators
    &[RuleArg::Rule(RuleId::Classdef), RuleArg::Rule(RuleId::Funcdef), RuleArg::Rule(RuleId::AsyncFuncdef)], // decorated_body
    &[RuleArg::Tok(TokenKind::KwAsync), RuleArg::Rule(RuleId::Funcdef)], // async_funcdef
    &[RuleArg::Tok(TokenKind::DelMinusMore), RuleArg::Rule(RuleId::Test)], // funcdefrettype
    &[RuleArg::Rule(RuleId::TypedargslistItem), RuleArg::Tok(TokenKind::DelComma)], // typedargslist
    &[RuleArg::Rule(RuleId::TypedargslistName), RuleArg::Rule(RuleId::TypedargslistStar), RuleArg::Rule(RuleId::TypedargslistDblStar)], // typedargslist_item
    &[RuleArg::Tok(TokenKind::Name), RuleArg::OptRule(RuleId::GenericColonTest), RuleArg::OptRule(RuleId::GenericEqualTest)], // typedargslist_name
    &[RuleArg::Tok(TokenKind::OpStar), RuleArg::OptRule(RuleId::Tfpdef)], // typedargslist_star
    &[RuleArg::Tok(TokenKind::OpDblStar), RuleArg::Tok(TokenKind::Name), RuleArg::OptRule(RuleId::GenericColonTest)], // typedargslist_dbl_star
    &[RuleArg::Tok(TokenKind::Name), RuleArg::OptRule(RuleId::GenericColonTest)], // tfpdef
    &[RuleArg::Rule(RuleId::VarargslistItem), RuleArg::Tok(TokenKind::DelComma)], // varargslist
    &[RuleArg::Rule(RuleId::VarargslistName), RuleArg::Rule(RuleId::VarargslistStar), RuleArg::Rule(RuleId::VarargslistDblStar)], // varargslist_item
    &[RuleArg::Tok(TokenKind::Name), RuleArg::OptRule(RuleId::GenericEqualTest)], // varargslist_name
    &[RuleArg::Tok(TokenKind::OpStar), RuleArg::OptRule(RuleId::Vfpdef)], // varargslist_star
    &[RuleArg::Tok(TokenKind::OpDblStar), RuleArg::Tok(TokenKind::Name)], // varargslist_dbl_star
    &[RuleArg::Tok(TokenKind::Name)], // vfpdef
    &[RuleArg::Rule(RuleId::CompoundStmt), RuleArg::Rule(RuleId::SimpleStmt)], // stmt
    &[RuleArg::Rule(RuleId::SimpleStmt2), RuleArg::Tok(TokenKind::Newline)], // simple_stmt
    &[RuleArg::Rule(RuleId::DelStmt), RuleArg::Rule(RuleId::PassStmt), RuleArg::Rule(RuleId::FlowStmt), RuleArg::Rule(RuleId::ImportStmt), RuleArg::Rule(RuleId::GlobalStmt), RuleArg::Rule(RuleId::NonlocalStmt), RuleArg::Rule(RuleId::AssertStmt), RuleArg::Rule(RuleId::ExprStmt)], // small_stmt
    &[RuleArg::Rule(RuleId::Annassign), RuleArg::Rule(RuleId::ExprStmtAugassign), RuleArg::Rule(RuleId::ExprStmtAssignList)], // expr_stmt_2
    &[RuleArg::Rule(RuleId::Augassign), RuleArg::Rule(RuleId::ExprStmt6)], // expr_stmt_augassign
    &[RuleArg::Rule(RuleId::ExprStmtAssign)], // expr_stmt_assign_list
    &[RuleArg::Tok(TokenKind::DelEqual), RuleArg::Rule(RuleId::ExprStmt6)], // expr_stmt_assign
    &[RuleArg::Rule(RuleId::YieldExpr), RuleArg::Rule(RuleId::TestlistStarExpr)], // expr_stmt_6
    &[RuleArg::Rule(RuleId::StarExpr), RuleArg::Rule(RuleId::Test)], // testlist_star_expr_2
    &[RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Test), RuleArg::OptRule(RuleId::ExprStmtAssign)], // annassign
    &[RuleArg::Tok(TokenKind::DelPlusEqual), RuleArg::Tok(TokenKind::DelMinusEqual), RuleArg::Tok(TokenKind::DelStarEqual), RuleArg::Tok(TokenKind::DelAtEqual), RuleArg::Tok(TokenKind::DelSlashEqual), RuleArg::Tok(TokenKind::DelPercentEqual), RuleArg::Tok(TokenKind::DelAmpersandEqual), RuleArg::Tok(TokenKind::DelPipeEqual), RuleArg::Tok(TokenKind::DelCaretEqual), RuleArg::Tok(TokenKind::DelDblLessEqual), RuleArg::Tok(TokenKind::DelDblMoreEqual), RuleArg::Tok(TokenKind::DelDblStarEqual), RuleArg::Tok(TokenKind::DelDblSlashEqual)], // augassign
    &[RuleArg::Rule(RuleId::BreakStmt), RuleArg::Rule(RuleId::ContinueStmt), RuleArg::Rule(RuleId::ReturnStmt), RuleArg::Rule(RuleId::RaiseStmt), RuleArg::Rule(RuleId::YieldStmt)], // flow_stmt
    &[RuleArg::Rule(RuleId::Test), RuleArg::OptRule(RuleId::RaiseStmtFrom)], // raise_stmt_arg
    &[RuleArg::Tok(TokenKind::KwFrom), RuleArg::Rule(RuleId::Test)], // raise_stmt_from
    &[RuleArg::Rule(RuleId::ImportName), RuleArg::Rule(RuleId::ImportFrom)], // import_stmt
    &[RuleArg::Rule(RuleId::DottedName), RuleArg::Rule(RuleId::ImportFrom2b)], // import_from_2
    &[RuleArg::Rule(RuleId::OneOrMorePeriodOrEllipsis), RuleArg::OptRule(RuleId::DottedName)], // import_from_2b
    &[RuleArg::Tok(TokenKind::OpStar), RuleArg::Rule(RuleId::ImportAsNamesParen), RuleArg::Rule(RuleId::ImportAsNames)], // import_from_3
    &[RuleArg::Tok(TokenKind::DelParenOpen), RuleArg::Rule(RuleId::ImportAsNames), RuleArg::Tok(TokenKind::DelParenClose)], // import_as_names_paren
    &[RuleArg::Rule(RuleId::PeriodOrEllipsis)], // one_or_more_period_or_ellipsis
    &[RuleArg::Tok(TokenKind::DelPeriod), RuleArg::Tok(TokenKind::Ellipsis)], // period_or_ellipsis
    &[RuleArg::Tok(TokenKind::Name), RuleArg::OptRule(RuleId::AsName)], // import_as_name
    &[RuleArg::Rule(RuleId::DottedName), RuleArg::OptRule(RuleId::AsName)], // dotted_as_name
    &[RuleArg::Tok(TokenKind::KwAs), RuleArg::Tok(TokenKind::Name)], // as_name
    &[RuleArg::Rule(RuleId::ImportAsName), RuleArg::Tok(TokenKind::DelComma)], // import_as_names
    &[RuleArg::Rule(RuleId::DottedAsName), RuleArg::Tok(TokenKind::DelComma)], // dotted_as_names
    &[RuleArg::Tok(TokenKind::Name), RuleArg::Tok(TokenKind::DelPeriod)], // dotted_name
    &[RuleArg::Tok(TokenKind::Name), RuleArg::Tok(TokenKind::DelComma)], // name_list
    &[RuleArg::Tok(TokenKind::DelComma), RuleArg::Rule(RuleId::Test)], // assert_stmt_extra
    &[RuleArg::Rule(RuleId::IfStmt), RuleArg::Rule(RuleId::WhileStmt), RuleArg::Rule(RuleId::ForStmt), RuleArg::Rule(RuleId::TryStmt), RuleArg::Rule(RuleId::WithStmt), RuleArg::Rule(RuleId::Funcdef), RuleArg::Rule(RuleId::Classdef), RuleArg::Rule(RuleId::Decorated), RuleArg::Rule(RuleId::AsyncStmt)], // compound_stmt
    &[RuleArg::Rule(RuleId::Funcdef), RuleArg::Rule(RuleId::WithStmt), RuleArg::Rule(RuleId::ForStmt)], // async_stmt_2
    &[RuleArg::Rule(RuleId::IfStmtElif)], // if_stmt_elif_list
    &[RuleArg::Tok(TokenKind::KwElif), RuleArg::Rule(RuleId::NamedexprTest), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Suite)], // if_stmt_elif
    &[RuleArg::Rule(RuleId::TryStmtExceptAndMore), RuleArg::Rule(RuleId::TryStmtFinally)], // try_stmt_2
    &[RuleArg::Rule(RuleId::TryStmtExceptList), RuleArg::OptRule(RuleId::ElseStmt), RuleArg::OptRule(RuleId::TryStmtFinally)], // try_stmt_except_and_more
    &[RuleArg::Tok(TokenKind::KwExcept), RuleArg::OptRule(RuleId::TryStmtAsName), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Suite)], // try_stmt_except
    &[RuleArg::Rule(RuleId::Test), RuleArg::OptRule(RuleId::AsName)], // try_stmt_as_name
    &[RuleArg::Rule(RuleId::TryStmtExcept)], // try_stmt_except_list
    &[RuleArg::Tok(TokenKind::KwFinally), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Suite)], // try_stmt_finally
    &[RuleArg::Tok(TokenKind::KwElse), RuleArg::Tok(TokenKind::DelColon), RuleArg::Rule(RuleId::Suite)], // else_stmt
    &[RuleArg::Rule(RuleId::WithItem), RuleArg::Tok(TokenKind::DelComma)], // with_stmt_list
    &[RuleArg::Rule(RuleId::Test), RuleArg::OptRule(RuleId::WithItemAs)], // with_item
    &[RuleArg::Tok(TokenKind::KwAs), RuleArg::Rule(RuleId::Expr)], // with_item_as
    &[RuleArg::Rule(RuleId::SuiteBlock), RuleArg::Rule(RuleId::SimpleStmt)], // suite
    &[RuleArg::Tok(TokenKind::Newline), RuleArg::Tok(TokenKind::Indent), RuleArg::Rule(RuleId::SuiteBlockStmts), RuleArg::Tok(TokenKind::Dedent)], // suite_block
    &[RuleArg::Tok(TokenKind::OpAssign), RuleArg::Rule(RuleId::Test)], // namedexpr_test_2
    &[RuleArg::Rule(RuleId::Lambdef), RuleArg::Rule(RuleId::TestIfExpr)], // test
    &[RuleArg::Tok(TokenKind::KwIf), RuleArg::Rule(RuleId::OrTest), RuleArg::Tok(TokenKind::KwElse), RuleArg::Rule(RuleId::Test)], // test_if_else
    &[RuleArg::Rule(RuleId::LambdefNocond), RuleArg::Rule(RuleId::OrTest)], // test_nocond
    &[RuleArg::Rule(RuleId::NotTest2), RuleArg::Rule(RuleId::Comparison)], // not_test
    &[RuleArg::Tok(TokenKind::OpLess), RuleArg::Tok(TokenKind::OpMore), RuleArg::Tok(TokenKind::OpDblEqual), RuleArg::Tok(TokenKind::OpLessEqual), RuleArg::Tok(TokenKind::OpMoreEqual), RuleArg::Tok(TokenKind::OpNotEqual), RuleArg::Tok(TokenKind::KwIn), RuleArg::Rule(RuleId::CompOpNotIn), RuleArg::Rule(RuleId::CompOpIs)], // comp_op
    &[RuleArg::Tok(TokenKind::KwNot), RuleArg::Tok(TokenKind::KwIn)], // comp_op_not_in
    &[RuleArg::Tok(TokenKind::KwIs), RuleArg::OptRule(RuleId::CompOpIsNot)], // comp_op_is
    &[RuleArg::Tok(TokenKind::KwNot)], // comp_op_is_not
    &[RuleArg::Tok(TokenKind::OpDblLess), RuleArg::Tok(TokenKind::OpDblMore)], // shift_op
    &[RuleArg::Tok(TokenKind::OpPlus), RuleArg::Tok(TokenKind::OpMinus)], // arith_op
    &[RuleArg::Tok(TokenKind::OpStar), RuleArg::Tok(TokenKind::OpAt), RuleArg::Tok(TokenKind::OpSlash), RuleArg::Tok(TokenKind::OpPercent), RuleArg::Tok(TokenKind::OpDblSlash)], // term_op
    &[RuleArg::Rule(RuleId::Factor2), RuleArg::Rule(RuleId::Power)], // factor
    &[RuleArg::Tok(TokenKind::OpPlus), RuleArg::Tok(TokenKind::OpMinus), RuleArg::Tok(TokenKind::OpTilde)], // factor_op
    &[RuleArg::Rule(RuleId::AtomExprAwait), RuleArg::Rule(RuleId::AtomExprNormal)], // atom_expr
    &[RuleArg::Rule(RuleId::Trailer)], // atom_expr_trailers
    &[RuleArg::Tok(TokenKind::OpDblStar), RuleArg::Rule(RuleId::Factor)], // power_dbl_star
    &[RuleArg::Tok(TokenKind::Name), RuleArg::Tok(TokenKind::Integer), RuleArg::Tok(TokenKind::FloatOrImag), RuleArg::Tok(TokenKind::String), RuleArg::Tok(TokenKind::Bytes), RuleArg::Tok(TokenKind::Ellipsis), RuleArg::Tok(TokenKind::KwNone), RuleArg::Tok(TokenKind::KwTrue), RuleArg::Tok(TokenKind::KwFalse), RuleArg::Rule(RuleId::AtomParen), RuleArg::Rule(RuleId::AtomBracket), RuleArg::Rule(RuleId::AtomBrace)], // atom
    &[RuleArg::Rule(RuleId::YieldExpr), RuleArg::Rule(RuleId::TestlistComp)], // atom_2b
    &[RuleArg::Rule(RuleId::TestlistComp2), RuleArg::OptRule(RuleId::TestlistComp3)], // testlist_comp
    &[RuleArg::Rule(RuleId::StarExpr), RuleArg::Rule(RuleId::NamedexprTest)], // testlist_comp_2
    &[RuleArg::Rule(RuleId::CompFor), RuleArg::Rule(RuleId::TestlistComp3b)], // testlist_comp_3
    &[RuleArg::Tok(TokenKind::DelComma), RuleArg::OptRule(RuleId::TestlistComp3c)], // testlist_comp_3b
    &[RuleArg::Rule(RuleId::TestlistComp2), RuleArg::Tok(TokenKind::DelComma)], // testlist_comp_3c
    &[RuleArg::Rule(RuleId::TrailerParen), RuleArg::Rule(RuleId::TrailerBracket), RuleArg::Rule(RuleId::TrailerPeriod)], // trailer
    &[RuleArg::Rule(RuleId::Subscript3), RuleArg::Rule(RuleId::Subscript2)], // subscript
    &[RuleArg::Rule(RuleId::Subscript3c), RuleArg::Rule(RuleId::Subscript3d)], // subscript_3b
    &[RuleArg::Tok(TokenKind::DelColon), RuleArg::OptRule(RuleId::Test)], // subscript_3c
    &[RuleArg::Rule(RuleId::Test), RuleArg::OptRule(RuleId::Sliceop)], // subscript_3d
    &[RuleArg::Tok(TokenKind::DelColon), RuleArg::OptRule(RuleId::Test)], // sliceop
    &[RuleArg::Rule(RuleId::Exprlist2), RuleArg::Tok(TokenKind::DelComma)], // exprlist
    &[RuleArg::Rule(RuleId::StarExpr), RuleArg::Rule(RuleId::Expr)], // exprlist_2
    &[RuleArg::Rule(RuleId::DictorsetmakerItem), RuleArg::OptRule(RuleId::DictorsetmakerTail)], // dictorsetmaker
    &[RuleArg::Rule(RuleId::CompFor), RuleArg::Rule(RuleId::DictorsetmakerList)], // dictorsetmaker_tail
    &[RuleArg::Tok(TokenKind::DelComma), RuleArg::OptRule(RuleId::DictorsetmakerList2)], // dictorsetmaker_list
    &[RuleArg::Rule(RuleId::DictorsetmakerItem), RuleArg::Tok(TokenKind::DelComma)], // dictorsetmaker_list2
    &[RuleArg::Tok(TokenKind::DelParenOpen), RuleArg::OptRule(RuleId::Arglist), RuleArg::Tok(TokenKind::DelParenClose)], // classdef_2
    &[RuleArg::Rule(RuleId::Arglist2), RuleArg::Tok(TokenKind::DelComma)], // arglist
    &[RuleArg::Rule(RuleId::ArglistStar), RuleArg::Rule(RuleId::ArglistDblStar), RuleArg::Rule(RuleId::Argument)], // arglist_2
    &[RuleArg::Tok(TokenKind::OpStar), RuleArg::Rule(RuleId::Test)], // arglist_star
    &[RuleArg::Tok(TokenKind::OpDblStar), RuleArg::Rule(RuleId::Test)], // arglist_dbl_star
    &[RuleArg::Rule(RuleId::Test), RuleArg::OptRule(RuleId::Argument2)], // argument
    &[RuleArg::Rule(RuleId::CompFor), RuleArg::Rule(RuleId::GenericEqualTest), RuleArg::Rule(RuleId::Argument3)], // argument_2
    &[RuleArg::Tok(TokenKind::OpAssign), RuleArg::Rule(RuleId::Test)], // argument_3
    &[RuleArg::Rule(RuleId::CompFor), RuleArg::Rule(RuleId::CompIf)], // comp_iter
    &[RuleArg::Tok(TokenKind::KwFor), RuleArg::Rule(RuleId::Exprlist), RuleArg::Tok(TokenKind::KwIn), RuleArg::Rule(RuleId::OrTest), RuleArg::OptRule(RuleId::CompIter)], // comp_for
    &[RuleArg::Tok(TokenKind::KwIf), RuleArg::Rule(RuleId::TestNocond), RuleArg::OptRule(RuleId::CompIter)], // comp_if
    &[RuleArg::Rule(RuleId::YieldArgFrom), RuleArg::Rule(RuleId::Testlist)], // yield_arg
    &[RuleArg::Tok(TokenKind::KwFrom), RuleArg::Rule(RuleId::Test)], // yield_arg_from
];

/// Debug-only rule names (upstream `rule_name_table`, always on here --
/// small and const, useful for `ParseError` messages).
pub static RULE_NAMES: [&str; RULE_COUNT] = [
    "file_input",
    "file_input_2",
    "decorated",
    "funcdef",
    "simple_stmt_2",
    "expr_stmt",
    "testlist_star_expr",
    "del_stmt",
    "pass_stmt",
    "break_stmt",
    "continue_stmt",
    "return_stmt",
    "yield_stmt",
    "raise_stmt",
    "import_name",
    "import_from",
    "global_stmt",
    "nonlocal_stmt",
    "assert_stmt",
    "async_stmt",
    "if_stmt",
    "while_stmt",
    "for_stmt",
    "try_stmt",
    "with_stmt",
    "suite_block_stmts",
    "namedexpr_test",
    "test_if_expr",
    "lambdef",
    "lambdef_nocond",
    "or_test",
    "and_test",
    "not_test_2",
    "comparison",
    "star_expr",
    "expr",
    "xor_expr",
    "and_expr",
    "shift_expr",
    "arith_expr",
    "term",
    "factor_2",
    "power",
    "atom_expr_await",
    "atom_expr_normal",
    "atom_paren",
    "atom_bracket",
    "atom_brace",
    "trailer_paren",
    "trailer_bracket",
    "trailer_period",
    "subscriptlist",
    "subscript_2",
    "subscript_3",
    "testlist",
    "dictorsetmaker_item",
    "classdef",
    "yield_expr",
    "const_object",
    "generic_colon_test",
    "generic_equal_test",
    "single_input",
    "file_input_3",
    "eval_input",
    "eval_input_2",
    "decorator",
    "decorators",
    "decorated_body",
    "async_funcdef",
    "funcdefrettype",
    "typedargslist",
    "typedargslist_item",
    "typedargslist_name",
    "typedargslist_star",
    "typedargslist_dbl_star",
    "tfpdef",
    "varargslist",
    "varargslist_item",
    "varargslist_name",
    "varargslist_star",
    "varargslist_dbl_star",
    "vfpdef",
    "stmt",
    "simple_stmt",
    "small_stmt",
    "expr_stmt_2",
    "expr_stmt_augassign",
    "expr_stmt_assign_list",
    "expr_stmt_assign",
    "expr_stmt_6",
    "testlist_star_expr_2",
    "annassign",
    "augassign",
    "flow_stmt",
    "raise_stmt_arg",
    "raise_stmt_from",
    "import_stmt",
    "import_from_2",
    "import_from_2b",
    "import_from_3",
    "import_as_names_paren",
    "one_or_more_period_or_ellipsis",
    "period_or_ellipsis",
    "import_as_name",
    "dotted_as_name",
    "as_name",
    "import_as_names",
    "dotted_as_names",
    "dotted_name",
    "name_list",
    "assert_stmt_extra",
    "compound_stmt",
    "async_stmt_2",
    "if_stmt_elif_list",
    "if_stmt_elif",
    "try_stmt_2",
    "try_stmt_except_and_more",
    "try_stmt_except",
    "try_stmt_as_name",
    "try_stmt_except_list",
    "try_stmt_finally",
    "else_stmt",
    "with_stmt_list",
    "with_item",
    "with_item_as",
    "suite",
    "suite_block",
    "namedexpr_test_2",
    "test",
    "test_if_else",
    "test_nocond",
    "not_test",
    "comp_op",
    "comp_op_not_in",
    "comp_op_is",
    "comp_op_is_not",
    "shift_op",
    "arith_op",
    "term_op",
    "factor",
    "factor_op",
    "atom_expr",
    "atom_expr_trailers",
    "power_dbl_star",
    "atom",
    "atom_2b",
    "testlist_comp",
    "testlist_comp_2",
    "testlist_comp_3",
    "testlist_comp_3b",
    "testlist_comp_3c",
    "trailer",
    "subscript",
    "subscript_3b",
    "subscript_3c",
    "subscript_3d",
    "sliceop",
    "exprlist",
    "exprlist_2",
    "dictorsetmaker",
    "dictorsetmaker_tail",
    "dictorsetmaker_list",
    "dictorsetmaker_list2",
    "classdef_2",
    "arglist",
    "arglist_2",
    "arglist_star",
    "arglist_dbl_star",
    "argument",
    "argument_2",
    "argument_3",
    "comp_iter",
    "comp_for",
    "comp_if",
    "yield_arg",
    "yield_arg_from",
];

/// Safe decode of a rule-id byte stored in a struct-node header (the
/// alternative to an `unsafe transmute::<u8, RuleId>` -- every byte parse.rs
/// stores there came from `as u8` on a real `RuleId`, so this is only ever
/// hit with an in-range value; `unreachable!()` documents that invariant
/// instead of asserting it away with `unsafe`.
pub fn rule_id_from_u8(v: u8) -> RuleId {
    match v {
        0 => RuleId::FileInput,
        1 => RuleId::FileInput2,
        2 => RuleId::Decorated,
        3 => RuleId::Funcdef,
        4 => RuleId::SimpleStmt2,
        5 => RuleId::ExprStmt,
        6 => RuleId::TestlistStarExpr,
        7 => RuleId::DelStmt,
        8 => RuleId::PassStmt,
        9 => RuleId::BreakStmt,
        10 => RuleId::ContinueStmt,
        11 => RuleId::ReturnStmt,
        12 => RuleId::YieldStmt,
        13 => RuleId::RaiseStmt,
        14 => RuleId::ImportName,
        15 => RuleId::ImportFrom,
        16 => RuleId::GlobalStmt,
        17 => RuleId::NonlocalStmt,
        18 => RuleId::AssertStmt,
        19 => RuleId::AsyncStmt,
        20 => RuleId::IfStmt,
        21 => RuleId::WhileStmt,
        22 => RuleId::ForStmt,
        23 => RuleId::TryStmt,
        24 => RuleId::WithStmt,
        25 => RuleId::SuiteBlockStmts,
        26 => RuleId::NamedexprTest,
        27 => RuleId::TestIfExpr,
        28 => RuleId::Lambdef,
        29 => RuleId::LambdefNocond,
        30 => RuleId::OrTest,
        31 => RuleId::AndTest,
        32 => RuleId::NotTest2,
        33 => RuleId::Comparison,
        34 => RuleId::StarExpr,
        35 => RuleId::Expr,
        36 => RuleId::XorExpr,
        37 => RuleId::AndExpr,
        38 => RuleId::ShiftExpr,
        39 => RuleId::ArithExpr,
        40 => RuleId::Term,
        41 => RuleId::Factor2,
        42 => RuleId::Power,
        43 => RuleId::AtomExprAwait,
        44 => RuleId::AtomExprNormal,
        45 => RuleId::AtomParen,
        46 => RuleId::AtomBracket,
        47 => RuleId::AtomBrace,
        48 => RuleId::TrailerParen,
        49 => RuleId::TrailerBracket,
        50 => RuleId::TrailerPeriod,
        51 => RuleId::Subscriptlist,
        52 => RuleId::Subscript2,
        53 => RuleId::Subscript3,
        54 => RuleId::Testlist,
        55 => RuleId::DictorsetmakerItem,
        56 => RuleId::Classdef,
        57 => RuleId::YieldExpr,
        58 => RuleId::ConstObject,
        59 => RuleId::GenericColonTest,
        60 => RuleId::GenericEqualTest,
        61 => RuleId::SingleInput,
        62 => RuleId::FileInput3,
        63 => RuleId::EvalInput,
        64 => RuleId::EvalInput2,
        65 => RuleId::Decorator,
        66 => RuleId::Decorators,
        67 => RuleId::DecoratedBody,
        68 => RuleId::AsyncFuncdef,
        69 => RuleId::Funcdefrettype,
        70 => RuleId::Typedargslist,
        71 => RuleId::TypedargslistItem,
        72 => RuleId::TypedargslistName,
        73 => RuleId::TypedargslistStar,
        74 => RuleId::TypedargslistDblStar,
        75 => RuleId::Tfpdef,
        76 => RuleId::Varargslist,
        77 => RuleId::VarargslistItem,
        78 => RuleId::VarargslistName,
        79 => RuleId::VarargslistStar,
        80 => RuleId::VarargslistDblStar,
        81 => RuleId::Vfpdef,
        82 => RuleId::Stmt,
        83 => RuleId::SimpleStmt,
        84 => RuleId::SmallStmt,
        85 => RuleId::ExprStmt2,
        86 => RuleId::ExprStmtAugassign,
        87 => RuleId::ExprStmtAssignList,
        88 => RuleId::ExprStmtAssign,
        89 => RuleId::ExprStmt6,
        90 => RuleId::TestlistStarExpr2,
        91 => RuleId::Annassign,
        92 => RuleId::Augassign,
        93 => RuleId::FlowStmt,
        94 => RuleId::RaiseStmtArg,
        95 => RuleId::RaiseStmtFrom,
        96 => RuleId::ImportStmt,
        97 => RuleId::ImportFrom2,
        98 => RuleId::ImportFrom2b,
        99 => RuleId::ImportFrom3,
        100 => RuleId::ImportAsNamesParen,
        101 => RuleId::OneOrMorePeriodOrEllipsis,
        102 => RuleId::PeriodOrEllipsis,
        103 => RuleId::ImportAsName,
        104 => RuleId::DottedAsName,
        105 => RuleId::AsName,
        106 => RuleId::ImportAsNames,
        107 => RuleId::DottedAsNames,
        108 => RuleId::DottedName,
        109 => RuleId::NameList,
        110 => RuleId::AssertStmtExtra,
        111 => RuleId::CompoundStmt,
        112 => RuleId::AsyncStmt2,
        113 => RuleId::IfStmtElifList,
        114 => RuleId::IfStmtElif,
        115 => RuleId::TryStmt2,
        116 => RuleId::TryStmtExceptAndMore,
        117 => RuleId::TryStmtExcept,
        118 => RuleId::TryStmtAsName,
        119 => RuleId::TryStmtExceptList,
        120 => RuleId::TryStmtFinally,
        121 => RuleId::ElseStmt,
        122 => RuleId::WithStmtList,
        123 => RuleId::WithItem,
        124 => RuleId::WithItemAs,
        125 => RuleId::Suite,
        126 => RuleId::SuiteBlock,
        127 => RuleId::NamedexprTest2,
        128 => RuleId::Test,
        129 => RuleId::TestIfElse,
        130 => RuleId::TestNocond,
        131 => RuleId::NotTest,
        132 => RuleId::CompOp,
        133 => RuleId::CompOpNotIn,
        134 => RuleId::CompOpIs,
        135 => RuleId::CompOpIsNot,
        136 => RuleId::ShiftOp,
        137 => RuleId::ArithOp,
        138 => RuleId::TermOp,
        139 => RuleId::Factor,
        140 => RuleId::FactorOp,
        141 => RuleId::AtomExpr,
        142 => RuleId::AtomExprTrailers,
        143 => RuleId::PowerDblStar,
        144 => RuleId::Atom,
        145 => RuleId::Atom2b,
        146 => RuleId::TestlistComp,
        147 => RuleId::TestlistComp2,
        148 => RuleId::TestlistComp3,
        149 => RuleId::TestlistComp3b,
        150 => RuleId::TestlistComp3c,
        151 => RuleId::Trailer,
        152 => RuleId::Subscript,
        153 => RuleId::Subscript3b,
        154 => RuleId::Subscript3c,
        155 => RuleId::Subscript3d,
        156 => RuleId::Sliceop,
        157 => RuleId::Exprlist,
        158 => RuleId::Exprlist2,
        159 => RuleId::Dictorsetmaker,
        160 => RuleId::DictorsetmakerTail,
        161 => RuleId::DictorsetmakerList,
        162 => RuleId::DictorsetmakerList2,
        163 => RuleId::Classdef2,
        164 => RuleId::Arglist,
        165 => RuleId::Arglist2,
        166 => RuleId::ArglistStar,
        167 => RuleId::ArglistDblStar,
        168 => RuleId::Argument,
        169 => RuleId::Argument2,
        170 => RuleId::Argument3,
        171 => RuleId::CompIter,
        172 => RuleId::CompFor,
        173 => RuleId::CompIf,
        174 => RuleId::YieldArg,
        175 => RuleId::YieldArgFrom,
        _ => unreachable!("rule id byte out of range"),
    }
}

pub const RULE_SINGLE_INPUT: RuleId = RuleId::SingleInput;
pub const RULE_FILE_INPUT: RuleId = RuleId::FileInput;
pub const RULE_EVAL_INPUT: RuleId = RuleId::EvalInput;

