# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.externals`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/boot/externals_py_bind.c
"""

from typing import Any

def get(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def list(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def register(*args: Any) -> Any:
    """Register or update a third-party stack id at runtime.

register(id: str, version: str, url: str = '', note: str = '') -> bool

Used by mods/*/autoload.py (and any guest code). Strings are copied into the host dyn table; same id updates in place. False if the table is full or id is empty."""
    ...

def __getattr__(name: str) -> Any: ...
