# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.fs`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/fs/fs_py_bind.c
"""

from typing import Any

def close(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def listdir(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def lseek(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def mkdir(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def open(*args: Any) -> Any:
    """Open a Metal FS path, returning a small-int file handle (-1 on failure).

open(path: str, mode: str) -> int

mode is one of 'r'/'rb', 'w'/'wb', 'a'/'ab', 'r+'/'r+b', 'w+'/'w+b' -- same subset os.py's own open() accepts (io.py wraps this into a file-like object; most callers should use that instead of this directly)."""
    ...

def read(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def rename(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def stat(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def unlink(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def write(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
