# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.tar`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/util/tar_py_bind.c
"""

from typing import Any

def close_read(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def close_write(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def finish(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def is_dir(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def name(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def next(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def open_read(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def open_write(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def put(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def read(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def size(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
