# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.time`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/dev/random/time_py_bind.c
"""

from typing import Any

def mono_us(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def realtime_ms(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def sleep_ms(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def tz_minutes(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
