def detect() -> int: ...
def open() -> int: ...
def capacity_sectors() -> int: ...
def read(lba: int, buf: bytearray | memoryview, nsec: int) -> int: ...
def read_async(lba: int, buf: bytearray | memoryview, nsec: int) -> int: ...
def result(h: int) -> int: ...
