"""Typing face (matrix Py count = max(glue,.pyi))."""

def pipe(*args, **kwargs): ...
def pty(*args, **kwargs): ...
def write(*args, **kwargs): ...
def try_read(*args, **kwargs): ...
def read(*args, **kwargs): ...
def drain(*args, **kwargs): ...
def close(*args, **kwargs): ...
def termios_get(*args, **kwargs): ...
def termios_set(*args, **kwargs): ...
def winsize_get(*args, **kwargs): ...
def winsize_set(*args, **kwargs): ...
def pending(*args, **kwargs): ...
def attach(*args, **kwargs): ...
def in(*args, **kwargs): ...
def out(*args, **kwargs): ...
def err(*args, **kwargs): ...
def feed_stdin(*args, **kwargs): ...
def write_line(*args, **kwargs): ...
