#!/usr/bin/env python3
"""Generate exp2/build/autoconf.h + config.sh (forge-private; forge config gen)."""
from __future__ import annotations

import sys
from pathlib import Path

from _util import enter_exp2_config, metal_root


def main() -> int:
    root = metal_root(Path(__file__))
    exp2 = root / "exp2"
    klib = root / "scripts" / "lib" / "kconfig"
    sys.path.insert(0, str(klib))

    import kconfiglib  # noqa: E402

    config_dir = exp2 / "config"
    dotconfig = config_dir / ".config"
    defconfig = config_dir / "defconfig"
    out_dir = exp2 / "build"
    autoconf = out_dir / "autoconf.h"
    config_sh = out_dir / "config.sh"

    size_to_bytes = {
        "PM_METAL_FS_ROOT_SIZE_MIB": ("PM_METAL_FS_ROOT_SIZE", 1024 * 1024),
    }

    enter_exp2_config(config_dir)
    kconf = kconfiglib.Kconfig("Kconfig", warn_to_stderr=True)
    if dotconfig.is_file():
        kconf.load_config(str(dotconfig))
    elif defconfig.is_file():
        kconf.load_config(str(defconfig))
    else:
        print("forge config gen: missing config/.config and config/defconfig", file=sys.stderr)
        return 1

    out_dir.mkdir(parents=True, exist_ok=True)

    lines = [
        "/* AUTO-GENERATED by forge config gen — do not edit */",
        "#ifndef PM_METAL_EXP2_AUTOCONF_H_",
        "#define PM_METAL_EXP2_AUTOCONF_H_",
        "",
    ]
    sh = [
        "# AUTO-GENERATED by forge config gen — do not edit",
        "# shellcheck shell=bash",
        "",
    ]
    for sym in kconf.unique_defined_syms:
        name = sym.name
        if sym.type == kconfiglib.BOOL or sym.type == kconfiglib.TRISTATE:
            if sym.tri_value == 2:
                lines.append(f"#define CONFIG_{name} 1")
                sh.append(f"export CONFIG_{name}=y")
            else:
                sh.append(f"export CONFIG_{name}=n")
        elif sym.type == kconfiglib.INT:
            val = sym.str_value
            lines.append(f"#define CONFIG_{name} {val}")
            sh.append(f"export CONFIG_{name}={val}")
            scaled = size_to_bytes.get(name)
            if scaled is not None:
                byte_name, mult = scaled
                try:
                    nbytes = int(val, 0) * mult
                except ValueError:
                    print(f"forge config gen: bad int for {name}={val!r}", file=sys.stderr)
                    return 1
                lines.append(f"#define CONFIG_{byte_name} {nbytes}")
                sh.append(f"export CONFIG_{byte_name}={nbytes}")
        elif sym.type == kconfiglib.HEX:
            val = sym.str_value
            lines.append(f"#define CONFIG_{name} {val}")
            sh.append(f"export CONFIG_{name}={val}")
        elif sym.type == kconfiglib.STRING:
            val = sym.str_value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'#define CONFIG_{name} "{val}"')
            sh.append(f'export CONFIG_{name}="{val}"')

    lines += ["", "#endif /* PM_METAL_EXP2_AUTOCONF_H_ */", ""]
    autoconf.write_text("\n".join(lines) + "\n")
    config_sh.write_text("\n".join(sh) + "\n")
    print(f"forge config gen: {autoconf}")
    print(f"forge config gen: {config_sh}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
