[package]
name = "pymergetic_metal_fs_tmpfs"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "../../src/pymergetic/metal/fs/tmpfs/__init__.rs"
crate-type = ["rlib"]

[dependencies]
pymergetic_metal_reg = { path = "../pymergetic_metal_reg" }
pymergetic_metal_rt = { path = "../pymergetic_metal_rt" }
pymergetic_metal_fs = { path = "../pymergetic_metal_fs" }
pymergetic_metal_fs_vfs = { path = "../pymergetic_metal_fs_vfs" }
