# µPy ``ssh`` builtin — export of pymergetic.metal.net.ssh.
# Module: src/pymergetic/metal/net/ssh/__init__.{h,c,rs,pyi}

from typing import TypeAlias

_WriteableBuffer: TypeAlias = bytearray | memoryview

__version__: str
info: str

def available() -> bool: ...
def init() -> int: ...
def autoload() -> int: ...
def listen(port: int) -> int: ...
def close(s: int) -> None: ...
def poll() -> int: ...
def served() -> int: ...
def client_exec(
    host: str,
    port: int,
    user: str,
    cmd: str,
    buf: _WriteableBuffer | None = ...,
) -> None: ...
def banner_send() -> int: ...
def banner_sent() -> int: ...
def banner_reset() -> None: ...
