#!/usr/bin/env bash
# Pack iface kinds h / c / pyi / py / meta into
# src/pymergetic/metal/util/iface_metal_guest_embed.inc.c — lz4(ustar).
#
# Kconfig (config/metal/util/Kconfig.iface):
#   CONFIG_PM_METAL_IFACE_EMBED_C_HEADERS
#   CONFIG_PM_METAL_IFACE_EMBED_C_IMPL
#   CONFIG_PM_METAL_IFACE_EMBED_PYTHON_HEADERS
#   CONFIG_PM_METAL_IFACE_EMBED_PYTHON_IMPL
# py@metal.stdlib is always baked when C headers are on (mandatory for µPy).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
INCLUDE_METAL="${ROOT}/include/pymergetic/metal"
METAL_H="${INCLUDE_METAL}/metal.h"
DOCS_DIR="${ROOT}/docs"
T8_INCLUDE="${ROOT}/mods/tests/t8_multimod_lib/include"
TYPINGS_DIR="${ROOT}/typings"
STDLIB_DIR="${ROOT}/mods/py/stdlib"
INC_OUT="${ROOT}/src/pymergetic/metal/util/iface_metal_guest_embed.inc.c"
C_IMPL_TREES=(
	"src/pymergetic/metal"
	"src/efi/pymergetic/metal"
	"src/bios/pymergetic/metal"
	"include/pymergetic/metal"
)

# shellcheck disable=SC1091
source "${ROOT}/scripts/lib/kconfig.sh"
pm_metal_kconfig_load

# shellcheck disable=SC1091
source "${ROOT}/scripts/lib/stage-py-trees.sh"

EMBED_C_HEADERS="${CONFIG_PM_METAL_IFACE_EMBED_C_HEADERS:-y}"
EMBED_C_IMPL="${CONFIG_PM_METAL_IFACE_EMBED_C_IMPL:-n}"
EMBED_PY_HEADERS="${CONFIG_PM_METAL_IFACE_EMBED_PYTHON_HEADERS:-y}"
EMBED_PY_IMPL="${CONFIG_PM_METAL_IFACE_EMBED_PYTHON_IMPL:-y}"

write_empty_install() {
	cat >"${INC_OUT}" <<'EOF'
/* AUTO-GENERATED by scripts/build.d/port/efi/embed-iface.sh — do not edit */
#include <stdint.h>
#include <pymergetic/metal/util/iface.h>

void pm_metal_iface_embed_install(void);
void pm_metal_iface_embed_install(void) {}
EOF
	echo "embed-iface: h packs disabled — empty install -> ${INC_OUT}" >&2
}

if [[ "${EMBED_C_HEADERS}" != "y" ]]; then
	write_empty_install
	exit 0
fi

if [[ ! -f "${METAL_H}" ]]; then
	echo "embed-iface: missing ${METAL_H}" >&2
	exit 1
fi

TMP="$(mktemp -d)"
# shellcheck disable=SC1091
source "${ROOT}/scripts/lib/iface-pack.sh"
trap 'pm_metal_iface_pack_cleanup; rm -rf "${TMP}"' EXIT
pm_metal_iface_pack_init

# Args: stage_dir pkg_name c_ident version KIND_MACRO
pack_one() {
	local stage="$1" name="$2" ident="$3" version="$4" kind="$5"
	local blob_path uncompressed_len
	blob_path="${TMP}/${ident}.tar.lz4"

	uncompressed_len="$(pm_metal_iface_pack_dir "${stage}" "${blob_path}")"

	echo "static const uint8_t g_pm_metal_iface_embed_${ident}[] = {"
	od -An -v -tx1 "${blob_path}" | sed 's/ \([0-9a-f][0-9a-f]\)/ 0x\1,/g'
	echo "};"
	echo "static const uint32_t g_pm_metal_iface_embed_${ident}_len = sizeof(g_pm_metal_iface_embed_${ident});"
	echo "static const uint32_t g_pm_metal_iface_embed_${ident}_uncompressed_len = ${uncompressed_len}u;"
	echo ""
	REGISTER_CALLS+=("  (void)pm_metal_iface_pkg_register(\"${name}\", ${kind}, \"${version}\", \"\", g_pm_metal_iface_embed_${ident}, g_pm_metal_iface_embed_${ident}_len, g_pm_metal_iface_embed_${ident}_uncompressed_len);")

	echo "embed-iface: ${name} (${kind}) <- ${stage} (${uncompressed_len} ustar -> $(wc -c <"${blob_path}" | tr -d ' ') lz4)" >&2
}

REGISTER_CALLS=()

STAGE_GUEST="${TMP}/stage_guest"
mkdir -p "${STAGE_GUEST}"

mapfile -t GUEST_HEADERS < <(
	grep -oE '"pymergetic/metal/[A-Za-z0-9_./]+\.h"' "${METAL_H}" | tr -d '"'
	echo "pymergetic/metal/wasi.h"
	echo "pymergetic/metal/version.h"
	find "${INCLUDE_METAL}/guest/mod" -maxdepth 1 -name '*.h' -printf 'pymergetic/metal/guest/mod/%f\n' 2>/dev/null || true
)

for rel in "${GUEST_HEADERS[@]}"; do
	src="${ROOT}/include/${rel}"
	if [[ ! -f "${src}" ]]; then
		echo "embed-iface: missing header ${rel}, skipped" >&2
		continue
	fi
	dst="${STAGE_GUEST}/${rel#pymergetic/metal/}"
	mkdir -p "$(dirname "${dst}")"
	cp -f "${src}" "${dst}"
done

STAGE_C_IMPL=""
if [[ "${EMBED_C_IMPL}" == "y" ]]; then
	STAGE_C_IMPL="${TMP}/stage_c_impl"
	mkdir -p "${STAGE_C_IMPL}"
	src_n=0
	for tree in "${C_IMPL_TREES[@]}"; do
		abs="${ROOT}/${tree}"
		if [[ ! -d "${abs}" ]]; then
			echo "embed-iface: c_impl tree missing, skip ${tree}" >&2
			continue
		fi
		while IFS= read -r -d '' src; do
			rel="${src#"${ROOT}"/}"
			dst="${STAGE_C_IMPL}/${rel}"
			mkdir -p "$(dirname "${dst}")"
			cp -f "${src}" "${dst}"
			src_n=$((src_n + 1))
		done < <(
			find "${abs}" -type f \( -name '*.c' -o -name '*.S' -o -name '*.s' -o -name '*.h' \) \
				! -name '*.inc.c' -print0
		)
	done
	echo "embed-iface: c_impl staged ${src_n} files" >&2
	if [[ "${src_n}" -eq 0 ]]; then
		STAGE_C_IMPL=""
	fi
fi

STAGE_META="${TMP}/stage_meta"
mkdir -p "${STAGE_META}"
meta_n=0
for f in LICENSE README.md; do
	if [[ -f "${ROOT}/${f}" ]]; then
		cp -f "${ROOT}/${f}" "${STAGE_META}/${f}"
		meta_n=$((meta_n + 1))
	else
		echo "embed-iface: missing ${f}, skipped for meta@metal.guest" >&2
	fi
done
if [[ "${meta_n}" -eq 0 ]]; then
	STAGE_META=""
fi

STAGE_DOCS=""
if [[ -d "${DOCS_DIR}" ]]; then
	STAGE_DOCS="${TMP}/stage_docs"
	mkdir -p "${STAGE_DOCS}"
	docs_n=0
	while IFS= read -r -d '' src; do
		base="$(basename "${src}")"
		cp -f "${src}" "${STAGE_DOCS}/${base}"
		docs_n=$((docs_n + 1))
	done < <(find "${DOCS_DIR}" -maxdepth 1 -type f -name '*.md' -print0 | sort -z)
	if [[ "${docs_n}" -eq 0 ]]; then
		STAGE_DOCS=""
	fi
fi

STAGE_PYI=""
if [[ "${EMBED_PY_HEADERS}" == "y" && -d "${TYPINGS_DIR}" ]]; then
	STAGE_PYI="${TMP}/stage_pyi"
	pm_metal_stage_py_typings_into "${STAGE_PYI}"
	if [[ -z "$(find "${STAGE_PYI}" -type f -name '*.pyi' 2>/dev/null | head -n 1)" ]]; then
		STAGE_PYI=""
	fi
fi

STAGE_PY_IMPL=""
if [[ "${EMBED_PY_IMPL}" == "y" ]]; then
	STAGE_PY_IMPL="${TMP}/stage_py_impl"
	pm_metal_stage_py_import_tree_into "${STAGE_PY_IMPL}"
	if [[ -z "$(find "${STAGE_PY_IMPL}" -type f -name '*.py' 2>/dev/null | head -n 1)" ]]; then
		echo "embed-iface: warning — python_impl empty; skip" >&2
		STAGE_PY_IMPL=""
	fi
fi

# Mandatory: MicroPython has no usable stdlib without this pack + ESP stage.
if [[ ! -d "${STDLIB_DIR}" ]]; then
	echo "embed-iface: missing mandatory ${STDLIB_DIR}" >&2
	exit 1
fi
STAGE_PY_STDLIB="${TMP}/stage_py_stdlib"
pm_metal_stage_py_copy_py_tree "${STDLIB_DIR}" "${STAGE_PY_STDLIB}"
if [[ -z "$(find "${STAGE_PY_STDLIB}" -type f -name '*.py' 2>/dev/null | head -n 1)" ]]; then
	echo "embed-iface: mandatory stdlib stage empty (${STDLIB_DIR})" >&2
	exit 1
fi

METAL_VERSION="$(git -C "${ROOT}" describe --tags --dirty --always 2>/dev/null || echo "0.0.0-unknown")"

{
	echo "/* AUTO-GENERATED by scripts/build.d/port/efi/embed-iface.sh — do not edit */"
	echo "#include <stdint.h>"
	echo "#include <pymergetic/metal/util/iface.h>"
	echo ""
	# Pack names: <kind>@<base> (e.g. h@metal.guest).
	pack_one "${STAGE_GUEST}" "h@metal.guest" "h_metal_guest" "${METAL_VERSION}" "PM_METAL_IFACE_PKG_H"

	if [[ -n "${STAGE_C_IMPL}" ]]; then
		pack_one "${STAGE_C_IMPL}" "c@metal.guest" "c_metal_guest" "${METAL_VERSION}" "PM_METAL_IFACE_PKG_C"
	fi

	if [[ -n "${STAGE_META}" ]]; then
		pack_one "${STAGE_META}" "meta@metal.guest" "meta_metal_guest" "${METAL_VERSION}" "PM_METAL_IFACE_PKG_META"
	fi

	if [[ -n "${STAGE_DOCS}" ]]; then
		pack_one "${STAGE_DOCS}" "meta@metal.guest.docs" "meta_metal_guest_docs" "${METAL_VERSION}" "PM_METAL_IFACE_PKG_META"
	fi

	if [[ -d "${T8_INCLUDE}" ]]; then
		pack_one "${T8_INCLUDE}" "h@mod.t8_multimod_lib" "h_mod_t8_multimod_lib" "" "PM_METAL_IFACE_PKG_H"
	else
		echo "embed-iface: ${T8_INCLUDE} missing, h@mod.t8_multimod_lib pack skipped" >&2
	fi

	if [[ -n "${STAGE_PYI}" ]]; then
		pack_one "${STAGE_PYI}" "pyi@metal.guest" "pyi_metal_guest" "${METAL_VERSION}" "PM_METAL_IFACE_PKG_PYI"
	fi

	if [[ -n "${STAGE_PY_IMPL}" ]]; then
		pack_one "${STAGE_PY_IMPL}" "py@metal.guest" "py_metal_guest" "${METAL_VERSION}" "PM_METAL_IFACE_PKG_PY"
	fi

	pack_one "${STAGE_PY_STDLIB}" "py@metal.stdlib" "py_metal_stdlib" "${METAL_VERSION}" "PM_METAL_IFACE_PKG_PY"

	echo "void pm_metal_iface_embed_install(void);"
	echo "void pm_metal_iface_embed_install(void)"
	echo "{"
	for call in "${REGISTER_CALLS[@]}"; do
		echo "${call}"
	done
	echo "}"
} >"${INC_OUT}"

echo "embed-iface: wrote ${INC_OUT}"
