manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject
      revision: v4.4.0
      clone-depth: 1
      import:
        path-prefix: external
    - name: tlsf
      url: https://github.com/mattconte/tlsf
      revision: deff9ab509341f264addbd3c8ada533678591905
      path: external/tlsf
    - name: wasm-micro-runtime
      url: https://github.com/bytecodealliance/wasm-micro-runtime
      revision: WAMR-2.4.5
      path: external/wamr
    - name: lz4
      url: https://github.com/lz4/lz4
      revision: v1.10.0
      path: external/lz4
    - name: microtar
      url: https://github.com/rxi/microtar
      revision: 27076e1b9290e9c7842bb7890a54fcf172406c84
      path: external/microtar
