# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.mem`` — generated package re-exports (scripts/gen_py_stubs.py).
"""

from typing import Any

from . import limit as limit

__all__ = ['limit']
__path__: list[str]

def __getattr__(name: str) -> Any: ...
