def empty() -> bytearray: ...
def init(a: bytearray | memoryview, base: bytearray | memoryview) -> int: ...
def ready(a: bytearray | memoryview) -> int: ...
def bytes(a: bytearray | memoryview) -> int: ...
def map_used(a: bytearray | memoryview) -> int: ...
def heap_used(a: bytearray | memoryview) -> int: ...
def hole(a: bytearray | memoryview) -> int: ...
def heap_grow(a: bytearray | memoryview, bytes: int) -> int: ...
def map(a: bytearray | memoryview, bytes: int) -> int: ...
def unmap(a: bytearray | memoryview, ptr: int, bytes: int) -> int: ...
def align_up(x: int, a: int) -> int: ...
def align_down(x: int, a: int) -> int: ...
def page_size() -> int: ...
