# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.mem.limit`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/runtime/mem/limit_py_bind.c
"""

from typing import Any

def get(*args: Any) -> Any:
    """Lookup one budget row by id (module.name).

get(id: str) -> dict | None

Returns the same dict shape as list() entries, or None."""
    ...

def list(*args: Any) -> Any:
    """List compile-time memory/buffer budget rows.

list() -> list[dict]

Each dict is {id, module, name, value, unit, note}. id is 'module.name' (e.g. net.asgi.ASGI_IO_MAX)."""
    ...

def module(*args: Any) -> Any:
    """List budget rows for a module name or prefix.

module(name: str) -> list[dict]

'net' matches net and net.asgi / net.ip / net.tls; exact module names match only that module."""
    ...

def __getattr__(name: str) -> Any: ...
