def spin_init(s: bytearray | memoryview) -> None: ...
def spin_lock(s: bytearray | memoryview) -> None: ...
def spin_try_lock(s: bytearray | memoryview) -> int: ...
def spin_unlock(s: bytearray | memoryview) -> None: ...
def mutex_init(m: bytearray | memoryview) -> None: ...
def mutex_lock(m: bytearray | memoryview) -> None: ...
def mutex_try_lock(m: bytearray | memoryview) -> int: ...
def mutex_unlock(m: bytearray | memoryview) -> None: ...
