def size() -> int: ...
def pool_overhead() -> int: ...
def align_size() -> int: ...
def alloc_overhead() -> int: ...
def block_size_min() -> int: ...
def block_size_max() -> int: ...
def create(mem: bytearray | memoryview) -> int: ...
def create_with_pool(mem: bytearray | memoryview) -> int: ...
def destroy(t: int) -> None: ...
def get_pool(t: int) -> int: ...
def add_pool(t: int, mem: bytearray | memoryview) -> int: ...
def remove_pool(t: int, pool: int) -> None: ...
def malloc(t: int, size: int) -> int: ...
def memalign(t: int, align: int, size: int) -> int: ...
def realloc(t: int, ptr: int, size: int) -> int: ...
def free(t: int, ptr: int) -> None: ...
def block_size(ptr: int) -> int: ...
def walk_pool(pool: int, walker: int, user: int) -> None: ...
def check(t: int) -> int: ...
def check_pool(pool: int) -> int: ...
