#!/usr/bin/env python3
"""
Generate typings/**.pyi from the C source of truth instead of hand-editing
stubs that drift — Phase 2e (docs/MICROPYTHON.md, docs/TODO.md).

Three sources, generated outputs:

  pymergetic.metal.*  <- PM_METAL_PY_BIND(var, "mod.str", "name_str", fn_obj,
                          class_) call sites across src/pymergetic/metal/**.
                          One nested .pyi per dotted module, one
                          "def name(*args) -> ...:" per row. When a module
                          also has child modules (e.g. net + net.ssh), it is
                          emitted as a package ``…/net/__init__.pyi`` (not a
                          sibling ``net.pyi``).

  Package __init__.pyi  <- derived from the same bind set (+ always
                          ``pymergetic.metal.mod``): re-exports every direct
                          child so ``from pymergetic.metal import net`` etc.
                          type-check. No hand-maintained package stubs.

  pmcmd.*             <- PM_METAL_SHELL_CMD(var, name_str, help_str, fn_) and
                          PM_METAL_SHELL_CMDS(arr) = { {name, help, fn}, ... }
                          call sites across src/pymergetic/metal/**. One
                          typings/pmcmd.pyi, help_str as each def's docstring.

  pymergetic.metal.mod.*  <- pm_metal_mod_register_func(name, export_name)
                          call sites inside each in-tree mod's own source
                          under mods/**, grouped by owning mod (best-effort:
                          the mod's directory name is used as a stand-in for
                          its runtime-registered name, which is usually but
                          not always identical — e.g. build_one's alias in
                          scripts/build.d/port/efi/embed-mods.sh can rename
                          t0_hello's directory to "hello". Mods loaded later
                          at runtime and not present in mods/** at build time
                          get no stub at all — documented limitation, not a
                          bug, same as the pmcmd fallback below).

Every generated file keeps a `def __getattr__(name) -> Any: ...` (or a
class-level equivalent) fallback so anything this static scan missed still
type-checks as Any instead of erroring.

Hand-authored (not this script): typings/{os,uio,deflate}.pyi — port/stdlib
or upstream MicroPython modules with no PM_METAL_PY_BIND rows.

Usage: scripts/gen_py_stubs.py [--check]
  --check   Exit 1 if regenerating would change any file (CI/pre-commit use;
            does not itself write anything in that case... actually it does
            write, then diffs — see main()). Prints changed paths either way.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_METAL = ROOT / "src" / "pymergetic" / "metal"
MODS_DIR = ROOT / "mods"
TYPINGS = ROOT / "typings"

HEADER = "# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)\n"

PY_BIND_RE = re.compile(
    r'PM_METAL_PY_BIND\s*\(\s*'
    r'(?P<var>[A-Za-z_]\w*)\s*,\s*'
    r'"(?P<mod>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'"(?P<name>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'(?P<fn_obj>[A-Za-z_]\w*)\s*,\s*'
    r'(?P<class_>PM_METAL_PY_\w+)\s*\)',
    re.MULTILINE,
)

# DOC field slot: one-or-more *adjacent* string literals (plain C string
# concatenation — `"a " "b"` is one string, and every DOC field long
# enough to wrap a line in this codebase uses exactly that), or NULL, or a
# C identifier (e.g. a g_foo_summary variable, per
# docs/DOC_IFACE_PLAN.md's interface preview) — an identifier is not a
# static-scan-friendly literal, so it degrades to None here same as NULL;
# doc.c (runtime) still sees the real value either way, this only affects
# the generated stub's docstring richness.
_STR_LIT = r'"(?:[^"\\]|\\.)*"'
_DOC_FIELD = rf'{_STR_LIT}(?:\s*{_STR_LIT})*|NULL|[A-Za-z_]\w*'
_STR_LIT_RE = re.compile(_STR_LIT)

PY_BIND_DOC_RE = re.compile(
    r'PM_METAL_PY_BIND_DOC\s*\(\s*'
    r'(?P<var>[A-Za-z_]\w*)\s*,\s*'
    r'"(?P<mod>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'"(?P<name>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'(?P<fn_obj>[A-Za-z_]\w*)\s*,\s*'
    r'(?P<class_>PM_METAL_PY_\w+)\s*,\s*'
    rf'(?P<summary>{_DOC_FIELD})\s*,\s*'
    rf'(?P<sig>{_DOC_FIELD})\s*,\s*'
    rf'(?P<body>{_DOC_FIELD})\s*\)',
    re.MULTILINE,
)

SHELL_CMD_RE = re.compile(
    r'PM_METAL_SHELL_CMD\s*\(\s*[A-Za-z_]\w*\s*,\s*'
    r'"(?P<name>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'"(?P<help>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'[A-Za-z_]\w*\s*\)',
    re.MULTILINE,
)

SHELL_CMD_DOC_RE = re.compile(
    r'PM_METAL_SHELL_CMD_DOC\s*\(\s*[A-Za-z_]\w*\s*,\s*'
    r'"(?P<name>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'"(?P<help>(?:[^"\\]|\\.)*)"\s*,\s*'
    rf'(?P<sig>{_DOC_FIELD})\s*,\s*'
    rf'(?P<body>{_DOC_FIELD})\s*,\s*'
    r'[A-Za-z_]\w*\s*\)',
    re.MULTILINE,
)


def doc_field(raw: str | None) -> str | None:
    """A DOC_FIELD match's text -> literal content, or None (NULL / identifier).

    `raw` may hold more than one adjacent string literal (C concatenation,
    e.g. `"a " "b"` split across lines to stay under ~100 cols) — every
    piece is unescaped and joined with no separator, same as the C
    compiler's own string-literal concatenation."""
    if raw is None or raw == "NULL":
        return None
    if raw.startswith('"'):
        return "".join(unescape(m.group(0)[1:-1]) for m in _STR_LIT_RE.finditer(raw))
    return None  # C identifier — see _DOC_FIELD's comment above


def doc_string_from_parts(parts) -> str | None:
    """(summary, sig, body) -> joined docstring text, "\\n\\n" between
    non-None parts (same join util/doc.c / py_bind.c use), or None if all
    three are None (identifier fields, or a plain PY_BIND with no doc)."""
    joined = [p.replace('"""', "'''") for p in parts if p]
    return "\n\n".join(joined) if joined else None

SHELL_CMDS_TABLE_RE = re.compile(
    r'PM_METAL_SHELL_CMDS\s*\(\s*(?P<arr>[A-Za-z_]\w*)\s*\)\s*=\s*\{(?P<body>.*?)\}\s*;\s*'
    r'PM_METAL_SHELL_CMDS_END\s*\(\s*(?P=arr)\s*\)',
    re.DOTALL,
)

SHELL_CMDS_ROW_RE = re.compile(
    r'\{\s*"(?P<name>(?:[^"\\]|\\.)*)"\s*,\s*"(?P<help>(?:[^"\\]|\\.)*)"\s*,\s*[A-Za-z_]\w*\s*\}'
)

# A PM_METAL_SHELL_CMDS(arr) row may also be a raw 5-field struct literal
# (name, help, fn, sig, body — shell_cmd.h's own trailing fields, no macro
# involved since PM_METAL_SHELL_CMD_DOC only covers the single-command
# form) — e.g. shell_core_cmds.c's own "mem" row.
SHELL_CMDS_ROW_DOC_RE = re.compile(
    r'\{\s*"(?P<name>(?:[^"\\]|\\.)*)"\s*,\s*"(?P<help>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'[A-Za-z_]\w*\s*,\s*'
    rf'(?P<sig>{_DOC_FIELD})\s*,\s*'
    rf'(?P<body>{_DOC_FIELD})\s*\}}',
    re.DOTALL,
)

MOD_REGISTER_FUNC_RE = re.compile(
    r'pm_metal_mod_register_func\s*\(\s*'
    r'"(?P<name>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'"(?P<export>(?:[^"\\]|\\.)*)"\s*\)'
)

# pm_metal_mod_register_func_doc(name, export, summary, sig, body) —
# docs/DOC_IFACE_PLAN.md Part I-D; same (name, export) pair as the plain
# call above, plus doc fields for the generated stub's docstring.
MOD_REGISTER_FUNC_DOC_RE = re.compile(
    r'pm_metal_mod_register_func_doc\s*\(\s*'
    r'"(?P<name>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'"(?P<export>(?:[^"\\]|\\.)*)"\s*,\s*'
    rf'(?P<summary>{_DOC_FIELD})\s*,\s*'
    rf'(?P<sig>{_DOC_FIELD})\s*,\s*'
    rf'(?P<body>{_DOC_FIELD})\s*\)',
    re.DOTALL,
)


def unescape(s: str) -> str:
    return s.replace('\\"', '"').replace("\\\\", "\\")


def iter_c_files(root: Path):
    yield from sorted(root.rglob("*.c"))


def is_ident(name: str) -> bool:
    return bool(re.match(r"^[A-Za-z_]\w*$", name)) and name not in (
        "class", "def", "import", "from", "global", "lambda", "return",
        "yield", "raise", "assert", "pass", "async", "await",
    )


# --- pymergetic.metal.* (PM_METAL_PY_BIND) ---

def scan_py_binds():
    by_mod = {}
    for f in iter_c_files(SRC_METAL):
        text = f.read_text(errors="replace")
        for m in PY_BIND_RE.finditer(text):
            mod = unescape(m.group("mod"))
            name = unescape(m.group("name"))
            class_ = m.group("class_")
            by_mod.setdefault(mod, []).append((name, class_, f.relative_to(ROOT), None))
        for m in PY_BIND_DOC_RE.finditer(text):
            mod = unescape(m.group("mod"))
            name = unescape(m.group("name"))
            class_ = m.group("class_")
            doc = (doc_field(m.group("summary")), doc_field(m.group("sig")), doc_field(m.group("body")))
            by_mod.setdefault(mod, []).append((name, class_, f.relative_to(ROOT), doc))
    return by_mod


def module_names(by_mod_binds) -> set:
    """All pymergetic.* modules that should appear in the stub tree."""
    names = set(by_mod_binds)
    names.add("pymergetic.metal.mod")  # custom attr proxy, not PM_METAL_PY_BIND
    return names


def package_names(modules: set) -> set:
    """Proper prefixes of every module — those must be packages with __init__.pyi."""
    pkgs = set()
    for mod in modules:
        parts = mod.split(".")
        for i in range(1, len(parts)):
            pkgs.add(".".join(parts[:i]))
    return pkgs


def mod_dotted_to_path(mod: str, packages: set) -> Path:
    parts = mod.split(".")
    base = TYPINGS.joinpath(*parts)
    if mod in packages:
        return base / "__init__.pyi"
    return base.with_suffix(".pyi")


def direct_children(parent: str, modules: set, packages: set) -> list:
    """Immediate child names under parent (modules or nested packages)."""
    prefix = parent + "."
    kids = set()
    for name in modules | packages:
        if not name.startswith(prefix):
            continue
        rest = name[len(prefix) :]
        if "." in rest:
            continue
        if is_ident(rest):
            kids.add(rest)
    return sorted(kids)


def render_py_bind_module(mod: str, rows, child_names=None) -> str:
    lines = [HEADER, '"""', f"``{mod}`` — generated from PM_METAL_PY_BIND call sites.", "", "Sources:"]
    seen_files = sorted({str(r[2]) for r in rows})
    for sf in seen_files:
        lines.append(f"  {sf}")
    lines.append('"""')
    lines.append("")
    lines.append("from typing import Any")
    lines.append("")
    all_names = []
    for name, class_, _src, doc in sorted(rows, key=lambda r: r[0]):
        if not is_ident(name.rstrip("_")) and not is_ident(name):
            continue
        # class_ (PM_METAL_PY_SYNC/ASYNC/FACADE) describes the C-side install,
        # not the Python-visible return shape (e.g. a SYNC bind can still
        # return an awaitable object, like aio.sleep_us) — noted, not typed.
        lines.append(f"def {name}(*args: Any) -> Any:")
        docstring = doc_string_from_parts(doc) if doc else None
        if docstring:
            lines.append(f'    """{docstring}"""')
        else:
            lines.append(f'    """C bind: {class_}."""')
        lines.append("    ...")
        lines.append("")
        all_names.append(name)
    if child_names:
        for child in child_names:
            lines.append(f"from . import {child} as {child}")
        lines.append("")
        all_names.extend(child_names)
        lines.append(f"__all__ = {all_names!r}")
        lines.append("__path__: list[str]")
        lines.append("")
    lines.append("def __getattr__(name: str) -> Any: ...")
    lines.append("")
    return "\n".join(lines)


def render_package_init(mod: str, child_names: list) -> str:
    """Package with no bind rows of its own — re-export children only."""
    lines = [
        HEADER,
        '"""',
        f"``{mod}`` — generated package re-exports (scripts/gen_py_stubs.py).",
        '"""',
        "",
        "from typing import Any",
        "",
    ]
    for child in child_names:
        lines.append(f"from . import {child} as {child}")
    lines.append("")
    lines.append(f"__all__ = {child_names!r}")
    lines.append("__path__: list[str]")
    lines.append("")
    lines.append("def __getattr__(name: str) -> Any: ...")
    lines.append("")
    return "\n".join(lines)


def remove_if_exists(path: Path, removed: list) -> None:
    if path.is_file():
        path.unlink()
        removed.append(path)


# --- pmcmd.* (PM_METAL_SHELL_CMD / PM_METAL_SHELL_CMDS) ---

def scan_shell_cmds():
    rows = []
    for f in iter_c_files(SRC_METAL):
        text = f.read_text(errors="replace")
        for m in SHELL_CMD_RE.finditer(text):
            rows.append((unescape(m.group("name")), unescape(m.group("help")), None, None))
        for tm in SHELL_CMDS_TABLE_RE.finditer(text):
            body = tm.group("body")
            doc_spans = []
            for m in SHELL_CMDS_ROW_DOC_RE.finditer(body):
                doc_spans.append(m.span())
                rows.append((
                    unescape(m.group("name")),
                    unescape(m.group("help")),
                    doc_field(m.group("sig")),
                    doc_field(m.group("body")),
                ))
            for m in SHELL_CMDS_ROW_RE.finditer(body):
                if any(a <= m.start() < b for a, b in doc_spans):
                    continue  # already captured (richer) by the 5-field pass above
                rows.append((unescape(m.group("name")), unescape(m.group("help")), None, None))
        for m in SHELL_CMD_DOC_RE.finditer(text):
            rows.append((
                unescape(m.group("name")),
                unescape(m.group("help")),
                doc_field(m.group("sig")),
                doc_field(m.group("body")),
            ))
    return rows


def render_pmcmd(rows) -> str:
    lines = [
        HEADER,
        '"""',
        "``pmcmd`` — every registered shell command as a real attribute.",
        "",
        "Generated from PM_METAL_SHELL_CMD / PM_METAL_SHELL_CMDS call sites under",
        "src/pymergetic/metal/**. Deliberately the one module that does NOT carry",
        "the ``pymergetic.metal.*`` prefix — see docs/MICROPYTHON.md.",
        "",
        "Mod-registered commands (pm_metal_mod_register_cmd, runtime-only — a mod's",
        "on_load must actually run before they exist) are NOT covered by this static",
        "scan; they still work at runtime via __getattr__ below, just without a",
        "named stub.",
        '"""',
        "",
        "from typing import Any",
        "",
    ]
    seen = set()
    for name, help_, sig, body in sorted(rows, key=lambda r: r[0]):
        if name in seen or not is_ident(name):
            continue
        seen.add(name)
        lines.append(f"def {name}(*args: Any) -> Any:")
        doc = doc_string_from_parts((help_, sig, body)) or help_.replace('"""', "'''") or name
        lines.append(f'    """{doc}"""')
        lines.append("    ...")
        lines.append("")
    lines.append("def __getattr__(name: str) -> Any: ...")
    lines.append("")
    return "\n".join(lines)


# --- pymergetic.metal.mod.* (pm_metal_mod_register_func, best-effort) ---

def scan_mod_funcs():
    """mod_name -> {func_name: doc_or_None}; doc is (summary, sig, body)
    from a _doc call, else None for a plain pm_metal_mod_register_func."""
    by_mod = {}
    if not MODS_DIR.is_dir():
        return by_mod
    for f in iter_c_files(MODS_DIR):
        text = f.read_text(errors="replace")
        funcs = {}
        doc_spans = []
        for m in MOD_REGISTER_FUNC_DOC_RE.finditer(text):
            doc_spans.append(m.span())
            doc = (doc_field(m.group("summary")), doc_field(m.group("sig")), doc_field(m.group("body")))
            funcs[unescape(m.group("name"))] = doc
        for m in MOD_REGISTER_FUNC_RE.finditer(text):
            if any(a <= m.start() < b for a, b in doc_spans):
                continue  # substring can't actually overlap (see _doc's own "_" gap), kept defensive
            name = unescape(m.group("name"))
            funcs.setdefault(name, None)
        if not funcs:
            continue
        mod_name = f.parent.name
        merged = by_mod.setdefault(mod_name, {})
        for name, doc in funcs.items():
            if doc is not None or name not in merged:
                merged[name] = doc
    return by_mod


def render_mod_module(by_mod) -> str:
    lines = [
        HEADER,
        '"""',
        "``pymergetic.metal.mod`` — ``mod.<name>.<func>()`` real attribute access",
        "over the mod registry (docs/MODS.md), plus ``mod.<name>.fresh()`` for a",
        "private FRESH-mode instance (Phase 2d).",
        "",
        "Best-effort generated from pm_metal_mod_register_func(...) call sites",
        "under mods/**, grouped by the mod's own source directory name — usually",
        "but not always identical to its runtime-registered name (some mods are",
        "aliased at embed time, e.g. scripts/build.d/port/efi/embed-mods.sh's",
        "t0_hello -> \"hello\"). Mods loaded later at runtime and not present in",
        "mods/** at build time get no stub — use the module-level __getattr__",
        "fallback, which always works (real attribute access, not string dispatch,",
        "at runtime — this is purely a static-analysis gap).",
        '"""',
        "",
        "from typing import Any, Awaitable",
        "",
    ]
    for mod_name in sorted(by_mod):
        funcs = sorted(by_mod[mod_name])
        if not is_ident(mod_name):
            continue
        scope_cls = f"_ModFresh_{mod_name}"
        mod_cls = f"_Mod_{mod_name}"

        def _method_lines(fn: str, doc) -> list:
            out = [f"    def {fn}(self, *args: Any) -> Awaitable[Any]:"]
            docstring = doc_string_from_parts(doc) if doc else None
            if docstring:
                out.append(f'        """{docstring}"""')
                out.append("        ...")
            else:
                out[-1] += " ..."
            return out

        lines.append(f"class {scope_cls}:")
        lines.append(f'    """Fresh-instance scope for "{mod_name}" (async with)."""')
        lines.append("")
        lines.append(f"    async def __aenter__(self) -> \"{scope_cls}\": ...")
        lines.append("    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> bool: ...")
        for fn in funcs:
            if is_ident(fn):
                lines.extend(_method_lines(fn, by_mod[mod_name][fn]))
        lines.append("")
        lines.append(f"class {mod_cls}:")
        for fn in funcs:
            if is_ident(fn):
                lines.extend(_method_lines(fn, by_mod[mod_name][fn]))
        lines.append(f"    def fresh(self) -> {scope_cls}: ...")
        lines.append("")
        lines.append(f"{mod_name}: {mod_cls}")
        lines.append("")
    lines.append("def __getattr__(name: str) -> Any: ...")
    lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text() if path.exists() else None
    if old == content:
        return False
    path.write_text(content)
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if any output would change")
    args = ap.parse_args()

    changed = []
    removed = []

    by_mod_binds = scan_py_binds()
    modules = module_names(by_mod_binds)
    packages = package_names(modules)

    for mod, rows in by_mod_binds.items():
        kids = direct_children(mod, modules, packages) if mod in packages else []
        out = mod_dotted_to_path(mod, packages)
        if write_if_changed(out, render_py_bind_module(mod, rows, kids or None)):
            changed.append(out)
        # Migrating module.pyi -> package/__init__.pyi: drop the old sibling.
        if mod in packages:
            remove_if_exists(TYPINGS.joinpath(*mod.split(".")).with_suffix(".pyi"), removed)

    for pkg in sorted(packages):
        if pkg in by_mod_binds:
            continue  # already written with bind defs + child re-exports
        kids = direct_children(pkg, modules, packages)
        out = mod_dotted_to_path(pkg, packages)
        if write_if_changed(out, render_package_init(pkg, kids)):
            changed.append(out)

    cmd_rows = scan_shell_cmds()
    pmcmd_out = TYPINGS / "pmcmd.pyi"
    if write_if_changed(pmcmd_out, render_pmcmd(cmd_rows)):
        changed.append(pmcmd_out)

    mod_funcs = scan_mod_funcs()
    mod_out = TYPINGS / "pymergetic" / "metal" / "mod.pyi"
    if write_if_changed(mod_out, render_mod_module(mod_funcs)):
        changed.append(mod_out)

    n_binds = sum(len(v) for v in by_mod_binds.values())
    print(
        f"gen_py_stubs: {len(by_mod_binds)} py-bind modules ({n_binds} rows), "
        f"{len(packages)} packages, {len(cmd_rows)} shell cmds, "
        f"{len(mod_funcs)} mods with registered funcs"
    )
    for c in changed:
        print(f"gen_py_stubs: wrote {c.relative_to(ROOT)}")
    for c in removed:
        print(f"gen_py_stubs: removed {c.relative_to(ROOT)}")

    if args.check and (changed or removed):
        print("gen_py_stubs: --check found stale stubs (regenerated above)", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
