# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic`` — generated package re-exports (scripts/gen_py_stubs.py).
"""

from typing import Any

from . import metal as metal

__all__ = ['metal']
__path__: list[str]

def __getattr__(name: str) -> Any: ...
