/* IDE/clangd stub — real header is generated by zefi.py at EFI build time. */
/* GENERATED CODE.  DO NOT EDIT. */

struct data_seg { uint64_t addr; uint32_t sz; uint32_t off; };

static struct data_seg zefi_dsegs[] = {
};

struct zero_seg { uint64_t addr; uint32_t sz; };

static struct zero_seg zefi_zsegs[] = {
};

static uintptr_t zefi_entry = 0UL;
