// AUTO-GENERATED by forge img rootfs — do not edit

pub const KERNEL_MODULE_ID: &str = "pymergetic.metal";
pub const LOG_BOOT_MOUNTS: bool = true;
pub const HAVE_MODS: bool = true;
pub const HAVE_SRC: bool = true;

pub static MODS_MTAR: &[u8] = include_bytes!("../../../../../build/rootfs/mods.mtar");
pub static SRC_MTAR: &[u8] = include_bytes!("../../../../../build/rootfs/src.mtar");
