#!/usr/bin/env bash
# Embed named lz4 guest packages for Zephyr (same packages as Linux/NuttX).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
# shellcheck disable=SC1091
source "${ROOT}/scripts/lib/guest-pkgs.sh"

OUT_DIR="${ROOT}/src/zephyr/generated"
mkdir -p "${OUT_DIR}"

pm_guest_pkgs_compose

# Copy package .c + pkgs_init.c into zephyr generated for west to pick up.
rm -f "${OUT_DIR}/pkg_"*.c "${OUT_DIR}/pkgs_init.c" "${OUT_DIR}/pkgs.cmake"
shopt -s nullglob
for f in "${PM_GUEST_PKGS}"/pkg_*.c "${PM_GUEST_PKGS}/pkgs_init.c"; do
	[[ -f "${f}" ]] || continue
	cp -f "${f}" "${OUT_DIR}/"
done
shopt -u nullglob
{
	echo "# Generated by embed.sh — do not edit."
	echo "set(PM_METAL_GUEST_PKG_SOURCES"
	for f in "${OUT_DIR}"/pkg_*.c; do
		echo "	${f}"
	done
	if [[ -f "${OUT_DIR}/pkgs_init.c" ]]; then
		echo "	${OUT_DIR}/pkgs_init.c"
	fi
	echo ")"
} >"${OUT_DIR}/pkgs.cmake"

# Remove legacy embed artifacts so they are not linked by accident.
rm -f "${OUT_DIR}/mods_embed.c" "${OUT_DIR}/mods_embed.h" \
	"${OUT_DIR}/python_embed.S" "${OUT_DIR}/populate_embed.c"

echo "zephyr embed: packages in ${OUT_DIR}"
