"""Typing face (matrix Py count = max(glue,.pyi))."""

def detect(*args, **kwargs): ...
def open(*args, **kwargs): ...
def ready(*args, **kwargs): ...
def mac(*args, **kwargs): ...
def tx(*args, **kwargs): ...
def poll(*args, **kwargs): ...
