[package]
name = "pymergetic_metal_fs_littlefs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
path = "../__init__.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
pymergetic_metal_rt = { path = "../../../rt/.pm" }
pymergetic_metal_async = { path = "../../../async/.pm" }
pymergetic_metal_fs = { path = "../../.pm" }
pymergetic_metal_fs_vfs = { path = "../../vfs/.pm" }

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
