# Build named lz4 guest packages and embed .c files for all platforms.
# Packages:
#   mods-tests          /mods/tests/*.wasm
#   python-stdlib       /lib/python3.14/** (+ folded wasi sysconfig files)
#   mods-apps-python    /mods/apps/python.wasm, pm-test.py  deps: python-stdlib
#
# Outputs under build/guest-pkgs/:
#   pkg_mods_tests.c  pkg_python_stdlib.c  pkg_mods_apps_python.c
#   pkgs.cmake        — list of .c to link
#
# shellcheck shell=bash

: "${PM_METAL_GUEST_TESTS:=1}"
: "${PM_METAL_APP_PYTHON:=1}"

PM_GUEST_PKGS="${ROOT}/build/guest-pkgs"
PM_GUEST_PKGS_STAMP="${PM_GUEST_PKGS}/.stamp"

pm_guest_pkgs_stamp_payload() {
	printf 'tests=%s python=%s\n' "${PM_METAL_GUEST_TESTS}" "${PM_METAL_APP_PYTHON}"
}

pm_guest_pkgs_is_fresh() {
	[[ "${PM_METAL_FORCE_PACKAGE:-0}" == "1" ]] && return 1
	[[ -f "${PM_GUEST_PKGS_STAMP}" ]] || return 1
	[[ "$(cat "${PM_GUEST_PKGS_STAMP}")" == "$(pm_guest_pkgs_stamp_payload)" ]] || return 1
	[[ -f "${PM_GUEST_PKGS}/pkgs.cmake" ]] || return 1
	return 0
}

# Compose package staging dirs + pack-pkg embeds. Also refreshes guest-package tree.
pm_guest_pkgs_compose() {
	local stage cfiles=()

	# shellcheck disable=SC1091
	source "${ROOT}/scripts/lib/guest-package.sh"
	pm_guest_package_compose

	if pm_guest_pkgs_is_fresh; then
		echo "guest-pkgs: up to date (${PM_GUEST_PKGS})"
		return 0
	fi

	rm -rf "${PM_GUEST_PKGS}"
	mkdir -p "${PM_GUEST_PKGS}"

	if [[ "${PM_METAL_GUEST_TESTS}" == "1" ]]; then
		stage="$(mktemp -d)"
		mkdir -p "${stage}/mods/tests"
		cp -a "${PM_GUEST_PACKAGE_TESTS}/." "${stage}/mods/tests/"
		"${ROOT}/scripts/lib/pack-pkg.sh" --id=mods-tests "${stage}" \
			"${PM_GUEST_PKGS}/pkg_mods_tests.c"
		cfiles+=("${PM_GUEST_PKGS}/pkg_mods_tests.c")
		rm -rf "${stage}"
	fi

	if [[ "${PM_METAL_APP_PYTHON}" == "1" ]]; then
		stage="$(mktemp -d)"
		mkdir -p "${stage}/lib/python3.14"
		cp -a "${PM_GUEST_PACKAGE_LIB}/." "${stage}/lib/python3.14/"
		# Fold wasi sysconfig into Lib prefix (no /wasi-lib).
		cp -a "${PM_GUEST_PACKAGE_WASI_LIB}/." "${stage}/lib/python3.14/"
		# getpath probes …/lib-dynload (isdir). Keep a marker so ustar
		# always carries the directory (empty dirs are easy to drop).
		mkdir -p "${stage}/lib/python3.14/lib-dynload"
		: >"${stage}/lib/python3.14/lib-dynload/.keep"
		"${ROOT}/scripts/lib/pack-pkg.sh" --id=python-stdlib "${stage}" \
			"${PM_GUEST_PKGS}/pkg_python_stdlib.c"
		cfiles+=("${PM_GUEST_PKGS}/pkg_python_stdlib.c")
		rm -rf "${stage}"

		stage="$(mktemp -d)"
		mkdir -p "${stage}/mods/apps"
		cp "${PM_GUEST_PACKAGE_APPS}/python.wasm" "${stage}/mods/apps/python.wasm"
		cp "${PM_GUEST_PACKAGE_APPS}/pm-test.py" "${stage}/mods/apps/pm-test.py"
		# Do NOT ship pyvenv.cfg. getpath treats any present file as an active
		# venv and rewrites prefix/exec_prefix to dirname(dirname(argv[0]))
		# (/mods) — which then probes /mods/lib and fights PYTHONHOME=/.
		"${ROOT}/scripts/lib/pack-pkg.sh" --id=mods-apps-python --dep=python-stdlib \
			"${stage}" "${PM_GUEST_PKGS}/pkg_mods_apps_python.c"
		cfiles+=("${PM_GUEST_PKGS}/pkg_mods_apps_python.c")
		rm -rf "${stage}"
	fi

	# Explicit init pulls each package .o into static-lib links (NuttX).
	{
		echo "/* Generated by guest-pkgs.sh — do not edit. */"
		echo "#include \"pymergetic/metal/mount/pkg.h\""
		for f in "${cfiles[@]+"${cfiles[@]}"}"; do
			base="$(basename "${f}" .c)"
			# pkg_mods_tests.c → mods_tests (pack-pkg SAFE_ID)
			safe="${base#pkg_}"
			echo "void pm_metal_pkg_${safe}_register(void);"
		done
		echo "void pm_metal_pkg_embed_init(void)"
		echo "{"
		echo "	static int done;"
		echo "	if (done) {"
		echo "		return;"
		echo "	}"
		echo "	done = 1;"
		for f in "${cfiles[@]+"${cfiles[@]}"}"; do
			base="$(basename "${f}" .c)"
			safe="${base#pkg_}"
			echo "	pm_metal_pkg_${safe}_register();"
		done
		echo "}"
	} >"${PM_GUEST_PKGS}/pkgs_init.c"
	cfiles+=("${PM_GUEST_PKGS}/pkgs_init.c")

	{
		echo "# Generated by guest-pkgs.sh — do not edit."
		echo "set(PM_METAL_GUEST_PKG_SOURCES"
		for f in "${cfiles[@]+"${cfiles[@]}"}"; do
			echo "	${f}"
		done
		echo ")"
	} >"${PM_GUEST_PKGS}/pkgs.cmake"

	pm_guest_pkgs_stamp_payload >"${PM_GUEST_PKGS_STAMP}"
	echo "guest-pkgs -> ${PM_GUEST_PKGS} ($((${#cfiles[@]} - 1)) packages)"
}
