#!/usr/bin/env bash
# Pack a directory into an lz4+ustar C blob that registers as a named package.
#
# Usage: pack-pkg.sh --id=<name> [--dep=<id>]... <dir> <out.c>
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ID=""
DEPS=()

while [[ $# -gt 0 ]]; do
	case "$1" in
	--id=*)
		ID="${1#--id=}"
		shift
		;;
	--dep=*)
		DEPS+=("${1#--dep=}")
		shift
		;;
	--)
		shift
		break
		;;
	-*)
		echo "unknown option: $1" >&2
		exit 1
		;;
	*)
		break
		;;
	esac
done

DIR="${1:?usage: pack-pkg.sh --id=<name> [--dep=<id>]... <dir> <out.c>}"
OUT="${2:?usage: pack-pkg.sh --id=<name> [--dep=<id>]... <dir> <out.c>}"

if [[ -z "${ID}" ]]; then
	echo "pack-pkg.sh: --id= required" >&2
	exit 1
fi
if [[ ! -d "${DIR}" ]]; then
	echo "not a directory: ${DIR}" >&2
	exit 1
fi

TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

TAR="${TMP}/image.tar"
tar --format=ustar -cf "${TAR}" -C "${DIR}" .
UNCOMPRESSED_LEN="$(wc -c <"${TAR}" | tr -d ' ')"

CC_BIN="${CC:-cc}"
COMP_C="${TMP}/lz4pack.c"
COMP_BIN="${TMP}/lz4pack"
cat >"${COMP_C}" <<'EOF'
#include <stdio.h>
#include <stdlib.h>
#include "lz4.h"
int main(void) {
	long n; unsigned char *in; int bound, out_n; unsigned char *out;
	if (fseek(stdin, 0, SEEK_END) != 0) return 1;
	n = ftell(stdin); if (n < 0 || fseek(stdin, 0, SEEK_SET) != 0) return 1;
	in = malloc((size_t)n); if (!in || fread(in, 1, (size_t)n, stdin) != (size_t)n) return 1;
	bound = LZ4_compressBound((int)n); out = malloc((size_t)bound);
	if (!out) return 1;
	out_n = LZ4_compress_default((const char *)in, (char *)out, (int)n, bound);
	if (out_n <= 0) return 1;
	if (fwrite(out, 1, (size_t)out_n, stdout) != (size_t)out_n) return 1;
	return 0;
}
EOF
"${CC_BIN}" -O2 -I "${ROOT}/external/lz4/lib" -o "${COMP_BIN}" "${COMP_C}" "${ROOT}/external/lz4/lib/lz4.c"
BLOB="${TMP}/image.tar.lz4"
"${COMP_BIN}" <"${TAR}" >"${BLOB}"

# printf (not echo): trailing newline must not become a trailing '_'.
SAFE_ID="$(printf '%s' "${ID}" | tr -c 'A-Za-z0-9_' '_')"
NDEPS="${#DEPS[@]}"

{
	echo "/* Generated by scripts/lib/pack-pkg.sh — do not edit. */"
	echo "#include \"pymergetic/metal/mount/pkg.h\""
	echo "#include <stddef.h>"
	echo "#include <stdint.h>"
	echo "static const uint8_t g_pm_metal_pkg_${SAFE_ID}_blob[] = {"
	od -An -v -tx1 "${BLOB}" | sed 's/ \([0-9a-f][0-9a-f]\)/ 0x\1,/g'
	echo "};"
	if [[ "${NDEPS}" -gt 0 ]]; then
		echo "static const char *const g_pm_metal_pkg_${SAFE_ID}_deps[] = {"
		for d in "${DEPS[@]}"; do
			echo "	\"${d}\","
		done
		echo "};"
	fi
	# Non-static register — pulled in via pkgs_init.c (NuttX static libs
	# drop constructor-only .o files under --gc-sections).
	echo "void pm_metal_pkg_${SAFE_ID}_register(void);"
	echo "void pm_metal_pkg_${SAFE_ID}_register(void)"
	echo "{"
	if [[ "${NDEPS}" -gt 0 ]]; then
		echo "	(void)pm_metal_pkg_register(\"${ID}\", g_pm_metal_pkg_${SAFE_ID}_blob,"
		echo "		sizeof(g_pm_metal_pkg_${SAFE_ID}_blob), (size_t)${UNCOMPRESSED_LEN}u,"
		echo "		PM_METAL_MOUNT_PKG_FLAG_LZ4, g_pm_metal_pkg_${SAFE_ID}_deps, ${NDEPS}u);"
	else
		echo "	(void)pm_metal_pkg_register(\"${ID}\", g_pm_metal_pkg_${SAFE_ID}_blob,"
		echo "		sizeof(g_pm_metal_pkg_${SAFE_ID}_blob), (size_t)${UNCOMPRESSED_LEN}u,"
		echo "		PM_METAL_MOUNT_PKG_FLAG_LZ4, NULL, 0u);"
	fi
	echo "}"
} >"${OUT}"

echo "pack-pkg: ${ID} ${DIR} -> ${OUT} (lz4 ustar uncomp=${UNCOMPRESSED_LEN} deps=${NDEPS})"
