#!/usr/bin/env bash
# Pack a directory tree into an embedded C array that self-registers with
# pm_metal_mount_populate_register() (Phase 4 — see docs/MOUNT.md).
#
# Usage: pack-image.sh [--lz4] <dir> <out.c>
#
# Paths inside the ustar are relative to <dir> (e.g. dir/scratch/hello.txt
# → "scratch/hello.txt"). populate_all() extracts them against guest "/"
# via the mount table. Optional --lz4 wraps the ustar in a plain LZ4 block
# (same format as util/lz4.h), compressed with the vendored lz4 library.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
USE_LZ4=0
if [ "${1:-}" = "--lz4" ]; then
	USE_LZ4=1
	shift
fi

DIR="${1:?usage: pack-image.sh [--lz4] <dir> <out.c>}"
OUT="${2:?usage: pack-image.sh [--lz4] <dir> <out.c>}"

if [ ! -d "${DIR}" ]; then
	echo "not a directory: ${DIR}" >&2
	exit 1
fi

TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

TAR="${TMP}/image.tar"
# ustar only — matches util/tar.h. Paths relative to DIR; no leading '/'.
tar --format=ustar -cf "${TAR}" -C "${DIR}" .

UNCOMPRESSED_LEN="$(wc -c < "${TAR}" | tr -d ' ')"
BLOB="${TAR}"
FLAGS=0
UNCOMP_ARG=0

if [ "${USE_LZ4}" = 1 ]; then
	# Plain LZ4 *block* (matches util/lz4.h) — not the host `lz4` CLI's
	# frame format. Compress with the vendored library.
	CC_BIN="${CC:-cc}"
	COMP_C="${TMP}/lz4pack.c"
	COMP_BIN="${TMP}/lz4pack"
	cat > "${COMP_C}" <<'EOF'
#include <stdio.h>
#include <stdlib.h>
#include "lz4.h"
int main(void) {
	long n; unsigned char *in; int bound, out_n; unsigned char *out;
	if (fseek(stdin, 0, SEEK_END) != 0) return 1;
	n = ftell(stdin); if (n < 0 || fseek(stdin, 0, SEEK_SET) != 0) return 1;
	in = malloc((size_t)n); if (!in || fread(in, 1, (size_t)n, stdin) != (size_t)n) return 1;
	bound = LZ4_compressBound((int)n); out = malloc((size_t)bound);
	if (!out) return 1;
	out_n = LZ4_compress_default((const char *)in, (char *)out, (int)n, bound);
	if (out_n <= 0) return 1;
	if (fwrite(out, 1, (size_t)out_n, stdout) != (size_t)out_n) return 1;
	return 0;
}
EOF
	"${CC_BIN}" -O2 -I "${ROOT}/external/lz4/lib" -o "${COMP_BIN}" "${COMP_C}" "${ROOT}/external/lz4/lib/lz4.c"
	BLOB="${TMP}/image.tar.lz4"
	"${COMP_BIN}" < "${TAR}" > "${BLOB}"
	FLAGS=1
	UNCOMP_ARG="${UNCOMPRESSED_LEN}"
fi

{
	echo "/* Generated by scripts/lib/pack-image.sh — do not edit. */"
	echo "#include \"pymergetic/metal/mount/populate.h\""
	echo "#include <stddef.h>"
	echo "#include <stdint.h>"
	echo "static const uint8_t g_pm_metal_mount_populate_blob[] = {"
	od -An -v -tx1 "${BLOB}" | sed 's/ \([0-9a-f][0-9a-f]\)/ 0x\1,/g'
	echo "};"
	echo "static void pm_metal_mount_populate_embed_register(void) __attribute__((constructor));"
	echo "static void pm_metal_mount_populate_embed_register(void)"
	echo "{"
	echo "	(void)pm_metal_mount_populate_register(g_pm_metal_mount_populate_blob,"
	echo "		sizeof(g_pm_metal_mount_populate_blob), (size_t)${UNCOMP_ARG}u, ${FLAGS}u);"
	echo "}"
} > "${OUT}"

if [ "${USE_LZ4}" = 1 ]; then
	echo "pack-image: ${DIR} -> ${OUT} (lz4-compressed ustar, uncompressed=${UNCOMPRESSED_LEN})"
else
	echo "pack-image: ${DIR} -> ${OUT} (ustar, uncompressed=${UNCOMPRESSED_LEN})"
fi
