#!/usr/bin/env python3
"""Pack file bytes into a generated C array. Edit the source files, not this output."""
from __future__ import annotations

import argparse
import pathlib
import sys


def emit_array(out, ident: str, data: bytes, ctype: str) -> None:
    out.write(f"static const {ctype} s_{ident}[] = {{\n")
    if not data:
        out.write("    0\n")
    else:
        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            line = ", ".join(str(b) for b in chunk)
            comma = "," if i + 16 < len(data) else ""
            out.write(f"    {line}{comma}\n")
    out.write("};\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument(
        "--str",
        nargs=2,
        metavar=("NAME", "PATH"),
        action="append",
        default=[],
        help="const char *NAME(void) + unsigned NAME_len(void)",
    )
    ap.add_argument(
        "--bytes",
        nargs=2,
        metavar=("PREFIX", "PATH"),
        action="append",
        default=[],
        help="const uint8_t *PREFIX_bytes(void) + unsigned PREFIX_size(void)",
    )
    args = ap.parse_args()
    out_path = pathlib.Path(args.output)
    chunks: list[str] = []

    def write_into() -> str:
        from io import StringIO

        buf = StringIO()
        buf.write("/* Generated by embed_bytes.py - do not edit. */\n")
        buf.write("#include <stdint.h>\n\n")
        n = 0
        for name, path in args.str:
            data = pathlib.Path(path).read_bytes()
            ident = f"str_{n}"
            n += 1
            # NUL-terminated: consumers that hand the buffer to C string APIs
            # (tcc_compile_string, printf %s) must not read past the content.
            # _len() stays the content length — the terminator is not content.
            emit_array(buf, ident, data + b"\0", "char")
            buf.write(f"const char *{name}(void) {{ return s_{ident}; }}\n")
            buf.write(f"unsigned {name}_len(void) {{ return {len(data)}u; }}\n\n")
        for prefix, path in args.bytes:
            data = pathlib.Path(path).read_bytes()
            ident = f"bin_{n}"
            n += 1
            emit_array(buf, ident, data, "uint8_t")
            buf.write(f"const uint8_t *{prefix}_bytes(void) {{ return s_{ident}; }}\n")
            buf.write(f"unsigned {prefix}_size(void) {{ return {len(data)}u; }}\n\n")
        if n == 0:
            raise SystemExit("embed_bytes.py: nothing to emit")
        return buf.getvalue()

    out_path.write_text(write_into(), encoding="ascii")
    return 0


if __name__ == "__main__":
    sys.exit(main())
