#ifndef PM_BIOS_SHIM_INDUSTRY_STANDARD_PCI_H_
#define PM_BIOS_SHIM_INDUSTRY_STANDARD_PCI_H_

#define PCI_VENDOR_ID_OFFSET 0x00
#define PCI_DEVICE_ID_OFFSET 0x02
#define PCI_COMMAND_OFFSET 0x04
#define PCI_STATUS_OFFSET 0x06
#define PCI_REVISION_ID_OFFSET 0x08
#define PCI_CLASSCODE_OFFSET 0x09
#define PCI_HEADER_TYPE_OFFSET 0x0E
#define PCI_BAR0 0x10
#define PCI_CAPBILITY_POINTER_OFFSET 0x34
#define PCI_COMMAND_MEMORY_SPACE 0x0002
#define PCI_COMMAND_BUS_MASTER 0x0004
#define HEADER_TYPE_MULTI_FUNCTION 0x80
#define EFI_PCI_CAPABILITY_ID_VENDOR 0x09

#endif /* PM_BIOS_SHIM_INDUSTRY_STANDARD_PCI_H_ */
