WIRE_IS_LE: int

def host_is_le() -> bool: ...
def load_u16_le(src: bytes | bytearray | memoryview) -> int: ...
def store_u16_le(v: int) -> bytes: ...
def load_u32_le(src: bytes | bytearray | memoryview) -> int: ...
def store_u32_le(v: int) -> bytes: ...
def load_u64_le(src: bytes | bytearray | memoryview) -> int: ...
def store_u64_le(v: int) -> bytes: ...
