def from_u32(v: int) -> int: ...
def to_u32(tag: int) -> int: ...
def from_wire_bytes(src: bytes | bytearray | memoryview) -> int: ...
def to_wire_bytes(tag: int) -> bytes: ...
def from_bytes(src: bytes | bytearray | memoryview) -> int: ...
def to_bytes(tag: int) -> bytes: ...
def from_string(s: str) -> int: ...
def to_string(tag: int) -> str: ...
def label(magic: int) -> str: ...
