def list(archive: bytes | bytearray | memoryview) -> list[tuple[str, int, bool]]: ...
def list_ex(archive: bytes | bytearray | memoryview) -> list[tuple[str, int, bool, int, int]]: ...
def pad_len(size: int) -> int: ...
def write_header(name: str | bytes | bytearray | memoryview, size: int, typeflag: int) -> bytes: ...
def write_end() -> bytes: ...
