# Autogenerated file
def render(title, about):
    # Autogenerated file
    def render1(title):
        yield """<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>"""
        yield str(title)
        yield """ - metal</title>
  <link rel=\"stylesheet\" href=\"/static/doc.css\">
</head>
<body>
<header>
  <a class=\"brand\" href=\"/\">metal</a>
  <a href=\"/about\">about</a>
  <a href=\"/docs\">docs</a>
  <a href=\"/iface\">iface</a>
  <a href=\"/iface/sym\">syms</a>
  <a href=\"/externals\">externals</a>
  <a href=\"/limits\">limits</a>
  <a href=\"/api/doc\">api/doc</a>
  <a href=\"/api/iface\">api/iface</a>
</header>
<main>
"""
    yield from render1(title)
    yield """<h1>about</h1>
<p class=\"muted\">version """
    yield str(about["version"])
    yield """</p>
"""
    if about["url"]:
        yield """<p><a href=\""""
        yield str(about["url"])
        yield """\">"""
        yield str(about["url"])
        yield """</a></p>
"""
    if about["desc"]:
        yield """<pre>"""
        yield str(about["desc"])
        yield """</pre>
"""
    yield """<h2>authors</h2>
<table>
  <tr><th>name</th><th>email</th><th>role</th></tr>
  """
    for a in about["authors"]:
        yield """  <tr>
    <td>"""
        yield str(a["name"])
        yield """</td>
    <td>"""
        yield str(a["email"])
        yield """</td>
    <td>"""
        yield str(a["role"])
        yield """</td>
  </tr>
  """
    yield """</table>
"""
# Autogenerated file
    def render2(*a, **d):
        yield """</main>
<footer>
  <p>Callable docs + header packs. JSON under <code>/api/doc</code> and <code>/api/iface</code>. See <code>docs/IFACE.md</code>.</p>
  <p class=\"muted\">Copyright 2026 Pymergetic | Rouven Raudzus &lt;raudzus@pymergetic.com&gt;. Apache License 2.0.</p>
</footer>
</body>
</html>

"""
    yield from render2()
