# Autogenerated file
def render(title):
    yield """<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>"""
    yield str(title)
    yield """ - metal</title>
  <link rel=\"stylesheet\" href=\"/static/doc.css\">
</head>
<body>
<header>
  <a class=\"brand\" href=\"/\">metal</a>
  <a href=\"/about\">about</a>
  <a href=\"/docs\">docs</a>
  <a href=\"/iface\">iface</a>
  <a href=\"/iface/sym\">syms</a>
  <a href=\"/externals\">externals</a>
  <a href=\"/limits\">limits</a>
  <a href=\"/api/doc\">api/doc</a>
  <a href=\"/api/iface\">api/iface</a>
</header>
<main>
"""
