# Autogenerated file
def render(title, kind, rows, pager):
    # Autogenerated file
    def render1(title):
        yield """<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>"""
        yield str(title)
        yield """ - metal</title>
  <link rel=\"stylesheet\" href=\"/static/doc.css\">
</head>
<body>
<header>
  <a class=\"brand\" href=\"/\">metal</a>
  <a href=\"/about\">about</a>
  <a href=\"/docs\">docs</a>
  <a href=\"/iface\">iface</a>
  <a href=\"/iface/sym\">syms</a>
  <a href=\"/externals\">externals</a>
  <a href=\"/limits\">limits</a>
  <a href=\"/api/doc\">api/doc</a>
  <a href=\"/api/iface\">api/iface</a>
</header>
<main>
"""
    yield from render1(title)
    yield """<h1>docs</h1>
<p class=\"muted\">
  Filter:
  <a href=\"/docs\">all</a> |
  <a href=\"/docs?kind=shell\">shell</a> |
  <a href=\"/docs?kind=py\">py</a> |
  <a href=\"/docs?kind=mod\">mod</a>
  """
    if kind:
        yield """ - showing <code>"""
        yield str(kind)
        yield """</code>"""
    yield """</p>
<p class=\"muted\">
  <code>shell</code> = console cmds (same text as <code>pmcmd.*</code>).
  <code>py</code> = <code>pymergetic.metal.*</code> binds plus <code>pmcmd.*</code> aliases.
  <code>mod</code> = guest <code>register_func_doc</code> (e.g. <code>doom.run</code>).
</p>
"""
# Autogenerated file
    def render2(pager):
        if pager["total"]:
            yield """<nav class=\"pager\" aria-label=\"pagination\">
  <p class=\"muted\">
    showing """
            yield str(pager["from"])
            yield """-"""
            yield str(pager["to"])
            yield """ of """
            yield str(pager["total"])
            yield """
    (page """
            yield str(pager["page"])
            yield """ / """
            yield str(pager["pages"])
            yield """, """
            yield str(pager["limit"])
            yield """ per page)
  </p>
  """
            if pager["pages"] > 1:
                yield """  <p class=\"pager-links\">
    """
                if pager["has_prev"]:
                    yield """    <a href=\""""
                    yield str(pager["first_href"])
                    yield """\">first</a>
    <a href=\""""
                    yield str(pager["prev_href"])
                    yield """\">prev</a>
    """
                else:
                    yield """    <span class=\"muted\">first</span>
    <span class=\"muted\">prev</span>
    """
                yield """    """
                if pager["has_next"]:
                    yield """    <a href=\""""
                    yield str(pager["next_href"])
                    yield """\">next</a>
    <a href=\""""
                    yield str(pager["last_href"])
                    yield """\">last</a>
    """
                else:
                    yield """    <span class=\"muted\">next</span>
    <span class=\"muted\">last</span>
    """
                yield """  </p>
  """
            yield """</nav>
"""
    yield from render2(pager)
    yield """<table>
  <tr><th>kind</th><th>key</th><th>summary</th></tr>
  """
    for r in rows:
        yield """  <tr>
    <td>"""
        yield str(r["kind"])
        yield """</td>
    <td><a href=\"/docs/"""
        yield str(r["kind"])
        yield """/"""
        yield str(r["key"])
        yield """\"><code>"""
        yield str(r["key"])
        yield """</code></a></td>
    <td>"""
        yield str(r["summary"])
        yield """</td>
  </tr>
  """
    yield """</table>
"""
# Autogenerated file
    def render3(pager):
        if pager["total"]:
            yield """<nav class=\"pager\" aria-label=\"pagination\">
  <p class=\"muted\">
    showing """
            yield str(pager["from"])
            yield """-"""
            yield str(pager["to"])
            yield """ of """
            yield str(pager["total"])
            yield """
    (page """
            yield str(pager["page"])
            yield """ / """
            yield str(pager["pages"])
            yield """, """
            yield str(pager["limit"])
            yield """ per page)
  </p>
  """
            if pager["pages"] > 1:
                yield """  <p class=\"pager-links\">
    """
                if pager["has_prev"]:
                    yield """    <a href=\""""
                    yield str(pager["first_href"])
                    yield """\">first</a>
    <a href=\""""
                    yield str(pager["prev_href"])
                    yield """\">prev</a>
    """
                else:
                    yield """    <span class=\"muted\">first</span>
    <span class=\"muted\">prev</span>
    """
                yield """    """
                if pager["has_next"]:
                    yield """    <a href=\""""
                    yield str(pager["next_href"])
                    yield """\">next</a>
    <a href=\""""
                    yield str(pager["last_href"])
                    yield """\">last</a>
    """
                else:
                    yield """    <span class=\"muted\">next</span>
    <span class=\"muted\">last</span>
    """
                yield """  </p>
  """
            yield """</nav>
"""
    yield from render3(pager)
# Autogenerated file
    def render4(*a, **d):
        yield """</main>
<footer>
  <p>Callable docs + header packs. JSON under <code>/api/doc</code> and <code>/api/iface</code>. See <code>docs/IFACE.md</code>.</p>
  <p class=\"muted\">Copyright 2026 Pymergetic | Rouven Raudzus &lt;raudzus@pymergetic.com&gt;. Apache License 2.0.</p>
</footer>
</body>
</html>

"""
    yield from render4()
