# Autogenerated file
def render(title, row):
    # Autogenerated file
    def render1(title):
        yield """<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>"""
        yield str(title)
        yield """ - metal</title>
  <link rel=\"stylesheet\" href=\"/static/doc.css\">
</head>
<body>
<header>
  <a class=\"brand\" href=\"/\">metal</a>
  <a href=\"/about\">about</a>
  <a href=\"/docs\">docs</a>
  <a href=\"/iface\">iface</a>
  <a href=\"/iface/sym\">syms</a>
  <a href=\"/externals\">externals</a>
  <a href=\"/limits\">limits</a>
  <a href=\"/api/doc\">api/doc</a>
  <a href=\"/api/iface\">api/iface</a>
</header>
<main>
"""
    yield from render1(title)
    yield """<p class=\"nav-crumbs\"><a href=\"/externals\">externals</a> / <code>"""
    yield str(row["id"])
    yield """</code></p>
<h1>"""
    yield str(row["id"])
    yield """</h1>
<p class=\"muted\">version """
    yield str(row["version"])
    yield """</p>
"""
    if row["url"]:
        yield """<p><a href=\""""
        yield str(row["url"])
        yield """\">"""
        yield str(row["url"])
        yield """</a></p>
"""
    if row["note"]:
        yield """<pre>"""
        yield str(row["note"])
        yield """</pre>
"""
# Autogenerated file
    def render2(*a, **d):
        yield """</main>
<footer>
  <p>Callable docs + header packs. JSON under <code>/api/doc</code> and <code>/api/iface</code>. See <code>docs/IFACE.md</code>.</p>
  <p class=\"muted\">Copyright 2026 Pymergetic | Rouven Raudzus &lt;raudzus@pymergetic.com&gt;. Apache License 2.0.</p>
</footer>
</body>
</html>

"""
    yield from render2()
