# Autogenerated file
def render(title, name, info, files, pkg_href):
    # Autogenerated file
    def render1(title):
        yield """<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>"""
        yield str(title)
        yield """ - metal</title>
  <link rel=\"stylesheet\" href=\"/static/doc.css\">
</head>
<body>
<header>
  <a class=\"brand\" href=\"/\">metal</a>
  <a href=\"/about\">about</a>
  <a href=\"/docs\">docs</a>
  <a href=\"/iface\">iface</a>
  <a href=\"/iface/sym\">syms</a>
  <a href=\"/externals\">externals</a>
  <a href=\"/limits\">limits</a>
  <a href=\"/api/doc\">api/doc</a>
  <a href=\"/api/iface\">api/iface</a>
</header>
<main>
"""
    yield from render1(title)
    yield """<p class=\"nav-crumbs\"><a href=\"/iface\">iface</a> / <code>"""
    yield str(name)
    yield """</code></p>
<h1>"""
    yield str(name)
    yield """</h1>
<p class=\"muted\">"""
    yield str(info["kind"])
    yield """ | version """
    yield str(info["version"])
    yield """ | """
    yield str(info["nfiles"])
    yield """ files | blob """
    yield str(info["blob_len"])
    yield """</p>
<ul>
  """
    for f in files:
        yield """  <li><a href=\""""
        yield str(f["href"])
        yield """\"><code>"""
        yield str(f["path"])
        yield """</code></a></li>
  """
    yield """</ul>
"""
# Autogenerated file
    def render2(*a, **d):
        yield """</main>
<footer>
  <p>Callable docs + header packs. JSON under <code>/api/doc</code> and <code>/api/iface</code>. See <code>docs/IFACE.md</code>.</p>
  <p class=\"muted\">Copyright 2026 Pymergetic | Rouven Raudzus &lt;raudzus@pymergetic.com&gt;. Apache License 2.0.</p>
</footer>
</body>
</html>

"""
    yield from render2()
