# Autogenerated file
def render(title, row, doc):
    # Autogenerated file
    def render1(title):
        yield """<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>"""
        yield str(title)
        yield """ - metal</title>
  <link rel=\"stylesheet\" href=\"/static/doc.css\">
</head>
<body>
<header>
  <a class=\"brand\" href=\"/\">metal</a>
  <a href=\"/about\">about</a>
  <a href=\"/docs\">docs</a>
  <a href=\"/iface\">iface</a>
  <a href=\"/iface/sym\">syms</a>
  <a href=\"/externals\">externals</a>
  <a href=\"/limits\">limits</a>
  <a href=\"/api/doc\">api/doc</a>
  <a href=\"/api/iface\">api/iface</a>
</header>
<main>
"""
    yield from render1(title)
    yield """<p class=\"nav-crumbs\"><a href=\"/iface/sym\">syms</a> / <code>"""
    yield str(row["module"])
    yield """</code> / <code>"""
    yield str(row["name"])
    yield """</code></p>
<h1>"""
    yield str(row["name"])
    yield """</h1>
<p class=\"muted\">module <code>"""
    yield str(row["module"])
    yield """</code> | sig <code>"""
    yield str(row["sig"])
    yield """</code></p>
"""
    if row["doc_key"]:
        yield """<p>doc_key <a href=\"/docs/key/"""
        yield str(row["doc_key"])
        yield """\"><code>"""
        yield str(row["doc_key"])
        yield """</code></a></p>
"""
    if doc:
        yield """<h2>linked doc</h2>
<p>"""
        yield str(doc["summary"])
        yield """</p>
"""
        if doc["sig"]:
            yield """<pre>"""
            yield str(doc["sig"])
            yield """</pre>"""
        if doc["body"]:
            yield """<pre>"""
            yield str(doc["body"])
            yield """</pre>"""
# Autogenerated file
    def render2(*a, **d):
        yield """</main>
<footer>
  <p>Callable docs + header packs. JSON under <code>/api/doc</code> and <code>/api/iface</code>. See <code>docs/IFACE.md</code>.</p>
  <p class=\"muted\">Copyright 2026 Pymergetic | Rouven Raudzus &lt;raudzus@pymergetic.com&gt;. Apache License 2.0.</p>
</footer>
</body>
</html>

"""
    yield from render2()
