# Autogenerated file
def render(title, groups):
    # Autogenerated file
    def render1(title):
        yield """<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>"""
        yield str(title)
        yield """ - metal</title>
  <link rel=\"stylesheet\" href=\"/static/doc.css\">
</head>
<body>
<header>
  <a class=\"brand\" href=\"/\">metal</a>
  <a href=\"/about\">about</a>
  <a href=\"/docs\">docs</a>
  <a href=\"/iface\">iface</a>
  <a href=\"/iface/sym\">syms</a>
  <a href=\"/externals\">externals</a>
  <a href=\"/limits\">limits</a>
  <a href=\"/api/doc\">api/doc</a>
  <a href=\"/api/iface\">api/iface</a>
</header>
<main>
"""
    yield from render1(title)
    yield """<h1>iface packages</h1>
<p class=\"muted\">Grouped by module; expand a row for packs (h, c, pyi, py, meta).</p>
"""
    for base, npacks, packs in groups:
        yield """<details class=\"iface-mod\">
  <summary>
    <code>"""
        yield str(base)
        yield """</code>
    <span class=\"muted\">"""
        yield str(npacks)
        yield """ packs</span>
  </summary>
  <table class=\"iface-packs\">
    <tr><th>name</th><th>kind</th><th>version</th><th>files</th><th>blob</th></tr>
    """
        for p in packs:
            yield """    <tr>
      <td><a href=\""""
            yield str(p["href"])
            yield """\"><code>"""
            yield str(p["name"])
            yield """</code></a></td>
      <td>"""
            yield str(p["kind"])
            yield """</td>
      <td>"""
            yield str(p["version"])
            yield """</td>
      <td>"""
            yield str(p["nfiles"])
            yield """</td>
      <td>"""
            yield str(p["blob_len"])
            yield """</td>
    </tr>
    """
        yield """  </table>
</details>
"""
# Autogenerated file
    def render2(*a, **d):
        yield """</main>
<footer>
  <p>Callable docs + header packs. JSON under <code>/api/doc</code> and <code>/api/iface</code>. See <code>docs/IFACE.md</code>.</p>
  <p class=\"muted\">Copyright 2026 Pymergetic | Rouven Raudzus &lt;raudzus@pymergetic.com&gt;. Apache License 2.0.</p>
</footer>
</body>
</html>

"""
    yield from render2()
