# Autogenerated file
def render(title, version, n_docs, n_pkgs, n_syms, n_ext, n_lim):
    # Autogenerated file
    def render1(title):
        yield """<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>"""
        yield str(title)
        yield """ - metal</title>
  <link rel=\"stylesheet\" href=\"/static/doc.css\">
</head>
<body>
<header>
  <a class=\"brand\" href=\"/\">metal</a>
  <a href=\"/about\">about</a>
  <a href=\"/docs\">docs</a>
  <a href=\"/iface\">iface</a>
  <a href=\"/iface/sym\">syms</a>
  <a href=\"/externals\">externals</a>
  <a href=\"/limits\">limits</a>
  <a href=\"/api/doc\">api/doc</a>
  <a href=\"/api/iface\">api/iface</a>
</header>
<main>
"""
    yield from render1(title)
    yield """<h1>metal</h1>
<p class=\"muted\">version """
    yield str(version)
    yield """</p>
<p>Browse the live callable-doc catalog and baked iface header packs.</p>
<ul>
  <li><a href=\"/about\">about</a> - authors + kernel identity</li>
  <li><a href=\"/docs\">docs</a> - """
    yield str(n_docs)
    yield """ entries</li>
  <li><a href=\"/iface\">iface packages</a> - """
    yield str(n_pkgs)
    yield """ packs</li>
  <li><a href=\"/iface/sym\">native symbols</a> - """
    yield str(n_syms)
    yield """ rows</li>
  <li><a href=\"/externals\">externals</a> - """
    yield str(n_ext)
    yield """ third-party records</li>
  <li><a href=\"/limits\">limits</a> - """
    yield str(n_lim)
    yield """ compile-time budgets</li>
</ul>
"""
# Autogenerated file
    def render2(*a, **d):
        yield """</main>
<footer>
  <p>Callable docs + header packs. JSON under <code>/api/doc</code> and <code>/api/iface</code>. See <code>docs/IFACE.md</code>.</p>
  <p class=\"muted\">Copyright 2026 Pymergetic | Rouven Raudzus &lt;raudzus@pymergetic.com&gt;. Apache License 2.0.</p>
</footer>
</body>
</html>

"""
    yield from render2()
