# Autogenerated file
def render(pager):
    if pager["total"]:
        yield """<nav class=\"pager\" aria-label=\"pagination\">
  <p class=\"muted\">
    showing """
        yield str(pager["from"])
        yield """-"""
        yield str(pager["to"])
        yield """ of """
        yield str(pager["total"])
        yield """
    (page """
        yield str(pager["page"])
        yield """ / """
        yield str(pager["pages"])
        yield """, """
        yield str(pager["limit"])
        yield """ per page)
  </p>
  """
        if pager["pages"] > 1:
            yield """  <p class=\"pager-links\">
    """
            if pager["has_prev"]:
                yield """    <a href=\""""
                yield str(pager["first_href"])
                yield """\">first</a>
    <a href=\""""
                yield str(pager["prev_href"])
                yield """\">prev</a>
    """
            else:
                yield """    <span class=\"muted\">first</span>
    <span class=\"muted\">prev</span>
    """
            yield """    """
            if pager["has_next"]:
                yield """    <a href=\""""
                yield str(pager["next_href"])
                yield """\">next</a>
    <a href=\""""
                yield str(pager["last_href"])
                yield """\">last</a>
    """
            else:
                yield """    <span class=\"muted\">next</span>
    <span class=\"muted\">last</span>
    """
            yield """  </p>
  """
        yield """</nav>
"""
