"""Typing face (matrix Py count = max(glue,.pyi))."""

def init_from_bind(*args, **kwargs): ...
def init(*args, **kwargs): ...
def fini(*args, **kwargs): ...
def ready(*args, **kwargs): ...
def surface(*args, **kwargs): ...
def scanout_name(*args, **kwargs): ...
def clear(*args, **kwargs): ...
def fill_rect(*args, **kwargs): ...
def present_rect(*args, **kwargs): ...
def present(*args, **kwargs): ...
