"""pymergetic.metal.dev.gfx.scanout — µPy face over C scanout."""

def bind(bind_cookie: int) -> int: ...
def ops() -> int: ...
def name() -> str | None: ...
def caps() -> int: ...
def fini() -> None: ...
def bind_info() -> int: ...
def bind_set_shadow(pixels: int, pitch: int) -> None: ...
def copy_rect(dst: int, dst_pitch: int, x: int, y: int, w: int, h: int, bind_cookie: int) -> None: ...
