def format_buf(buf: bytearray | memoryview) -> int: ...
def open_buf(buf: bytearray | memoryview) -> int: ...
def close(vol: int) -> int: ...
def mount(target: str, buf: bytearray | memoryview) -> int: ...
def seed_simple(
    buf: bytearray | memoryview, files: list[tuple[str, bytes | bytearray | memoryview]]
) -> int: ...
def mount_ram(target: str, ram_h: int) -> int: ...
