def open_blob(blob: bytes | bytearray | memoryview) -> int: ...
def open_owned(blob: bytes | bytearray | memoryview, cap: int) -> int: ...
def mount(target: str, blob: bytes | bytearray | memoryview) -> int: ...
def mount_rw(target: str, blob: bytearray | memoryview, cap: int) -> int: ...
def empty(cap: int) -> bytes: ...
def pack_simple(files: list[tuple[str, bytes | bytearray | memoryview]], cap: int) -> bytes: ...
