def mount(target: str, ops: int, ctx: int) -> int: ...
def umount(target: str) -> int: ...
def mount_count() -> int: ...
def mount_info(index: int) -> tuple[str, str]: ...
def mount_get(index: int) -> tuple[int, int]: ...
def resolve(path: str) -> tuple[int, int, str | None, int]: ...
