def open_blob(blob: bytes | bytearray | memoryview) -> int: ...
def mount(target: str, blob: bytes | bytearray | memoryview) -> int: ...
def pack_simple(files: list[tuple[str, bytes | bytearray | memoryview]], cap: int) -> bytes: ...
def empty(cap: int) -> bytes: ...
