#!/usr/bin/env bash
# Build mods and embed a Zephyr verify set as C arrays.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="${ROOT}/src/zephyr/generated"
OUT_C="${OUT_DIR}/mods_embed.c"
OUT_H="${OUT_DIR}/mods_embed.h"

"${ROOT}/scripts/build-mod.sh"

mkdir -p "${OUT_DIR}"

# name -> wasm basename (without .wasm)
MODS=(
	t0_hello
	t1_read
	t12_tmpfs_write
	t13_tmpfs_read
	t14_tmpfs_read_alt
	t15_tmpfs_read_other
	t16_populate_read
	t21_proc_mounts
	t8_multimod_lib
	t9_multimod_app
	t4_getpid
	t5_spin
)

for m in "${MODS[@]}"; do
	if [[ ! -f "${ROOT}/build/mods/${m}.wasm" ]]; then
		echo "missing build/mods/${m}.wasm" >&2
		exit 1
	fi
done

{
	echo '/* Auto-generated by scripts/gen-zephyr-mods-embed.sh — do not edit. */'
	echo '#ifndef PM_METAL_MODS_EMBED_H_'
	echo '#define PM_METAL_MODS_EMBED_H_'
	echo '#include <stdint.h>'
	for m in "${MODS[@]}"; do
		sym="${m}"
		echo "extern const uint8_t pm_metal_embed_${sym}[];"
		echo "extern const uint32_t pm_metal_embed_${sym}_len;"
	done
	echo '#endif'
} >"${OUT_H}"

{
	echo '/* Auto-generated by scripts/gen-zephyr-mods-embed.sh — do not edit. */'
	echo '#include "generated/mods_embed.h"'
	echo
	for m in "${MODS[@]}"; do
		sym="${m}"
		echo "const uint8_t pm_metal_embed_${sym}[] = {"
		xxd -i <"${ROOT}/build/mods/${m}.wasm" | sed 's/^/	/'
		echo '};'
		echo "const uint32_t pm_metal_embed_${sym}_len = sizeof(pm_metal_embed_${sym});"
		echo
	done
} >"${OUT_C}"

# Tiny populate fixture: scratch/hello.txt → ustar embed with constructor.
FIXTURE="$(mktemp -d)"
trap 'rm -rf "${FIXTURE}"' EXIT
mkdir -p "${FIXTURE}/scratch"
printf 'hello from populate\n' >"${FIXTURE}/scratch/hello.txt"
"${ROOT}/scripts/pack-image.sh" "${FIXTURE}" "${OUT_DIR}/populate_embed.c"

echo "wrote ${OUT_C}"
echo "wrote ${OUT_DIR}/populate_embed.c"
