#!/usr/bin/env python3
"""Emit a naked MPWP v3 pack (uncompressed files) + optional C embed TU."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def u16(n: int) -> bytes:
    return int(n).to_bytes(2, "little")


def u32(n: int) -> bytes:
    return int(n).to_bytes(4, "little")


def build_mpwp(name: str, files: list[tuple[str, bytes]], kind: int = 3) -> bytes:
    """kind 3 = raw (MP_PACK_KIND_RAW)."""
    out = bytearray()
    out += b"MPWP"
    out += u16(3)  # version
    out += u16(0)  # flags
    nb = name.encode("utf-8")
    out += u16(len(nb))
    out += nb
    out += u32(len(files))
    for rel, data in files:
        pb = rel.encode("utf-8")
        out += u16(len(pb))
        out += pb
        out += bytes([kind])  # kind
        out += bytes([0])  # flags (no zlib)
        out += u32(len(data))  # raw_len
        out += u32(len(data))  # data_len
        out += data
    out += u32(0)  # n_exports
    return bytes(out)


def collect_tree(root: Path, prefix: str = "") -> list[tuple[str, bytes]]:
    files: list[tuple[str, bytes]] = []
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(root).as_posix()
        if prefix:
            rel = f"{prefix.rstrip('/')}/{rel}"
        files.append((rel, p.read_bytes()))
    return files


def emit_c(path: Path, symbol: str, data: bytes) -> None:
    lines = [
        "/* AUTO-GENERATED by gen_mpwp_pack.py — do not edit. */",
        "#include <stdint.h>",
        "",
        f"const uint8_t {symbol}[] = {{",
    ]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        lines.append(f"  {chunk},")
    lines.append("};")
    lines.append(f"const unsigned {symbol}_len = {len(data)}u;")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True, help="MPWP package name (FQN)")
    ap.add_argument("--dir", type=Path, action="append", default=[], help="dir to pack (repeatable)")
    ap.add_argument(
        "--prefix",
        action="append",
        default=[],
        help="path prefix for corresponding --dir",
    )
    ap.add_argument("--file", action="append", default=[], help="extra file as rel=path")
    ap.add_argument("--out-mpwp", type=Path, required=True)
    ap.add_argument("--out-c", type=Path)
    ap.add_argument("--symbol", default="pm_metal_pack_blob")
    ap.add_argument("--meta-json", type=Path, help="optional meta/package.json body path")
    args = ap.parse_args()

    files: list[tuple[str, bytes]] = []
    prefixes = list(args.prefix)
    while len(prefixes) < len(args.dir):
        prefixes.append("")
    for d, pref in zip(args.dir, prefixes):
        if not d.is_dir():
            raise SystemExit(f"not a dir: {d}")
        files.extend(collect_tree(d, pref))
    for spec in args.file:
        if "=" not in spec:
            raise SystemExit(f"--file wants rel=path, got {spec}")
        rel, p = spec.split("=", 1)
        files.append((rel, Path(p).read_bytes()))
    if args.meta_json:
        meta = {
            "name": args.name,
            "org": "pymergetic",
        }
        if args.meta_json.is_file():
            meta.update(json.loads(args.meta_json.read_text(encoding="utf-8")))
        else:
            meta.update(json.loads(args.meta_json.read_text(encoding="utf-8")) if False else {})
        # allow inline json via --meta-json @- style: if path missing, treat as json string
        files.append(
            (
                "meta/package.json",
                (json.dumps(meta, indent=2) + "\n").encode("utf-8"),
            )
        )

    # de-dup by path (last wins)
    by: dict[str, bytes] = {}
    for rel, data in files:
        by[rel] = data
    ordered = sorted(by.items(), key=lambda x: x[0])
    blob = build_mpwp(args.name, ordered)
    args.out_mpwp.parent.mkdir(parents=True, exist_ok=True)
    args.out_mpwp.write_bytes(blob)
    if args.out_c:
        args.out_c.parent.mkdir(parents=True, exist_ok=True)
        emit_c(args.out_c, args.symbol, blob)
    print(f"wrote {args.out_mpwp} ({len(blob)} bytes, {len(ordered)} files, name={args.name})")


if __name__ == "__main__":
    main()
