#!/usr/bin/env python3
"""
Generate typings/**.pyi from the C source of truth instead of hand-editing
stubs that drift — Phase 2e (docs/MICROPYTHON.md, docs/TODO.md).

Three sources, three outputs:

  pymergetic.metal.*  <- PM_METAL_PY_BIND(var, "mod.str", "name_str", fn_obj,
                          class_) call sites across src/pymergetic/metal/**.
                          One nested .pyi per dotted module, one
                          "def name(*args) -> ...:" per row.

  pmcmd.*             <- PM_METAL_SHELL_CMD(var, name_str, help_str, fn_) and
                          PM_METAL_SHELL_CMDS(arr) = { {name, help, fn}, ... }
                          call sites across src/pymergetic/metal/**. One
                          typings/pmcmd.pyi, help_str as each def's docstring.

  pymergetic.metal.mod.*  <- pm_metal_mod_register_func(name, export_name)
                          call sites inside each in-tree mod's own source
                          under mods/**, grouped by owning mod (best-effort:
                          the mod's directory name is used as a stand-in for
                          its runtime-registered name, which is usually but
                          not always identical — e.g. build_one's alias in
                          scripts/build.d/port/efi/embed-mods.sh can rename
                          t0_hello's directory to "hello". Mods loaded later
                          at runtime and not present in mods/** at build time
                          get no stub at all — documented limitation, not a
                          bug, same as the pmcmd fallback below).

Every generated file keeps a `def __getattr__(name) -> Any: ...` (or a
class-level equivalent) fallback so anything this static scan missed still
type-checks as Any instead of erroring.

Usage: scripts/gen_py_stubs.py [--check]
  --check   Exit 1 if regenerating would change any file (CI/pre-commit use;
            does not itself write anything in that case... actually it does
            write, then diffs — see main()). Prints changed paths either way.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_METAL = ROOT / "src" / "pymergetic" / "metal"
MODS_DIR = ROOT / "mods"
TYPINGS = ROOT / "typings"

HEADER = "# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)\n"

PY_BIND_RE = re.compile(
    r'PM_METAL_PY_BIND\s*\(\s*'
    r'(?P<var>[A-Za-z_]\w*)\s*,\s*'
    r'"(?P<mod>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'"(?P<name>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'(?P<fn_obj>[A-Za-z_]\w*)\s*,\s*'
    r'(?P<class_>PM_METAL_PY_\w+)\s*\)',
    re.MULTILINE,
)

SHELL_CMD_RE = re.compile(
    r'PM_METAL_SHELL_CMD\s*\(\s*[A-Za-z_]\w*\s*,\s*'
    r'"(?P<name>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'"(?P<help>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'[A-Za-z_]\w*\s*\)',
    re.MULTILINE,
)

SHELL_CMDS_TABLE_RE = re.compile(
    r'PM_METAL_SHELL_CMDS\s*\(\s*(?P<arr>[A-Za-z_]\w*)\s*\)\s*=\s*\{(?P<body>.*?)\}\s*;\s*'
    r'PM_METAL_SHELL_CMDS_END\s*\(\s*(?P=arr)\s*\)',
    re.DOTALL,
)

SHELL_CMDS_ROW_RE = re.compile(
    r'\{\s*"(?P<name>(?:[^"\\]|\\.)*)"\s*,\s*"(?P<help>(?:[^"\\]|\\.)*)"\s*,\s*[A-Za-z_]\w*\s*\}'
)

MOD_REGISTER_FUNC_RE = re.compile(
    r'pm_metal_mod_register_func\s*\(\s*'
    r'"(?P<name>(?:[^"\\]|\\.)*)"\s*,\s*'
    r'"(?P<export>(?:[^"\\]|\\.)*)"\s*\)'
)


def unescape(s: str) -> str:
    return s.replace('\\"', '"').replace("\\\\", "\\")


def iter_c_files(root: Path):
    yield from sorted(root.rglob("*.c"))


def is_ident(name: str) -> bool:
    return bool(re.match(r"^[A-Za-z_]\w*$", name)) and name not in (
        "class", "def", "import", "from", "global", "lambda", "return",
        "yield", "raise", "assert", "pass", "async", "await",
    )


# --- pymergetic.metal.* (PM_METAL_PY_BIND) ---

def scan_py_binds():
    by_mod = {}
    for f in iter_c_files(SRC_METAL):
        text = f.read_text(errors="replace")
        for m in PY_BIND_RE.finditer(text):
            mod = unescape(m.group("mod"))
            name = unescape(m.group("name"))
            class_ = m.group("class_")
            by_mod.setdefault(mod, []).append((name, class_, f.relative_to(ROOT)))
    return by_mod


def mod_dotted_to_path(mod: str) -> Path:
    parts = mod.split(".")
    return TYPINGS.joinpath(*parts).with_suffix(".pyi") if parts[-1] != "" else TYPINGS


def render_py_bind_module(mod: str, rows) -> str:
    lines = [HEADER, '"""', f"``{mod}`` — generated from PM_METAL_PY_BIND call sites.", "", "Sources:"]
    seen_files = sorted({str(r[2]) for r in rows})
    for sf in seen_files:
        lines.append(f"  {sf}")
    lines.append('"""')
    lines.append("")
    lines.append("from typing import Any")
    lines.append("")
    for name, class_, _src in sorted(rows, key=lambda r: r[0]):
        if not is_ident(name.rstrip("_")) and not is_ident(name):
            continue
        # class_ (PM_METAL_PY_SYNC/ASYNC/FACADE) describes the C-side install,
        # not the Python-visible return shape (e.g. a SYNC bind can still
        # return an awaitable object, like aio.sleep_us) — noted, not typed.
        lines.append(f"def {name}(*args: Any) -> Any:")
        lines.append(f'    """C bind: {class_}."""')
        lines.append("    ...")
        lines.append("")
    lines.append("def __getattr__(name: str) -> Any: ...")
    lines.append("")
    return "\n".join(lines)


# --- pmcmd.* (PM_METAL_SHELL_CMD / PM_METAL_SHELL_CMDS) ---

def scan_shell_cmds():
    rows = []
    for f in iter_c_files(SRC_METAL):
        text = f.read_text(errors="replace")
        for m in SHELL_CMD_RE.finditer(text):
            rows.append((unescape(m.group("name")), unescape(m.group("help"))))
        for tm in SHELL_CMDS_TABLE_RE.finditer(text):
            for m in SHELL_CMDS_ROW_RE.finditer(tm.group("body")):
                rows.append((unescape(m.group("name")), unescape(m.group("help"))))
    return rows


def render_pmcmd(rows) -> str:
    lines = [
        HEADER,
        '"""',
        "``pmcmd`` — every registered shell command as a real attribute.",
        "",
        "Generated from PM_METAL_SHELL_CMD / PM_METAL_SHELL_CMDS call sites under",
        "src/pymergetic/metal/**. Deliberately the one module that does NOT carry",
        "the ``pymergetic.metal.*`` prefix — see docs/MICROPYTHON.md.",
        "",
        "Mod-registered commands (pm_metal_mod_register_cmd, runtime-only — a mod's",
        "on_load must actually run before they exist) are NOT covered by this static",
        "scan; they still work at runtime via __getattr__ below, just without a",
        "named stub.",
        '"""',
        "",
        "from typing import Any",
        "",
    ]
    seen = set()
    for name, help_ in sorted(rows, key=lambda r: r[0]):
        if name in seen or not is_ident(name):
            continue
        seen.add(name)
        lines.append(f"def {name}(*args: Any) -> Any:")
        doc = help_.replace('"""', "'''") or name
        lines.append(f'    """{doc}"""')
        lines.append("    ...")
        lines.append("")
    lines.append("def __getattr__(name: str) -> Any: ...")
    lines.append("")
    return "\n".join(lines)


# --- pymergetic.metal.mod.* (pm_metal_mod_register_func, best-effort) ---

def scan_mod_funcs():
    by_mod = {}
    if not MODS_DIR.is_dir():
        return by_mod
    for f in iter_c_files(MODS_DIR):
        text = f.read_text(errors="replace")
        funcs = [unescape(m.group("name")) for m in MOD_REGISTER_FUNC_RE.finditer(text)]
        if not funcs:
            continue
        mod_name = f.parent.name
        by_mod.setdefault(mod_name, set()).update(funcs)
    return by_mod


def render_mod_module(by_mod) -> str:
    lines = [
        HEADER,
        '"""',
        "``pymergetic.metal.mod`` — ``mod.<name>.<func>()`` real attribute access",
        "over the mod registry (docs/MODS.md), plus ``mod.<name>.fresh()`` for a",
        "private FRESH-mode instance (Phase 2d).",
        "",
        "Best-effort generated from pm_metal_mod_register_func(...) call sites",
        "under mods/**, grouped by the mod's own source directory name — usually",
        "but not always identical to its runtime-registered name (some mods are",
        "aliased at embed time, e.g. scripts/build.d/port/efi/embed-mods.sh's",
        "t0_hello -> \"hello\"). Mods loaded later at runtime and not present in",
        "mods/** at build time get no stub — use the module-level __getattr__",
        "fallback, which always works (real attribute access, not string dispatch,",
        "at runtime — this is purely a static-analysis gap).",
        '"""',
        "",
        "from typing import Any, Awaitable",
        "",
    ]
    for mod_name in sorted(by_mod):
        funcs = sorted(by_mod[mod_name])
        if not is_ident(mod_name):
            continue
        scope_cls = f"_ModFresh_{mod_name}"
        mod_cls = f"_Mod_{mod_name}"
        lines.append(f"class {scope_cls}:")
        lines.append(f'    """Fresh-instance scope for "{mod_name}" (async with)."""')
        lines.append("")
        lines.append(f"    async def __aenter__(self) -> \"{scope_cls}\": ...")
        lines.append("    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> bool: ...")
        for fn in funcs:
            if is_ident(fn):
                lines.append(f"    def {fn}(self, *args: Any) -> Awaitable[Any]: ...")
        lines.append("")
        lines.append(f"class {mod_cls}:")
        for fn in funcs:
            if is_ident(fn):
                lines.append(f"    def {fn}(self, *args: Any) -> Awaitable[Any]: ...")
        lines.append(f"    def fresh(self) -> {scope_cls}: ...")
        lines.append("")
        lines.append(f"{mod_name}: {mod_cls}")
        lines.append("")
    lines.append("def __getattr__(name: str) -> Any: ...")
    lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text() if path.exists() else None
    if old == content:
        return False
    path.write_text(content)
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if any output would change")
    args = ap.parse_args()

    changed = []

    by_mod_binds = scan_py_binds()
    for mod, rows in by_mod_binds.items():
        out = mod_dotted_to_path(mod)
        if write_if_changed(out, render_py_bind_module(mod, rows)):
            changed.append(out)

    cmd_rows = scan_shell_cmds()
    pmcmd_out = TYPINGS / "pmcmd.pyi"
    if write_if_changed(pmcmd_out, render_pmcmd(cmd_rows)):
        changed.append(pmcmd_out)

    mod_funcs = scan_mod_funcs()
    mod_out = TYPINGS / "pymergetic" / "metal" / "mod.pyi"
    if write_if_changed(mod_out, render_mod_module(mod_funcs)):
        changed.append(mod_out)

    n_binds = sum(len(v) for v in by_mod_binds.values())
    print(
        f"gen_py_stubs: {len(by_mod_binds)} py-bind modules ({n_binds} rows), "
        f"{len(cmd_rows)} shell cmds, {len(mod_funcs)} mods with registered funcs"
    )
    for c in changed:
        print(f"gen_py_stubs: wrote {c.relative_to(ROOT)}")

    if args.check and changed:
        print("gen_py_stubs: --check found stale stubs (regenerated above)", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
