#!/usr/bin/env bash
# Generate build/pm_metal_version.inc.h from git describe (see docs/DOC_IFACE_PLAN.md Part P).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/build/pm_metal_version.inc.h"
mkdir -p "${ROOT}/build"

ver="$(git -C "${ROOT}" describe --tags --dirty --always 2>/dev/null || true)"
if [[ -z "${ver}" ]]; then
	ver="0.0.0-unknown"
fi
# Keep leading v if present (git tags); untagged short hashes stay as-is.
# Escape for C string.
ver_c="${ver//\\/\\\\}"
ver_c="${ver_c//\"/\\\"}"

tmp="${OUT}.tmp.$$"
cat >"${tmp}" <<EOF
/* Generated by scripts/gen_metal_version.sh — do not edit. */
#ifndef PM_METAL_VERSION_INC_H_
#define PM_METAL_VERSION_INC_H_
#define PM_METAL_VERSION "${ver_c}"
#endif
EOF
if [[ ! -f "${OUT}" ]] || ! cmp -s "${tmp}" "${OUT}"; then
	mv "${tmp}" "${OUT}"
	echo "gen_metal_version: ${ver}"
else
	rm -f "${tmp}"
fi
