def read32(bus: int, dev: int, func: int, offset: int) -> int: ...
def read16(bus: int, dev: int, func: int, offset: int) -> int: ...
def read8(bus: int, dev: int, func: int, offset: int) -> int: ...
def write16(bus: int, dev: int, func: int, offset: int, val: int) -> None: ...
def write32(bus: int, dev: int, func: int, offset: int, val: int) -> None: ...
def enable_mem_bm(bus: int, dev: int, func: int) -> None: ...
def bar_mmio(bus: int, dev: int, func: int, bar_index: int) -> tuple[int, int]: ...
def find(vendor: int, device: int) -> tuple[int, int, int] | None: ...
