"""Auto face stubs."""
from typing import Any

def virtio_pages_free(*args: Any, **kwargs: Any) -> Any: ...

def virtio_open(*args: Any, **kwargs: Any) -> Any: ...

def virtio_close(*args: Any, **kwargs: Any) -> Any: ...

def virtio_get_features(*args: Any, **kwargs: Any) -> Any: ...

def virtio_set_features(*args: Any, **kwargs: Any) -> Any: ...

def virtio_set_status(*args: Any, **kwargs: Any) -> Any: ...

def virtio_get_status(*args: Any, **kwargs: Any) -> Any: ...

def virtio_setup_queue(*args: Any, **kwargs: Any) -> Any: ...

def virtio_driver_ok(*args: Any, **kwargs: Any) -> Any: ...

def virtq_kick(*args: Any, **kwargs: Any) -> Any: ...

def virtq_get_used(*args: Any, **kwargs: Any) -> Any: ...

def virtq_free_chain(*args: Any, **kwargs: Any) -> Any: ...
