#!/usr/bin/env python3
"""Generate static_embed.c from inspect/www + httpd.json mount table."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
METAL = ROOT.parent
WWW = METAL / "inspect" / "www" / "inspect"
HTTPD = METAL / "httpd.json"
OUT_C = ROOT / "static_embed.c"

CTYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
}


def ctype_for(path: Path) -> str:
    return CTYPES.get(path.suffix.lower(), "application/octet-stream")


def c_bytes(data: bytes, name: str) -> str:
    lines = [f"static const uint8_t {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        lines.append(f"  {chunk},")
    lines.append("};")
    return "\n".join(lines)


def load_mounts() -> list[tuple[str, str, str]]:
    cfg = json.loads(HTTPD.read_text(encoding="utf-8"))
    out = []
    for m in cfg.get("static") or []:
        url = (m.get("url") or "").rstrip("/") or "/inspect"
        root = (m.get("root") or "").rstrip("/") or (
            "/mods/pymergetic.metal.inspect/www/inspect"
        )
        theme = m.get("theme") or "metal"
        out.append((url, root, theme))
    if not out:
        out.append(
            (
                "/inspect",
                "/mods/pymergetic.metal.inspect/www/inspect",
                "metal",
            )
        )
    return out


def main() -> None:
    files = sorted(p for p in WWW.rglob("*") if p.is_file())
    if not files:
        raise SystemExit(f"no files under {WWW}")
    mounts = load_mounts()

    parts = [
        "/* AUTO-GENERATED by gen_static_embed.py — do not edit. */",
        '#include "static_embed.h"',
        "",
        "#include <string.h>",
        "",
    ]
    entries = []
    for i, path in enumerate(files):
        rel = path.relative_to(WWW).as_posix()
        data = path.read_bytes()
        arr = f"k_file_{i}"
        parts.append(c_bytes(data, arr))
        parts.append("")
        entries.append((rel, ctype_for(path), arr, len(data)))

    httpd_data = HTTPD.read_bytes()
    parts.append(c_bytes(httpd_data, "k_httpd_json"))
    parts.append("")
    entries.append(("httpd.json", "application/json", "k_httpd_json", len(httpd_data)))

    parts.append("const pm_metal_asgi_static_file_t pm_metal_asgi_static_files[] = {")
    for rel, ctype, arr, n in entries:
        parts.append(f'  {{ "{rel}", "{ctype}", {arr}, {n}u }},')
    parts.append("};")
    parts.append(
        f"const unsigned pm_metal_asgi_static_file_count = {len(entries)}u;"
    )
    parts.append("")
    parts.append("const pm_metal_asgi_mount_t pm_metal_asgi_mounts[] = {")
    for url, root, theme in mounts:
        parts.append(f'  {{ "{url}", "{root}", "{theme}" }},')
    parts.append("};")
    parts.append(f"const unsigned pm_metal_asgi_mount_count = {len(mounts)}u;")
    parts.append("")
    parts.append(
        """const pm_metal_asgi_static_file_t *pm_metal_asgi_static_lookup(const char *rel_path)
{
    const char *p = rel_path ? rel_path : "";
    unsigned i;

    while (*p == '/') {
        p++;
    }
    if (*p == 0) {
        p = "index.html";
    }
    for (i = 0; i < pm_metal_asgi_static_file_count; i++) {
        if (strcmp(pm_metal_asgi_static_files[i].path, p) == 0) {
            return &pm_metal_asgi_static_files[i];
        }
    }
    return 0;
}
"""
    )
    OUT_C.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(
        f"wrote {OUT_C} ({len(files)} www + httpd.json, "
        f"{sum(e[3] for e in entries)} bytes, {len(mounts)} mounts)"
    )


if __name__ == "__main__":
    main()
