//! Stage generated faces into OUT_DIR so rust-analyzer can resolve them.
//! `include/` is gitignored; RA skips gitignored `#[path]` targets.
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let pkg = manifest
        .join("../../../../../../")
        .canonicalize()
        .expect("package root from audio/.pm");
    let dst_dir = out.join("faces");
    fs::create_dir_all(&dst_dir).expect("OUT_DIR/faces");

    let mut mods = String::from("/* GENERATED by audio/.pm/build.rs - do not edit. */\n");

    for (mod_name, rel) in [
        ("log_face", "include/pymergetic/metal/log/__init__.rs"),
        ("async_handle_face", "include/pymergetic/metal/async/handle.rs"),
    ] {
        let src = pkg.join(rel);
        println!("cargo:rerun-if-changed={}", src.display());
        let file_name = src.file_name().unwrap().to_string_lossy();
        let dst = dst_dir.join(format!("{mod_name}_{file_name}"));
        fs::copy(&src, &dst).unwrap_or_else(|e| {
            panic!(
                "copy {} -> {}: {} (run: ./forge-cli mod sync)",
                src.display(),
                dst.display(),
                e
            )
        });
        let abs = dst.canonicalize().unwrap_or(dst);
        let path = abs.to_string_lossy().replace('\\', "/").replace('"', "\\\"");
        mods.push_str(&format!("#[path = \"{path}\"]\nmod {mod_name};\n"));
    }

    fs::write(out.join("face_mods.rs"), mods).expect("write face_mods.rs");
}
