[package]
name = "pymergetic_metal_dev_audio"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
path = "../_impl/__init__.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
pymergetic_metal_reg = { path = "../../../reg/.pm" }
pymergetic_metal_rt = { path = "../../../rt/.pm" }

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
