from collections.abc import Callable

def init() -> int: ...
def ready() -> int: ...
def set_fn_callback(cb: Callable[[int], object] | None) -> None: ...
def feed_scancode(scancode: int) -> None: ...
def poll() -> None: ...
