#!/usr/bin/env python3
"""Pack inspect/www files into a C include. Edit the files under www/, not the output."""
from __future__ import annotations

import argparse
import pathlib
import re
import sys


def ident(rel: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "_", rel).strip("_")
    return "www_" + (s if s else "root")


def emit_array(out, name: str, data: bytes) -> None:
    out.write(f"static const uint8_t s_{name}[] = {{\n")
    if not data:
        out.write("    0\n")
    else:
        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            line = ", ".join(str(b) for b in chunk)
            comma = "," if i + 16 < len(data) else ""
            out.write(f"    {line}{comma}\n")
    out.write("};\n\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("www", type=pathlib.Path, help="inspect/www directory")
    args = ap.parse_args()
    root = args.www.resolve()
    if not root.is_dir():
        print(f"embed_www: no www at {root}", file=sys.stderr)
        return 1
    files = sorted(p for p in root.rglob("*") if p.is_file())
    if not files:
        print(f"embed_www: empty {root}", file=sys.stderr)
        return 1
    from io import StringIO

    buf = StringIO()
    buf.write("/* Generated by tools/embed_www.py - edit www/, not this file. */\n\n")
    mounts: list[tuple[str, str, int]] = []
    for path in files:
        rel = path.relative_to(root).as_posix()
        url = "/" + rel
        name = ident(rel)
        data = path.read_bytes()
        emit_array(buf, name, data)
        mounts.append((url, name, len(data)))
    buf.write("static int32_t inspect_www_mount(void) {\n")
    for url, name, n in mounts:
        buf.write(
            f'    if (pm_metal_net_http_asgi_route_static("{url}", s_{name}, {n}u) != 0) {{\n'
            f"        return -1;\n"
            f"    }}\n"
        )
    buf.write("    return 0;\n}\n")
    text = buf.getvalue()
    out = pathlib.Path(args.output)
    if out.is_file() and out.read_text(encoding="utf-8") == text:
        return 0
    out.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
