#!/usr/bin/env python3
"""Pack inspect/www files into a C include. Edit the files under www/, not the output."""
from __future__ import annotations

import argparse
import pathlib
import re
import sys


def render_pages(module_names, template_dir):
    """Render the seat's own pages from the card FQN ledger.

    One UI, three views, all from the very templates the CDN serves (home.html +
    shell.html synced into www/, plus the seat-only reg.html / factory.html):
    `/` is the CDN-catalog browse view ("the box is a CDN of its own cards"),
    `/reg` is the live registry console and `/factory` the build card's floor.
    `module_names` is the card FQN ledger from the build; every live number on a
    seat page is fetched by its page script from this seat's JSON API, so the
    HTML is static bytes on every seat and per-module detail stays the live
    `/inspect/reg/<fqn>` RPC. Templates remain the one UI source.

    Returns a list of (url, html) in mount order.
    """
    import pymergetic.metal.inspect.catalog_render as cr

    registry = {
        "modules": lambda: module_names,
        "export_count": lambda f: 0,
    }
    engine = cr.Engine(template_dir)
    # The seat renders /packs/<fqn> at runtime from the compiled template, so
    # compile it here even though this build step never renders a package page.
    engine.compile("package.html")
    return [
        ("/", cr.render_home(registry, engine=engine)),
        ("/reg", cr.render_reg(registry, engine=engine)),
        ("/factory", cr.render_factory(registry, engine=engine)),
    ]


def ident(rel: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "_", rel).strip("_")
    return "www_" + (s if s else "root")


def emit_array(out, name: str, data: bytes) -> None:
    out.write(f"static const uint8_t s_{name}[] = {{\n")
    if not data:
        out.write("    0\n")
    else:
        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            line = ", ".join(str(b) for b in chunk)
            comma = "," if i + 16 < len(data) else ""
            out.write(f"    {line}{comma}\n")
    out.write("};\n\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("www", type=pathlib.Path, help="inspect/www directory")
    ap.add_argument(
        "--render-pages",
        default="",
        help="render the seat's pages ('/', '/reg', '/factory') from these card "
        "FQNs (space/comma separated)",
    )
    args = ap.parse_args()
    root = args.www.resolve()
    if not root.is_dir():
        print(f"embed_www: no www at {root}", file=sys.stderr)
        return 1
    files = sorted(
        p
        for p in root.rglob("*")
        if p.is_file()
        # Skip VCS/tooling dotfiles (.gitignore, _compiled/, __pycache__): those
        # are build/bookkeeping artifacts, never served www assets.
        and not p.name.startswith(".")
        and not any(part in ("_compiled", "__pycache__") for part in p.parts)
        # The www root holds the templates. They are rendered here (or compiled
        # for the seat's runtime render), never served as source — a raw
        # "{% args d %}" body at /shell.html is not an asset.
        and not (p.parent == root and p.suffix == ".html")
    )
    if not files:
        print(f"embed_www: empty {root}", file=sys.stderr)
        return 1
    from io import StringIO

    buf = StringIO()
    buf.write("/* Generated by tools/embed_www.py - edit www/, not this file. */\n\n")
    mounts: list[tuple[str, str, int]] = []

    for path in files:
        rel = path.relative_to(root).as_posix()
        url = "/" + rel
        data_name = ident(rel)
        data = path.read_bytes()
        emit_array(buf, data_name, data)
        mounts.append((url, data_name, len(data)))

    # The rendered pages carry no file extension, so ctype_of() cannot derive
    # their type from the URL (only a bare "/" is assumed HTML) — state it, or a
    # browser downloads /reg instead of showing it.
    pages: list[tuple[str, str, int]] = []
    if args.render_pages:
        fqns = [f for f in args.render_pages.replace(",", " ").split() if f]
        if fqns:
            for url, html in render_pages(fqns, str(root)):
                data = html.encode("utf-8")
                data_name = ident(url.strip("/") or "index") + "_page"
                emit_array(buf, data_name, data)
                pages.append((url, data_name, len(data)))

    buf.write("static int32_t inspect_www_mount(void) {\n")
    for url, name, n in mounts:
        buf.write(
            f'    if (pm_metal_net_http_asgi_route_static("{url}", s_{name}, {n}u) != 0) {{\n'
            f"        return -1;\n"
            f"    }}\n"
        )
    for url, name, n in pages:
        buf.write(
            f'    if (pm_metal_net_http_asgi_route_static_ct("{url}", s_{name}, {n}u,\n'
            f'            "text/html; charset=utf-8") != 0) {{\n'
            f"        return -1;\n"
            f"    }}\n"
        )
    buf.write("    return 0;\n}\n")
    text = buf.getvalue()
    out = pathlib.Path(args.output)
    if out.is_file() and out.read_text(encoding="utf-8") == text:
        return 0
    out.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
