#!/usr/bin/env python3
"""Pack inspect/www files into a C include. Edit the files under www/, not the output."""
from __future__ import annotations

import argparse
import pathlib
import re
import sys


def render_index(module_names, template_dir):
    """Render the unified seat home from the card FQN ledger.

    The seat's `/` is the CDN-catalog view ("the box is a CDN of its own
    cards"), produced from the very templates the CDN serves (home.html +
    shell.html synced into www/) via `catalog_render`. `module_names` is the
    card FQN ledger from the build; per-module detail stays the live
    `/inspect/reg/<fqn>` RPC console (runtime C-served). Rendered at build so
    the seat serves static bytes; templates remain the one UI source.
    """
    import pymergetic.metal.inspect.catalog_render as cr

    registry = {
        "modules": lambda: module_names,
        "export_count": lambda f: 0,
    }
    engine = cr.Engine(template_dir)
    # The seat renders /packs/<fqn> at runtime from the compiled template, so
    # compile it here even though this build step never renders a package page.
    engine.compile("package.html")
    return cr.render_home(registry, engine=engine)


def ident(rel: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "_", rel).strip("_")
    return "www_" + (s if s else "root")


def emit_array(out, name: str, data: bytes) -> None:
    out.write(f"static const uint8_t s_{name}[] = {{\n")
    if not data:
        out.write("    0\n")
    else:
        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            line = ", ".join(str(b) for b in chunk)
            comma = "," if i + 16 < len(data) else ""
            out.write(f"    {line}{comma}\n")
    out.write("};\n\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("www", type=pathlib.Path, help="inspect/www directory")
    ap.add_argument(
        "--render-index",
        default="",
        help="render the seat home (CDN catalog view) at '/' from these card "
        "FQNs (space/comma separated) instead of embedding www/index.html",
    )
    args = ap.parse_args()
    root = args.www.resolve()
    if not root.is_dir():
        print(f"embed_www: no www at {root}", file=sys.stderr)
        return 1
    files = sorted(
        p
        for p in root.rglob("*")
        if p.is_file()
        # Skip VCS/tooling dotfiles (.gitignore, _compiled/, __pycache__): those
        # are build/bookkeeping artifacts, never served www assets.
        and not p.name.startswith(".")
        and not any(part in ("_compiled", "__pycache__") for part in p.parts)
    )
    if not files:
        print(f"embed_www: empty {root}", file=sys.stderr)
        return 1
    from io import StringIO

    buf = StringIO()
    buf.write("/* Generated by tools/embed_www.py - edit www/, not this file. */\n\n")
    mounts: list[tuple[str, str, int]] = []

    rendered_index = None
    if args.render_index:
        fqns = [f for f in args.render_index.replace(",", " ").split() if f]
        if fqns:
            rendered_index = render_index(fqns, str(root)).encode("utf-8")

    for path in files:
        rel = path.relative_to(root).as_posix()
        if rendered_index is not None and rel == "index.html":
            # The seat home is the CDN catalog view, rendered from the card
            # ledger; the bare SPA landing is dropped from the mount table.
            continue
        url = "/" + rel
        data_name = ident(rel)
        data = path.read_bytes()
        emit_array(buf, data_name, data)
        mounts.append((url, data_name, len(data)))

    if rendered_index is not None:
        emit_array(buf, "www_index_html", rendered_index)
        mounts.append(("/", "www_index_html", len(rendered_index)))

    # Lift a root index.html to "/" when no rendered index was requested.
    if not rendered_index:
        for i, (u, name, n) in enumerate(mounts):
            if u == "/index.html":
                mounts[i] = ("/", name, n)

    # A directory index must also answer the directory itself: links point at
    # /inspect (and /inspect/), not /inspect/index.html, and an unmounted path
    # falls through to the asgi default body — which a browser downloads.
    taken = {u for u, _, _ in mounts}
    aliases: list[tuple[str, str, int]] = []
    for url, name, n in mounts:
        if not url.endswith("/index.html"):
            continue
        bare = url[: -len("/index.html")]
        for alias in (bare, bare + "/"):
            if alias and alias not in taken:
                aliases.append((alias, name, n))
                taken.add(alias)
    buf.write("static int32_t inspect_www_mount(void) {\n")
    for url, name, n in mounts:
        buf.write(
            f'    if (pm_metal_net_http_asgi_route_static("{url}", s_{name}, {n}u) != 0) {{\n'
            f"        return -1;\n"
            f"    }}\n"
        )
    # Directory aliases carry no file extension, so they must state the type.
    for url, name, n in aliases:
        buf.write(
            f'    if (pm_metal_net_http_asgi_route_static_ct("{url}", s_{name}, {n}u,\n'
            f'            "text/html; charset=utf-8") != 0) {{\n'
            f"        return -1;\n"
            f"    }}\n"
        )
    buf.write("    return 0;\n}\n")
    text = buf.getvalue()
    out = pathlib.Path(args.output)
    if out.is_file() and out.read_text(encoding="utf-8") == text:
        return 0
    out.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
