# upy_embed.mk — the host seat's embedded µPy kernel (ports/embed route).
#
# The host C seat (host_test / ksweep / the selfhost feeds) links the µPy
# compiler+runtime in-process so pymergetic.metal.jit.py's object loop is a
# real source->mpy->load chain on this seat too, not the polite refusal the
# no-µPy era pinned. This is upstream's supported embed path:
#
#   1. `make -f $(TOP)/ports/embed/embed.mk` (run from host_upy/, whose
#      mpconfigport.h is the project config embed.mk expects beside it)
#      generates micropython_embed/ — the py core, this config, the genhdr
#      products (qstrdefs/moduledefs/mpversion/root_pointers, built by µPy's
#      own mkrules pipeline against THIS config) and the embed port glue
#      (embed_util.c: mp_embed_init/mp_embed_deinit + gchelper).
#   2. The rules below compile every .c in the package into build/upy-embed/
#      and stamp the object list (the package is generated, so the source
#      list only exists after step 1 — the stamp file is what the host
#      binaries' link lines consume, via $(shell cat)).
#
# No µPy source is edited; the package is generated bytes, same posture as
# src_embed.inc.h. Symbols: the µPy core (mp_*, qstr_*, gc_*, nlr_*) is C,
# compiled with the host's own cc; the host binary defines no mp_* symbol of
# its own, so there are no collisions.
#
# Ownership/lifetime: the GC heap is malloc'd by jit.py's card-boot init
# (PM_MOD_BOOT_C under PM_METAL_JIT_PY_EMBED) and freed by its deinit —
# the card that owns the µPy faces owns the kernel they run on. See
# src/pymergetic/metal/jit/py/__impl__.c.

UPY_EMBED := $(CURDIR)/build/upy-embed
UPY_EMBED_PACKAGE := $(UPY_EMBED)/micropython_embed
UPY_EMBED_OBJ := $(UPY_EMBED)/obj
UPY_EMBED_STAMP := $(UPY_EMBED)/package.stamp
UPY_EMBED_OBJS_FILE := $(UPY_EMBED)/objs.txt

# embed.mk needs MICROPYTHON_TOP and its own BUILD for the genhdr pipeline;
# it must run with cwd = host_upy/ so "-I." finds our mpconfigport.h (the
# project config the embed port documents as the integration point).
$(UPY_EMBED_STAMP): $(CURDIR)/host_upy/mpconfigport.h
	@mkdir -p $(UPY_EMBED)
	$(MAKE) -C $(CURDIR)/host_upy -f $(TOP)/ports/embed/embed.mk \
		MICROPYTHON_TOP=$(TOP) BUILD=$(UPY_EMBED)/build \
		PACKAGE_DIR=$(UPY_EMBED_PACKAGE) micropython-embed-package
	touch $@

# compile phase — re-entrant: by the time this parses, the package exists.
UPY_EMBED_SRCS := $(shell find $(UPY_EMBED_PACKAGE) -name '*.c' 2>/dev/null)
UPY_EMBED_OBJS := $(patsubst $(UPY_EMBED_PACKAGE)/%.c,$(UPY_EMBED_OBJ)/%.o,$(UPY_EMBED_SRCS)) \
	$(UPY_EMBED_OBJ)/port_faces.o
UPY_EMBED_CPPFLAGS := -I$(UPY_EMBED_PACKAGE) -I$(CURDIR)/host_upy -I$(TOP)/ports/embed \
	-std=gnu11 -O1 -g

$(UPY_EMBED_OBJ)/%.o: $(UPY_EMBED_PACKAGE)/%.c $(UPY_EMBED_STAMP)
	@mkdir -p $(dir $@)
	$(CC) $(UPY_EMBED_CPPFLAGS) -c -o $@ $<

# the host seat's own port faces (lexer-from-file/import-stat/open refusal,
# the browser seat's !MICROPY_VFS posture) — integrator-owned, so it compiles
# from host_upy/, not the generated package.
$(UPY_EMBED_OBJ)/port_faces.o: $(CURDIR)/host_upy/port_faces.c $(UPY_EMBED_STAMP)
	@mkdir -p $(dir $@)
	$(CC) $(UPY_EMBED_CPPFLAGS) -c -o $@ $<

# the object-list stamp: what the host link lines eat (late — the list lives
# in a file, so a fresh generation is picked up without re-parsing make).
# LDFLAGS_UPY expands at RECIPE time in the host binaries' link lines: by
# then the stamp exists, so the shell cat picks up the real list. Every
# binary that links the card objects also links the kernel (jit.py's faces
# reference mp_*; the µPy seats never build through this fragment).
UPY_EMBED_LATE_OBJS = $(shell cat $(UPY_EMBED_OBJS_FILE) 2>/dev/null)
LDFLAGS_UPY = $(UPY_EMBED_LATE_OBJS)

$(UPY_EMBED_OBJS_FILE): $(UPY_EMBED_OBJS) $(UPY_EMBED_STAMP)
	@find $(UPY_EMBED_OBJ) -name '*.o' | sort > $@
	@echo "upy embed: $$(wc -l < $@) objects in $(UPY_EMBED_OBJ)"

upy-embed: $(UPY_EMBED_OBJS_FILE)

clean-upy-embed:
	rm -rf $(UPY_EMBED)
