[package]
name = "pymergetic_metal_boot"
version = "0.1.0"
edition = "2021"

[lib]
path = "../__init__.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
pymergetic_metal_rt = { path = "../../rt/.pm" }
pymergetic_metal_mem = { path = "../../mem/.pm" }
pymergetic_metal_dt = { path = "../../dt/.pm" }
pymergetic_metal_console = { path = "../../console/.pm" }
pymergetic_metal_dev_serial = { path = "../../dev/serial/.pm" }
pymergetic_metal_log = { path = "../../log/.pm" }
pymergetic_metal_util_ascii = { path = "../../util/ascii/.pm" }
pymergetic_metal_util_size = { path = "../../util/size/.pm" }
pymergetic_metal_util_tar = { path = "../../util/tar/.pm" }
pymergetic_metal_util_lz4 = { path = "../../util/lz4/.pm" }
pymergetic_metal_bus_pci = { path = "../../bus/pci/.pm" }
pymergetic_metal_dev_time = { path = "../../dev/time/.pm" }
pymergetic_metal_dev_acpi = { path = "../../dev/acpi/.pm" }
pymergetic_metal_dev_random = { path = "../../dev/random/.pm" }
pymergetic_metal_dev_input = { path = "../../dev/input/.pm" }
pymergetic_metal_dev_gfx = { path = "../../dev/gfx/.pm" }
pymergetic_metal_hwtree = { path = "../../hwtree/.pm" }
pymergetic_metal_async = { path = "../../async/.pm" }
pymergetic_metal_vfs = { path = "../../vfs/.pm" }
pymergetic_metal_fs = { path = "../../fs/.pm" }
pymergetic_metal_fs_fat = { path = "../../fs/fat/.pm" }
pymergetic_metal_fs_mtar = { path = "../../fs/mtar/.pm" }
pymergetic_metal_fs_littlefs = { path = "../../fs/littlefs/.pm" }
pymergetic_metal_fs_tmpfs = { path = "../../fs/tmpfs/.pm" }
pymergetic_metal_dev_blk_ram = { path = "../../dev/blk/ram/.pm" }

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
