/* Nested builtin module objects — path == pymergetic.metal.<…> */
#ifndef PYMERGETIC_METAL_GLUE_MODULES_H_
#define PYMERGETIC_METAL_GLUE_MODULES_H_

#include "py/obj.h"

#if !defined(PM_METAL_CFG_FW_BROWSER) || !PM_METAL_CFG_FW_BROWSER
extern const mp_obj_module_t mp_module_pymergetic;
#endif
extern const mp_obj_module_t mp_module_pymergetic_metal;
extern const mp_obj_module_t mp_module_pymergetic_metal_util;
extern const mp_obj_module_t mp_module_pymergetic_metal_externals;
extern const mp_obj_module_t mp_module_pymergetic_metal_auth;
extern const mp_obj_module_t mp_module_pymergetic_metal_trust;
extern const mp_obj_module_t mp_module_pymergetic_metal_util_lz4;
extern const mp_obj_module_t mp_module_pymergetic_metal_util_size;
extern const mp_obj_module_t mp_module_pymergetic_metal_util_endian;
extern const mp_obj_module_t mp_module_pymergetic_metal_util_fourcc;
extern const mp_obj_module_t mp_module_pymergetic_metal_util_eightcc;
extern const mp_obj_module_t mp_module_pymergetic_metal_util_ascii;
extern const mp_obj_module_t mp_module_pymergetic_metal_util_tar;
extern const mp_obj_module_t mp_module_pymergetic_metal_mem;
extern const mp_obj_module_t mp_module_pymergetic_metal_mem_tlsf;
extern const mp_obj_module_t mp_module_pymergetic_metal_mem_port;
extern const mp_obj_module_t mp_module_pymergetic_metal_mem_arena;
extern const mp_obj_module_t mp_module_pymergetic_metal_mem_lock;
extern const mp_obj_module_t mp_module_pymergetic_metal_async;
extern const mp_obj_module_t mp_module_pymergetic_metal_console;
extern const mp_obj_module_t mp_module_pymergetic_metal_boot;
extern const mp_obj_module_t mp_module_pymergetic_metal_boot_tree;
extern const mp_obj_module_t mp_module_pymergetic_metal_rt;
extern const mp_obj_module_t mp_module_pymergetic_metal_fs;
extern const mp_obj_module_t mp_module_pymergetic_metal_fs_embed;
extern const mp_obj_module_t mp_module_pymergetic_metal_fs_fat;
extern const mp_obj_module_t mp_module_pymergetic_metal_fs_littlefs;
extern const mp_obj_module_t mp_module_pymergetic_metal_fs_mtar;
extern const mp_obj_module_t mp_module_pymergetic_metal_fs_overlay;
extern const mp_obj_module_t mp_module_pymergetic_metal_fs_tmpfs;
extern const mp_obj_module_t mp_module_pymergetic_metal_fs_vfs;
extern const mp_obj_module_t mp_module_pymergetic_metal_fs_wasmmod;
extern const mp_obj_module_t mp_module_pymergetic_metal_fs_zip;
extern const mp_obj_module_t mp_module_pymergetic_metal_pack;
extern const mp_obj_module_t mp_module_pymergetic_metal_hwtree;
extern const mp_obj_module_t mp_module_pymergetic_metal_net;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_asgi;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_dhcp;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_dns;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_faces;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_http;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_ip;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_nic;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_ntp;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_pump;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_ssh;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_tftp;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_tls;
extern const mp_obj_module_t mp_module_pymergetic_metal_net_wg;
extern const mp_obj_module_t mp_module_pymergetic_metal_draw;
extern const mp_obj_module_t mp_module_pymergetic_metal_bus;
extern const mp_obj_module_t mp_module_pymergetic_metal_bus_pci;
extern const mp_obj_module_t mp_module_pymergetic_metal_bus_virtio;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_serial;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_acpi;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_blk;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_stream;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_gfx;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_gfx_compositor;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_gfx_scanout;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_gfx_text;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_input;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_input_kbd;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_net;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_net_bge;
extern const mp_obj_module_t mp_module_pymergetic_metal_dev_net_virtio_net;
extern const mp_obj_module_t mp_module_pymergetic_metal_shell;
extern const mp_obj_module_t mp_module_pymergetic_metal_shell_tui;
extern const mp_obj_module_t mp_module_pymergetic_metal_shell_ui;
extern const mp_obj_module_t mp_module_pymergetic_metal_shell_vt;
extern const mp_obj_module_t mp_module_pymergetic_metal_wamr_host;

#endif
