# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.net`` — generated package re-exports (scripts/gen_py_stubs.py).
"""

from typing import Any

from . import asgi as asgi
from . import http as http
from . import ip as ip
from . import ssh as ssh
from . import tls as tls

__all__ = ['asgi', 'http', 'ip', 'ssh', 'tls']
__path__: list[str]

def __getattr__(name: str) -> Any: ...
