# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.net.asgi`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/dev/net/asgi_py_bind.c
"""

from typing import Any

def app_health(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def app_static(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def autoload(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def close(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def conn_method(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def conn_path(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def listen(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def mount(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def register_py(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def reload(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def reply(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def unmount(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
