"""Typing face (matrix Py count = max(glue,.pyi))."""

def init(*args, **kwargs): ...
def init_tls(*args, **kwargs): ...
def shutdown(*args, **kwargs): ...
def poll(*args, **kwargs): ...
def served(*args, **kwargs): ...
def client_get(*args, **kwargs): ...
def get(*args, **kwargs): ...
def status(*args, **kwargs): ...
def body_len(*args, **kwargs): ...
def body(*args, **kwargs): ...
def set_tls_verify_none(*args, **kwargs): ...
def client_poll(*args, **kwargs): ...
