def init(addr_be: int, mask_be: int, gw_be: int) -> int: ...
def ready() -> int: ...
def set_addrs(addr: int, mask: int, gw: int) -> int: ...
def set_dns(dns: int) -> int: ...
def addr() -> int: ...
def gw() -> int: ...
def mask() -> int: ...
def dns() -> int: ...
def arp_resolve(ip_host: int) -> int: ...
def announce() -> int: ...
def poll() -> None: ...
def ping(dst_ip: int, id: int, seq: int) -> int: ...
def ping_replies() -> int: ...
