# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.net.ip`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/net/ip/ip_py_bind.c
"""

from typing import Any

def accept(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def bind_if(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def close(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def connect(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def dns(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def dns_last_ntoa(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def listen(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def recv(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def send(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def socket(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
