"""Typing face (matrix Py count = max(glue,.pyi))."""

def resolve(*args, **kwargs): ...
def new(*args, **kwargs): ...
def close(*args, **kwargs): ...
def version(*args, **kwargs): ...
def request(*args, **kwargs): ...
def response(*args, **kwargs): ...
def abort(*args, **kwargs): ...
def redirect(*args, **kwargs): ...
def send_file(*args, **kwargs): ...
def url_pattern(*args, **kwargs): ...
def async_bytes_io(*args, **kwargs): ...
def iscoroutine(*args, **kwargs): ...
def getattr(*args, **kwargs): ...
def call0(*args, **kwargs): ...
def call_method0(*args, **kwargs): ...
def call_method1(*args, **kwargs): ...
def route(*args, **kwargs): ...
def run(*args, **kwargs): ...
def get(*args, **kwargs): ...
def post(*args, **kwargs): ...
