"""pymergetic.metal.net.ntp — µPy face."""

def sync(server_ip: int) -> int: ...
def sync_host(host: str) -> int: ...
def poll() -> None: ...
def status() -> int: ...
def last_unix_secs() -> int: ...
def query(server_ip: int) -> tuple[int, int]: ...
def query_host(host: str) -> tuple[int, int]: ...
