def once() -> None: ...
def bind_async() -> None: ...
def await_tcp_established_h(sock: int) -> int: ...
def await_tcp_rx_h(sock: int, min_bytes: int) -> int: ...
def await_tcp_established(sock: int, max_iters: int) -> int: ...
def await_tcp_rx(sock: int, min_bytes: int, max_iters: int) -> int: ...
def wake_tcp() -> None: ...
