# AUTO-GENERATED by scripts/gen_py_stubs.py — do not hand-edit (Phase 2e, docs/MICROPYTHON.md)

"""
``pymergetic.metal.net.ssh`` — generated from PM_METAL_PY_BIND call sites.

Sources:
  src/pymergetic/metal/dev/net/ssh_py_bind.c
"""

from typing import Any

def autoload(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def close(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def listen(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def status(*args: Any) -> Any:
    """C bind: PM_METAL_PY_SYNC."""
    ...

def __getattr__(name: str) -> Any: ...
