# pymergetic.metal.net.ssh — nested builtin; callee src/.../net/ssh

from typing import TypeAlias

_WriteableBuffer: TypeAlias = bytearray | memoryview

def available() -> bool: ...
def init() -> int: ...
def autoload() -> int: ...
def listen(port: int) -> int: ...
def release() -> None: ...
def close(s: int) -> None: ...
def poll() -> int: ...
def served() -> int: ...
def status(cap: int) -> str | None: ...
def listen_port() -> int: ...
def hostkey_label(cap: int) -> str | None: ...
def client_exec(
    host: str,
    port: int,
    user: str,
    cmd: str,
    buf: _WriteableBuffer | None = ...,
) -> int: ...
def banner_send() -> int: ...
def banner_sent() -> int: ...
def banner_reset() -> None: ...
def reg_load() -> int: ...
