"""pymergetic.metal.net.tftp — µPy face."""

def get_async(server_ip: int, filename: str, buf: bytearray | memoryview) -> int: ...
def poll() -> None: ...
def status() -> int: ...
def len() -> int: ...
def body() -> bytes | None: ...
def get(server_ip: int, filename: str, buf: bytearray | memoryview) -> int: ...
