"""pymergetic.metal.net.tls — µPy face over C TLS."""

VERIFY_REQUIRED: int
VERIFY_NONE: int
INVALID: int

def mbedtls_register() -> int: ...
def init() -> int: ...
def fini() -> None: ...
def client_open(sock: int, host: str | None, flags: int) -> int: ...
def server_open(sock: int) -> int: ...
def handshake(th: int) -> int: ...
def try_read(th: int, buf: bytearray | memoryview) -> int: ...
def write(th: int, buf: bytes | bytearray | memoryview) -> int: ...
def close(th: int) -> None: ...
def load_ca_pem(pem: bytes | bytearray | memoryview) -> int: ...
def load_ca_file(path: str) -> int: ...
def set_server_cert_pem(pem: bytes | bytearray | memoryview) -> int: ...
def set_server_key_pem(pem: bytes | bytearray | memoryview) -> int: ...
def set_server_chain_pem(pem: bytes | bytearray | memoryview) -> int: ...
def load_smoke_server() -> int: ...
def poll() -> None: ...
