def up_named(
    ifname: str, private_key_b64: str, listen_port: int, tunnel_ip: str, tunnel_mask: str
) -> int: ...
def down_named(ifname: str) -> int: ...
def peer_add_named(
    ifname: str,
    public_key_b64: str,
    endpoint_ip: str,
    endpoint_port: int,
    allowed_ip: str,
    allowed_mask: str,
) -> int: ...
def peer_del_named(ifname: str, public_key_b64: str) -> int: ...
def status_named(ifname: str) -> dict | None: ...
def up(private_key_b64: str, listen_port: int, tunnel_ip: str, tunnel_mask: str) -> int: ...
def down() -> int: ...
def peer_add(
    public_key_b64: str,
    endpoint_ip: str,
    endpoint_port: int,
    allowed_ip: str,
    allowed_mask: str,
) -> int: ...
def peer_del(public_key_b64: str) -> int: ...
def status() -> dict | None: ...
def ready() -> int: ...
def handshake_smoke() -> int: ...
