"""pymergetic.metal — µPy face of extmod/metal/modmetal.c."""

from collections.abc import Callable, Iterator
from typing import Any

from . import process as process

def __init__() -> None: ...
def ready() -> bool: ...
def poll() -> None: ...
def register_upy(gen: Iterator[Any]) -> None: ...
def PM_METAL_DRV_PCI(
    mod: str, vendor: int, device: int, attach: Callable[..., int]
) -> None: ...
def PM_METAL_DRV_ISA(mod: str, port: int, attach: Callable[..., int]) -> None: ...
def PM_METAL_DRV_PLATFORM(mod: str, attach: Callable[..., int]) -> None: ...

def packages() -> None: ...
def packages_catalog(channel: str = "lead") -> None: ...
def packages_search(q: str, channel: str = "lead") -> None: ...
def packages_filter(
    prefix: str | None = None,
    name_contains: str | None = None,
    kind: str | None = None,
    arch: str | None = None,
    channel: str = "lead",
) -> None: ...
def capabilities() -> dict[str, Any]:
    """µPy dict of host + vendored-Python faces (:code:`asgi`, :code:`ssh`,
    :code:`microdot`, :code:`utemplate`). Mirrors the :code:`/capabilities`
    JSON contract as a live dict so a REPL script can gate on it directly."""
    ...

def serve() -> None:
    """Start the default instance of every registered service (httpd :8090,
    sshd :2222) on ANY so hostfwd/host can reach them."""
    ...

def services() -> None:
    """List registered services and their live instances (start/stop hints)."""
    ...

def help() -> None: ...

# Registry cards attach as nested modules (`m.net.ip`) with no name list.
def __getattr__(name: str) -> Any: ...
