"""pymergetic.metal — µPy face of extmod/metal/modmetal.c."""

from collections.abc import Callable, Iterator
from typing import Any

from . import process as process

def __init__() -> None: ...
def ready() -> bool: ...
def poll() -> None: ...
def register_upy(gen: Iterator[Any]) -> None: ...
def PM_METAL_DRV_PCI(
    mod: str, vendor: int, device: int, attach: Callable[..., int]
) -> None: ...
def PM_METAL_DRV_ISA(mod: str, port: int, attach: Callable[..., int]) -> None: ...
def PM_METAL_DRV_PLATFORM(mod: str, attach: Callable[..., int]) -> None: ...

# Registry cards attach as nested modules (`m.net.ip`) with no name list.
def __getattr__(name: str) -> Any: ...
