/** @file
  pm_metal_iface_embed_install() — impl: common. Split into its own
  translation unit (rather than folded into iface.c) purely so the big
  generated byte-array include (iface_metal_guest_embed.inc.c) doesn't
  bloat iface.c's own compile unit, same reasoning as other generated
  kept separate from py.c.
**/
#include <pymergetic/metal/util/iface.h>

#include "iface_metal_guest_embed.inc.c"
