/** @file
  pm_metal_iface_* — impl: common (see util/iface.h; wasm32 mods reach
  this same code via this file's own wasi-style import registration at
  the bottom, not via a second compiled copy).

  Package storage: each registered pack decompresses once (lz4 -> ustar,
  or a raw-ustar copy if blob_len == uncompressed_len) into its own fixed
  host buffer; file_count()/file_at() walk it fresh each call via
  util/tar.h (small packs, no need to cache the walk itself). file_open()
  additionally keeps a small per-package cache of already-copied file
  bytes (tar.h's own iter_read() only *copies* out of the ustar buffer,
  it never hands back a pointer into it — see that header's own file
  comment — so a "borrow forever" file_open() needs somewhere durable to
  copy into once).

  Sym table: g_pm_metal_iface_syms[] (iface_syms.inc.c, generated by
  scripts/gen_iface_syms.py from every other module's own NativeSymbol[]
  table — never hand-written here).
**/
#include <pymergetic/metal/util/iface.h>

#include <stdio.h>
#include <string.h>

#include <pymergetic/metal/runtime/mem/mem.h>
#include <pymergetic/metal/util/lz4.h>
#include <pymergetic/metal/util/tar.h>

#define PM_METAL_IFACE_PKG_MAX        64u
#define PM_METAL_IFACE_FILE_CACHE_MAX 256u
#define PM_METAL_IFACE_STR_MAX        64u

typedef struct {
  int      used;
  char     path[PM_METAL_IFACE_PATH_MAX];
  uint8_t *data;
  uint32_t len;
} iface_file_cache_t;

typedef struct {
  int                       used;
  char                      name[PM_METAL_IFACE_STR_MAX];
  pm_metal_iface_pkg_kind_t kind;
  char                      version[PM_METAL_IFACE_STR_MAX];
  char                      abi_hash[PM_METAL_IFACE_STR_MAX];
  uint32_t                  blob_len;
  uint8_t                  *ustar;
  uint32_t                  ustar_len;
  uint32_t                  nfiles;
  iface_file_cache_t        cache[PM_METAL_IFACE_FILE_CACHE_MAX];
  uint32_t                  cache_count;
} iface_pkg_t;

static iface_pkg_t g_pkgs[PM_METAL_IFACE_PKG_MAX];
static uint32_t    g_pkg_count;

#include "iface_syms.inc.c"

/*
 * Tar from `tar -C dir .` stores "./foo"; HTTP clients collapse "/./" in
 * URLs so list/read must agree on a ./ -stripped form.
 */
static const char *PathSkipDotSlash(const char *path)
{
  if (path == NULL) {
    return "";
  }
  while (path[0] == '.' && path[1] == '/') {
    path += 2;
  }
  while (path[0] == '/') {
    path++;
  }
  return path;
}

static void StrCopy(char *dst, size_t cap, const char *src)
{
  snprintf(dst, cap, "%s", src != NULL ? src : "");
}

static iface_pkg_t *PkgFind(const char *name)
{
  uint32_t i;

  if (name == NULL) {
    return NULL;
  }
  for (i = 0; i < g_pkg_count; i++) {
    if (g_pkgs[i].used && strcmp(g_pkgs[i].name, name) == 0) {
      return &g_pkgs[i];
    }
  }
  return NULL;
}

static uint32_t PkgCountFiles(const uint8_t *ustar, size_t len)
{
  pm_metal_util_tar_iter_t it;
  uint32_t                 n = 0;
  int                      rc;

  pm_metal_util_tar_iter_init(&it, ustar, len);
  while ((rc = pm_metal_util_tar_iter_next(&it)) == 1) {
    if (pm_metal_util_tar_iter_is_dir(&it) == 0) {
      n++;
    }
  }
  pm_metal_util_tar_iter_close(&it);
  return n;
}

int32_t pm_metal_iface_pkg_register(const char               *name,
                                    pm_metal_iface_pkg_kind_t kind,
                                    const char               *version,
                                    const char               *abi_hash,
                                    const uint8_t            *blob,
                                    uint32_t                  blob_len,
                                    uint32_t                  uncompressed_len)
{
  iface_pkg_t *pkg;
  uint32_t     idx;

  if (name == NULL || name[0] == '\0' || blob == NULL || uncompressed_len == 0) {
    return -1;
  }
  if (PkgFind(name) != NULL) {
    return -1;
  }

  for (idx = 0; idx < PM_METAL_IFACE_PKG_MAX; idx++) {
    if (!g_pkgs[idx].used) {
      break;
    }
  }
  if (idx >= PM_METAL_IFACE_PKG_MAX) {
    return -1;
  }

  pkg = &g_pkgs[idx];
  memset(pkg, 0, sizeof(*pkg));

  pkg->ustar =
    (uint8_t *)pm_metal_mem_alloc(uncompressed_len, PM_METAL_MEM_HEAP, PM_METAL_MEM_ID_NONE);
  if (pkg->ustar == NULL) {
    return -1;
  }

  if (blob_len == uncompressed_len) {
    /* Raw ustar (debug opt-out — see util/iface.h file header). */
    memcpy(pkg->ustar, blob, uncompressed_len);
  } else {
    int n = pm_metal_util_lz4_decompress(blob, blob_len, pkg->ustar, uncompressed_len);

    if (n < 0 || (uint32_t)n != uncompressed_len) {
      pm_metal_mem_free(pkg->ustar);
      return -1;
    }
  }

  pkg->used = 1;
  StrCopy(pkg->name, sizeof(pkg->name), name);
  pkg->kind = kind;
  StrCopy(pkg->version, sizeof(pkg->version), version);
  StrCopy(pkg->abi_hash, sizeof(pkg->abi_hash), abi_hash);
  pkg->blob_len  = blob_len;
  pkg->ustar_len = uncompressed_len;
  pkg->nfiles    = PkgCountFiles(pkg->ustar, pkg->ustar_len);

  if (idx >= g_pkg_count) {
    g_pkg_count = idx + 1u;
  }
  return 0;
}

int32_t pm_metal_iface_pkg_count(void)
{
  return (int32_t)g_pkg_count;
}

static void PkgInfoFill(const iface_pkg_t *pkg, pm_metal_iface_pkg_info_t *out)
{
  out->name     = pkg->name;
  out->kind     = pkg->kind;
  out->version  = pkg->version;
  out->abi_hash = pkg->abi_hash;
  out->nfiles   = pkg->nfiles;
  out->blob_len = pkg->blob_len;
}

int32_t pm_metal_iface_pkg_at(uint32_t i, pm_metal_iface_pkg_info_t *out)
{
  if (out == NULL || i >= g_pkg_count || !g_pkgs[i].used) {
    return -1;
  }
  PkgInfoFill(&g_pkgs[i], out);
  return 0;
}

int32_t pm_metal_iface_pkg_info(const char *name, pm_metal_iface_pkg_info_t *out)
{
  iface_pkg_t *pkg = PkgFind(name);

  if (pkg == NULL || out == NULL) {
    return -1;
  }
  PkgInfoFill(pkg, out);
  return 0;
}

int32_t pm_metal_iface_file_count(const char *pkg)
{
  iface_pkg_t *p = PkgFind(pkg);

  if (p == NULL) {
    return -1;
  }
  return (int32_t)p->nfiles;
}

int32_t pm_metal_iface_file_at(const char *pkg, uint32_t i, char *out, uint32_t cap)
{
  iface_pkg_t             *p = PkgFind(pkg);
  pm_metal_util_tar_iter_t it;
  uint32_t                 seen = 0;
  int                      rc;

  if (p == NULL || out == NULL) {
    return -1;
  }

  pm_metal_util_tar_iter_init(&it, p->ustar, p->ustar_len);
  while ((rc = pm_metal_util_tar_iter_next(&it)) == 1) {
    if (pm_metal_util_tar_iter_is_dir(&it) != 0) {
      continue;
    }
    if (seen == i) {
      char name[PM_METAL_IFACE_PATH_MAX];
      int  n = pm_metal_util_tar_iter_name(&it, name, sizeof(name));

      pm_metal_util_tar_iter_close(&it);
      if (n < 0) {
        return -1;
      }
      StrCopy(out, (size_t)cap, PathSkipDotSlash(name));
      return 0;
    }
    seen++;
  }
  pm_metal_util_tar_iter_close(&it);
  return -1;
}

static iface_file_cache_t *FileCacheFind(iface_pkg_t *pkg, const char *path)
{
  uint32_t i;

  for (i = 0; i < pkg->cache_count; i++) {
    if (pkg->cache[i].used && strcmp(pkg->cache[i].path, path) == 0) {
      return &pkg->cache[i];
    }
  }
  return NULL;
}

static iface_file_cache_t *FileCacheLoad(iface_pkg_t *pkg, const char *path)
{
  pm_metal_util_tar_iter_t it;
  int                      rc;
  iface_file_cache_t      *slot = NULL;

  if (pkg->cache_count >= PM_METAL_IFACE_FILE_CACHE_MAX) {
    return NULL;
  }

  path = PathSkipDotSlash(path);
  pm_metal_util_tar_iter_init(&it, pkg->ustar, pkg->ustar_len);
  while ((rc = pm_metal_util_tar_iter_next(&it)) == 1) {
    char name[PM_METAL_IFACE_PATH_MAX];

    if (pm_metal_util_tar_iter_is_dir(&it) != 0) {
      continue;
    }
    if (pm_metal_util_tar_iter_name(&it, name, sizeof(name)) < 0 ||
        strcmp(PathSkipDotSlash(name), path) != 0) {
      continue;
    }

    {
      uint64_t size = pm_metal_util_tar_iter_size(&it);
      uint8_t *data;

      data = (uint8_t *)pm_metal_mem_alloc((uint32_t)size, PM_METAL_MEM_HEAP, PM_METAL_MEM_ID_NONE);
      if (data == NULL) {
        break;
      }

      {
        uint64_t got = 0;

        while (got < size) {
          int n = pm_metal_util_tar_iter_read(&it, data + got, (size_t)(size - got));

          if (n <= 0) {
            pm_metal_mem_free(data);
            data = NULL;
            break;
          }
          got += (uint64_t)n;
        }
      }
      if (data == NULL) {
        break;
      }

      slot       = &pkg->cache[pkg->cache_count++];
      slot->used = 1;
      StrCopy(slot->path, sizeof(slot->path), path);
      slot->data = data;
      slot->len  = (uint32_t)size;
    }
    break;
  }
  pm_metal_util_tar_iter_close(&it);
  return slot;
}

int32_t pm_metal_iface_file_open(const char     *pkg,
                                 const char     *path,
                                 const uint8_t **data,
                                 uint32_t       *len)
{
  iface_pkg_t        *p = PkgFind(pkg);
  iface_file_cache_t *slot;

  if (p == NULL || path == NULL || data == NULL || len == NULL) {
    return -1;
  }

  path = PathSkipDotSlash(path);
  slot = FileCacheFind(p, path);
  if (slot == NULL) {
    slot = FileCacheLoad(p, path);
  }
  if (slot == NULL) {
    return -1;
  }

  *data = slot->data;
  *len  = slot->len;
  return 0;
}

int32_t pm_metal_iface_sym_count(void)
{
  return (int32_t)g_pm_metal_iface_sym_count;
}

int32_t pm_metal_iface_sym_at(uint32_t i, pm_metal_iface_sym_t *out)
{
  if (out == NULL || i >= g_pm_metal_iface_sym_count) {
    return -1;
  }
  *out = g_pm_metal_iface_syms[i];
  return 0;
}

int32_t pm_metal_iface_sym_lookup(const char *module, const char *name, pm_metal_iface_sym_t *out)
{
  uint32_t i;

  if (module == NULL || name == NULL || out == NULL) {
    return -1;
  }

  for (i = 0; i < g_pm_metal_iface_sym_count; i++) {
    if (strcmp(g_pm_metal_iface_syms[i].module, module) == 0 &&
        strcmp(g_pm_metal_iface_syms[i].name, name) == 0) {
      *out = g_pm_metal_iface_syms[i];
      return 0;
    }
  }
  return -1;
}

/*
 * wasi-style import bridge — buffer-out flattening, same reasoning as
 * util/doc.c's own bridge (see that file + util/iface.h's file header).
 * pkg_register has no guest entry point: every v1 caller (embed-iface.sh's
 * generated install, guest/wasm/wasm.c's boot-time call into it) is
 * already host C — see util/iface.h.
 */
#include "wasm_export.h"

static int32_t pm_metal_iface_pkg_count_native(wasm_exec_env_t exec_env)
{
  (void)exec_env;
  return pm_metal_iface_pkg_count();
}

static int32_t pm_metal_iface_pkg_at_native(wasm_exec_env_t exec_env,
                                            uint32_t        i,
                                            char           *name,
                                            uint32_t        name_cap,
                                            uint32_t       *out_kind,
                                            char           *version,
                                            uint32_t        version_cap,
                                            char           *abi_hash,
                                            uint32_t        abi_hash_cap,
                                            uint32_t       *out_nfiles,
                                            uint32_t       *out_blob_len)
{
  pm_metal_iface_pkg_info_t info;

  (void)exec_env;
  if (pm_metal_iface_pkg_at(i, &info) != 0) {
    return -1;
  }

  StrCopy(name, name_cap, info.name);
  if (out_kind != NULL) {
    *out_kind = (uint32_t)info.kind;
  }
  StrCopy(version, version_cap, info.version);
  StrCopy(abi_hash, abi_hash_cap, info.abi_hash);
  if (out_nfiles != NULL) {
    *out_nfiles = info.nfiles;
  }
  if (out_blob_len != NULL) {
    *out_blob_len = info.blob_len;
  }
  return 0;
}

static int32_t pm_metal_iface_file_count_native(wasm_exec_env_t exec_env, const char *pkg)
{
  (void)exec_env;
  return pm_metal_iface_file_count(pkg);
}

static int32_t pm_metal_iface_file_at_native(
  wasm_exec_env_t exec_env, const char *pkg, uint32_t i, char *out, uint32_t cap)
{
  (void)exec_env;
  return pm_metal_iface_file_at(pkg, i, out, cap);
}

static int32_t pm_metal_iface_file_read_native(
  wasm_exec_env_t exec_env, const char *pkg, const char *path, uint8_t *dst, uint32_t dst_cap)
{
  const uint8_t *data;
  uint32_t       len;

  (void)exec_env;
  if (pm_metal_iface_file_open(pkg, path, &data, &len) != 0) {
    return -1;
  }
  if (dst != NULL && dst_cap > 0) {
    memcpy(dst, data, (len < dst_cap) ? len : dst_cap);
  }
  return (int32_t)len;
}

static int32_t pm_metal_iface_sym_count_native(wasm_exec_env_t exec_env)
{
  (void)exec_env;
  return pm_metal_iface_sym_count();
}

static int32_t pm_metal_iface_sym_at_native(wasm_exec_env_t exec_env,
                                            uint32_t        i,
                                            char           *module,
                                            uint32_t        module_cap,
                                            char           *name,
                                            uint32_t        name_cap,
                                            char           *sig,
                                            uint32_t        sig_cap,
                                            uint32_t       *out_class,
                                            char           *doc_key,
                                            uint32_t        doc_key_cap)
{
  pm_metal_iface_sym_t sym;

  (void)exec_env;
  if (pm_metal_iface_sym_at(i, &sym) != 0) {
    return -1;
  }

  StrCopy(module, module_cap, sym.module);
  StrCopy(name, name_cap, sym.name);
  StrCopy(sig, sig_cap, sym.sig);
  if (out_class != NULL) {
    *out_class = (uint32_t)sym.class_;
  }
  StrCopy(doc_key, doc_key_cap, sym.doc_key);
  return 0;
}

static int32_t pm_metal_iface_sym_lookup_native(wasm_exec_env_t exec_env,
                                                const char     *module,
                                                const char     *name,
                                                char           *sig,
                                                uint32_t        sig_cap,
                                                uint32_t       *out_class,
                                                char           *doc_key,
                                                uint32_t        doc_key_cap)
{
  pm_metal_iface_sym_t sym;

  (void)exec_env;
  if (pm_metal_iface_sym_lookup(module, name, &sym) != 0) {
    return -1;
  }

  StrCopy(sig, sig_cap, sym.sig);
  if (out_class != NULL) {
    *out_class = (uint32_t)sym.class_;
  }
  StrCopy(doc_key, doc_key_cap, sym.doc_key);
  return 0;
}

static NativeSymbol g_pm_metal_util_iface_native_symbols[] = {
  { "pm_metal_iface_pkg_count", (void *)pm_metal_iface_pkg_count_native, "()i", NULL },
  { "pm_metal_iface_pkg_at", (void *)pm_metal_iface_pkg_at_native, "(i*~**~*~**)i", NULL },
  { "pm_metal_iface_file_count", (void *)pm_metal_iface_file_count_native, "($)i", NULL },
  { "pm_metal_iface_file_at", (void *)pm_metal_iface_file_at_native, "($i*~)i", NULL },
  { "pm_metal_iface_file_read", (void *)pm_metal_iface_file_read_native, "($$*~)i", NULL },
  { "pm_metal_iface_sym_count", (void *)pm_metal_iface_sym_count_native, "()i", NULL },
  { "pm_metal_iface_sym_at", (void *)pm_metal_iface_sym_at_native, "(i*~*~*~**~)i", NULL },
  { "pm_metal_iface_sym_lookup", (void *)pm_metal_iface_sym_lookup_native, "($$*~**~)i", NULL },
};

int pm_metal_util_iface_native_register(void)
{
  if (!wasm_runtime_register_natives(PM_METAL_UTIL_IFACE_WASI_MODULE,
                                     g_pm_metal_util_iface_native_symbols,
                                     sizeof(g_pm_metal_util_iface_native_symbols) /
                                       sizeof(g_pm_metal_util_iface_native_symbols[0]))) {
    return -1;
  }
  return 0;
}
