# DO NOT EDIT — generated by `pymergetic.util.gen` (live µPy import).
# pymergetic.metal.boot

from typing import Any

def boot(*args: Any, **kwargs: Any) -> Any: ...

def feed_span(*args: Any, **kwargs: Any) -> Any: ...

def ready(*args: Any, **kwargs: Any) -> Any: ...

