//! Stage generated async faces into OUT_DIR so rust-analyzer can resolve
//! them. `include/` is gitignored (see package `.gitignore` + module.md),
//! and RA skips gitignored `#[path]` targets even when cargo can read them.
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let pkg = manifest
        .join("../../../../../../")
        .canonicalize()
        .expect("package root from input/.pm");
    let src_dir = pkg.join("include/pymergetic/metal/async");
    let dst_dir = out.join("async_faces");
    fs::create_dir_all(&dst_dir).expect("OUT_DIR/async_faces");

    let mut mods = String::from("/* GENERATED by input/.pm/build.rs - do not edit. */\n");

    for (mod_name, file) in [
        ("async_task_face", "task.rs"),
        ("async_coro_face", "coro.rs"),
        ("async_handle_face", "handle.rs"),
        ("async_time_face", "time.rs"),
    ] {
        let src = src_dir.join(file);
        println!("cargo:rerun-if-changed={}", src.display());
        let dst = dst_dir.join(file);
        fs::copy(&src, &dst).unwrap_or_else(|e| {
            panic!(
                "copy {} -> {}: {} (run: ./forge-cli mod sync)",
                src.display(),
                dst.display(),
                e
            )
        });
        let abs = dst.canonicalize().unwrap_or(dst);
        let path = abs.to_string_lossy().replace('\\', "/").replace('"', "\\\"");
        mods.push_str(&format!("#[path = \"{path}\"]\nmod {mod_name};\n"));
    }

    fs::write(out.join("async_face_mods.rs"), mods).expect("write async_face_mods.rs");
}
