# Metal package embed list — filled by `metal pack`.
# Usage (from a build script):
#   source "${ROOT}/scripts/lib/metal-packages.sh"
#   pm_metal_packages_embed_list   # prints paths under build/packages/
# shellcheck shell=bash

pm_metal_packages_dir() {
	echo "${ROOT}/build/packages"
}

# Print absolute paths of packed .wasm files listed in embed_list.txt (if any).
pm_metal_packages_embed_list() {
	local list dir f
	dir="$(pm_metal_packages_dir)"
	list="${dir}/embed_list.txt"
	if [[ ! -f "${list}" ]]; then
		return 0
	fi
	while IFS= read -r f || [[ -n "${f}" ]]; do
		[[ -z "${f}" || "${f}" =~ ^# ]] && continue
		if [[ -f "${dir}/${f}" ]]; then
			echo "${dir}/${f}"
		fi
	done <"${list}"
}

# Write a tiny generated C snippet that names embedded packages (for future link).
# Does not embed wasm bytes yet — phase-5 hook for embed-mods integration.
pm_metal_packages_write_embed_inc() {
	local dir list out
	dir="$(pm_metal_packages_dir)"
	list="${dir}/embed_list.txt"
	out="${dir}/embed_list.inc.c"
	mkdir -p "${dir}"
	{
		echo "/* GENERATED by metal pack / pm_metal_packages_write_embed_inc — do not hand-edit */"
		echo "/* Full wasm byte embed still via embed-mods; this lists package names. */"
		echo "#ifndef PM_METAL_PACKAGES_EMBED_LIST_INC"
		echo "#define PM_METAL_PACKAGES_EMBED_LIST_INC"
		echo "static const char * const pm_metal_package_embed_names[] = {"
		if [[ -f "${list}" ]]; then
			while IFS= read -r f || [[ -n "${f}" ]]; do
				[[ -z "${f}" || "${f}" =~ ^# ]] && continue
				echo "  \"${f}\","
			done <"${list}"
		fi
		echo "  0"
		echo "};"
		echo "#endif"
	} >"${out}"
	echo "metal-packages: wrote ${out}"
}
