//! Emit C or Rust source that embeds a byte image (mtar / fat / zip / any blob).
#![cfg_attr(any(target_os = "none", target_os = "uefi"), no_std)]
#![allow(dead_code, non_camel_case_types)]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;

use pymergetic_metal_rt as _;

/// Write C source: `static const uint8_t NAME[] = {...};` + `_len`.
/// Returns bytes written into `out`, or -1.
#[no_mangle]
pub unsafe extern "C" fn pm_metal_fs_embed_c(
    name: *const u8,
    data: *const u8,
    len: usize,
    out: *mut u8,
    out_cap: usize,
    out_len: *mut usize,
) -> i32 {
    if name.is_null() || data.is_null() || out.is_null() || out_len.is_null() {
        return -1;
    }
    let nm = cstr(name);
    if !is_ident(nm) {
        return -1;
    }
    let bytes = core::slice::from_raw_parts(data, len);
    let mut s = String::new();
    s.push_str("/* generated by pm_metal_fs_embed_c — do not edit */\n");
    s.push_str("static const uint8_t ");
    s.push_str(nm);
    s.push_str("[] = {\n");
    for (i, b) in bytes.iter().enumerate() {
        if i % 12 == 0 {
            s.push_str("  ");
        }
        s.push_str(&alloc::format!("0x{:02x},", b));
        if i % 12 == 11 || i + 1 == bytes.len() {
            s.push('\n');
        } else {
            s.push(' ');
        }
    }
    s.push_str("};\nstatic const unsigned long ");
    s.push_str(nm);
    s.push_str("_len = ");
    s.push_str(&alloc::format!("{};\n", len));
    write_out(out, out_cap, out_len, s.as_bytes())
}

/// Write Rust source: `pub static NAME: &[u8] = &[...];`
#[no_mangle]
pub unsafe extern "C" fn pm_metal_fs_embed_rs(
    name: *const u8,
    data: *const u8,
    len: usize,
    out: *mut u8,
    out_cap: usize,
    out_len: *mut usize,
) -> i32 {
    if name.is_null() || data.is_null() || out.is_null() || out_len.is_null() {
        return -1;
    }
    let nm = cstr(name);
    if !is_ident(nm) {
        return -1;
    }
    let bytes = core::slice::from_raw_parts(data, len);
    let mut s = String::new();
    s.push_str("/* generated by pm_metal_fs_embed_rs — do not edit */\n");
    s.push_str("pub static ");
    s.push_str(nm);
    s.push_str(": &[u8] = &[\n");
    for (i, b) in bytes.iter().enumerate() {
        if i % 12 == 0 {
            s.push_str("  ");
        }
        s.push_str(&alloc::format!("0x{:02x},", b));
        if i % 12 == 11 || i + 1 == bytes.len() {
            s.push('\n');
        } else {
            s.push(' ');
        }
    }
    s.push_str("];\n");
    write_out(out, out_cap, out_len, s.as_bytes())
}

fn write_out(out: *mut u8, out_cap: usize, out_len: *mut usize, src: &[u8]) -> i32 {
    if src.len() > out_cap {
        return -1;
    }
    unsafe {
        for (i, b) in src.iter().enumerate() {
            *out.add(i) = *b;
        }
        *out_len = src.len();
    }
    0
}

fn is_ident(s: &str) -> bool {
    let b = s.as_bytes();
    if b.is_empty() {
        return false;
    }
    let c0 = b[0];
    if !(c0.is_ascii_alphabetic() || c0 == b'_') {
        return false;
    }
    b.iter().all(|c| c.is_ascii_alphanumeric() || *c == b'_')
}

fn cstr<'a>(p: *const u8) -> &'a str {
    unsafe {
        let mut n = 0usize;
        while *p.add(n) != 0 {
            n += 1;
            if n > 128 {
                break;
            }
        }
        core::str::from_utf8_unchecked(core::slice::from_raw_parts(p, n))
    }
}

/// Host helper: allocate embed text into a Vec (not exported to C).
pub fn embed_c_string(name: &str, data: &[u8]) -> Option<Vec<u8>> {
    let mut name_z = String::from(name);
    name_z.push('\0');
    let mut out = alloc::vec![0u8; data.len() * 6 + 256];
    let mut olen = 0usize;
    let rc = unsafe {
        pm_metal_fs_embed_c(
            name_z.as_ptr(),
            data.as_ptr(),
            data.len(),
            out.as_mut_ptr(),
            out.len(),
            &mut olen,
        )
    };
    if rc != 0 {
        return None;
    }
    out.truncate(olen);
    Some(out)
}


use core::ffi::c_void;

use pymergetic_metal_reg::{pm_metal_reg_mod_load, RegMod};

pymergetic_metal_reg::reg_mod! {
    mod embed = "pymergetic.metal.fs.embed";
    exports: [c, rs];
}

extern "C" fn embed_register_symbols(_ctx: *mut c_void) -> i32 {
    embed::c.publish(pm_metal_fs_embed_c as *const c_void);
    embed::rs.publish(pm_metal_fs_embed_rs as *const c_void);
    0
}

static EMBED_MOD: RegMod = RegMod::from_static(
    embed::NAME,
    &embed::STORAGE.exports,
    &embed::STORAGE.imports,
    Some(embed_register_symbols),
);

#[no_mangle]
pub extern "C" fn pm_metal_fs_embed_reg_load() -> i32 {
    if pymergetic_metal_reg::find_mod(embed::NAME).is_some() {
        return 0;
    }
    unsafe { pm_metal_reg_mod_load(&EMBED_MOD) }
}

#[inline]
pub fn reg_load() -> i32 {
    pm_metal_fs_embed_reg_load()
}
